### ISSUE TITLE
Fuzzing multiple targets at once

### ISSUE THREAD

**Issue by magnusstubman** [google/honggfuzz#11]
While fuzzing network sniffers, I'd typically use something similair:

`honggfuzz -c ../external.sh -p 1234 -f input/ -- sudo tcpreplay -M topspeed -i lo ___FILE___`

Where pid 1234 belongs to a sniffer such as tshark/wireshark/tcpdump etc listening on the loopback interface.

With this setup I can easily start and configure multiple sniffers to listen on the loopback interface, and therefore also fuzz them with the same data generated by honggfuzz, however honggfuzz will in this setup have no knowledge of the other sniffers and therefore never save the input data once/if they crash.

What I want is the ability to honggfuzz to monitor multiple targets at once.

Please ask if I havn't made myself clear :)

**Comment by robertswiecki** [comment]
HI,

I think your request is kinda unique (for unique mode of using honggfuzz), but if you will submit a patch, I'll consider mergin it.

I can imagine that you could provide multiple -p argument, and save those to an array[] and not to an int. Then you would have to attach to all of the PIDs in arch_reapChild()

**Comment by robertswiecki** [comment]
I don't think I'll ever implement it - what is more I'm even thinking about removing this feature alltogether. Granted, it's useful sometimes, but slow and fuzzing should be done in persistent mode in such cases.
