### ISSUE TITLE
The dynamic file corpus is empty  bug with -C option in Mac

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#113]
I compiled libpng with `-fsanitize=address -fsanitize-coverage=bb`, then run the following cmd in mac osx :
`honggfuzz -C -f /samples/png -e png -- ./pngtest ___FILE___`

but it have a error"The dynamic file corpus is empty".

Do I using the wrong cmd or it need hardware supported?

> 
> ----------------------------[ honggfuzz v0.9alpha ]---------------------------
>   Iterations : 100
>        Phase : Dynamic Pre
>     Run Time : 0 hrs 0 min 10 sec (since: 2016-11-04 17:41:56)
>    Input Dir : '/samples/png'
>   Fuzzed Cmd : './pngtest ___FILE___'
>      Threads : 2, CPUs: 4, CPU: nan% (nan%/CPU)
>        Speed : 1/sec (avg: 10)
>      Crashes : 0 (unique: 0, blacklist: 0, verified: 0)
>     Timeouts : 0 [10 sec.]
>  Corpus Size : 0, max size (bytes): 613321
>     Coverage :
>        *** total hit #bb:  0 (coverage 0.00%)
>        *** total #dso:     0 (instrumented only)
>        *** discovered #bb: 0 (new from input seed)
>        *** crashes:        0
> -----------------------------------[ LOGS ]-----------------------------------
>
> [2016-11-04T17:42:06+0800][F][1034] fuzz_prepareFileDynamically():76 The dynamic file corpus is empty. Apparently, the initial fuzzing of the provided file corpus (-f) has not produced any follow-up files with positive coverage and/or CPU counters

```
ls /samples/png/
008b8bb75b8a487dc5aac86c9abb06fb.png      Waldau-plan.png
```

**Comment by riusksk** [comment]
I update the lasted version to fix it.

**Comment by robertswiecki** [comment]
Do you see any files in the HF_SANCOV dirctory?

**Comment by riusksk** [comment]
it reproduced again, without any file in HF_SANCOV dirctory.
do u konw why can't generate sancov.map file?

`
--------------------------------------[ LOGS ]--------------------------------------
[2016-11-19T20:16:35+0800][E][94068] sancov_sanCovParseRaw():375 sancov map file not found
`
