### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_LLVMFuzzerInitialize" in MacOS

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#115]
it have a bug when compiled libpng with Compile-time instrumentation in MacOS.

libpng_read_fuzzer.cc source code:
https://github.com/google/oss-fuzz/blob/master/targets/libpng/libpng_read_fuzzer.cc

```
riusksk@MacBook  ~/Downloads/libpng-master ‹›$ ./configure CFLAGS='-fsanitize-coverage=trace-pc-guard,indriect-calls,trace-cmp'
riusksk@MacBook  ~/Downloads/libpng-master ‹›$ make
riusksk@MacBook  ~/Downloads/libpng-master ‹›$ clang++ -std=c++11  libpng_read_fuzzer.cc ../honggfuzz/libhfuzz/libhfuzz.a ./.libs/libpng16.dylib -lz -o png_read_fuzzer
Undefined symbols for architecture x86_64:
  "_LLVMFuzzerInitialize", referenced from:
      _main in libhfuzz.a(persistent.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by robertswiecki** [comment]
Hm... might seem a bit like a problem with C vs C++ symbols. How have you compiled honggfuzz, also with clang++ ?

I guess it's some peculiarity of MacOS that symbols get underscore before name, or maybe MacOS doesn't support weak symbols.

If you don't use LLVMFuzzerInitialize you can try to remove it from persistent.c

I don't have currently access to MacOS X, but I can suggest is to try to compile code in libhfuzz with clang++ (you might want to surround it all with extern "C" { }), to see whether it helps.

**Comment by riusksk** [comment]
it still exist after complited honggfuzz with clang++, so I remove LLVMFuzzerInitialize from persistent.c, it's ok now.

**Comment by anestisb** [comment]
Adding `-Wl,-U,_LLVMFuzzerCustomMutator -Wl,-U,_LLVMFuzzerInitialize` should do the work. For example you fuzzer build should be like:
```
$ clang++ -std=c++11 -Wl,-U,_LLVMFuzzerCustomMutator -Wl,-U,_LLVMFuzzerInitialize libpng_read_fuzzer.cc -Ilibpng ~/Tools/Fuzzers/honggfuzz/libhfuzz/libhfuzz.a libpng/.libs/libpng16.dylib -lz -o png_fuzzer

$ otool -L png_fuzzer
png_fuzzer:
	/usr/local/lib/libpng16.16.dylib (compatibility version 43.0.0, current version 43.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

There is some more info from the chromium folks [here](https://reviews.llvm.org/D20741). It's a macOS specific issue.

**Comment by riusksk** [comment]
it's ok, thank you very much.

╭─riusksk@MacBook  ~/Downloads/libpng ‹›
╰─➤$ clang++ -std=c++11 -Wl,-U,_LLVMFuzzerCustomMutator -Wl,-U,_LLVMFuzzerInitialize libpng_read_fuzzer.cc -Ilibpng ../honggfuzz/libhfuzz/libhfuzz.a ./.libs/libpng16.dylib -lz -o png_fuzzer
╭─riusksk@MacBook  ~/Downloads/libpng ‹›
╰─➤$ ll png_fuzzer
-rwxr-xr-x  1 riusksk  staff    16K 11 27 15:55 png_fuzzer

**Comment by riusksk** [comment]
but the Compile-time instrumentation fuction can't run normal in MacOS, the "blocks seen" still is 0 and all processes run timeout:

----------------------------[ honggfuzz v0.9alpha ]---------------------------
  Iterations : 4
       Phase : Dynamic Fuzzing
    Run Time : 0 hrs 0 min 21 sec (since: 2016-11-27 16:03:28)
   Input Dir : '/Users/riusksk/Downloads/PngSuite'
  Fuzzed Cmd : './pngtest'
     Threads : 2, CPUs: 4, CPU: nan%
       Speed : 0/sec (avg: 0)
     Crashes : 0 (unique: 0, blacklist: 0, verified: 0)
    Timeouts : 104 [10 sec.]
 Corpus Size : 0, max size (bytes): 1795689
    Coverage :
       *** blocks seen:    0, comparison map: 0
--------------------------------------[ LOGS ]--------------------------------------
[2016-11-27T16:03:49+0800][W][842] subproc_checkTimeLimit():333 PID 851 took too much time (limit 10 s). Sending SIGKILL
[2016-11-27T16:03:49+0800][W][842] subproc_checkTimeLimit():333 PID 852 took too much time (limit 10 s). Sending SIGKILL
[2016-11-27T16:03:50+0800][W][842] subproc_checkTimeLimit():333 PID 851 took too much time (limit 10 s). Sending SIGKILL
[2016-11-27T16:03:50+0800][W][842] subproc_checkTimeLimit():333 PID 852 took too much time (limit 10 s). Sending SIGKILL
[2016-11-27T16:03:50+0800][W][842] subproc_checkTimeLimit():333 PID 851 took too much time (limit 10 s). Sending SIGKILL
[2016-11-27T16:03:50+0800][W][842] subproc_checkTimeLimit():333 PID 852 took too much time (limit 10 s). Sending SIGKILL
[2016-11-27T16:03:50+0800][W][842] subproc_checkTimeLimit():333 PID 851 took too much time (limit 10 s). Sending SIGKILL
[2016-11-27T16:03:50+0800][W][842] subproc_checkTimeLimit():333 PID 852 took too much time (limit 10 s). Sending SIGKILL

**Comment by riusksk** [comment]
clang maybe not support the compile arg '-fsanitize-coverage=trace-pc-guard,indriect-calls,trace-cmp'

> clang: warning: argument unused during compilation: '-fsanitize-coverage=trace-pc-guard,indriect-calls,trace-cmp'

> ─➤$ clang --version 
> Apple LLVM version 8.0.0 (clang-800.0.38)
> Target: x86_64-apple-darwin16.1.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

the `blocks seen` still is 0, and all fuzz processes are run timeout:

> Input Dir : '/Users/riusksk/Downloads/PngSuite'
>   Fuzzed Cmd : './pngtest'
>      Threads : 2, CPUs: 4, CPU: nan%
>        Speed : 0/sec (avg: 0)
>      Crashes : 0 (unique: 0, blacklist: 0, verified: 0)
>     Timeouts : 0 [10 sec.]
>  Corpus Size : 0, max size (bytes): 1795689
>     Coverage :
>        *** blocks seen:    0, comparison map: 0
> --------------------------------------[ LOGS ]--------------------------------------
> [2016-11-27T16:03:08+0800][W][467] subproc_Run():277 Could not send file contents to the persistent process
> [2016-11-27T16:03:08+0800][W][467] subproc_Run():277 Could not send file contents to the persistent process
> [2016-11-27T16:03:08+0800][W][467] subproc_Run():277 Could not send file contents to the persistent process

**Comment by anestisb** [comment]
The `clang-800.0.38` string indicates that you have Xcode 8.0 which comes with clang version 3.8. Most of the sanitizer options you're using have been added to later version of clang (most of them at 4.0 if I'm not mistaken).

You can either use Xcode 8.1 which comes with clang 4.2, install clang 4.2 from a package manager (brew, macports, etc.) or build clang from source.

If you don't want to change the system default Xcode, you can download latest Xcode 8.1 from apple developer website and have it a separate locaton (hint use `xcode-select -p <path>` to change the active one).

**Comment by robertswiecki** [comment]
-finstrument-functions should work with most clang/gcc versions but it offers function-level granularity only. Also, trace-cmp is pretty cool for increasing the coverage.

As for 'Could not send file contents to the persistent process' seems like sending data over persistent file-descriptor might be not working. I don't know how to check that in MacOS but it'd be good to check whether file-descriptors 1022 and 1023 are open in your pngtest. Maybe the dynamic loader from MacOS closes them?

**Comment by robertswiecki** [comment]
BTW, here's png testing code I used some time ago - http://pastebin.com/qbkw0k1L

It's made for Linux, hence the use of /proc/self/fd/100 and memfd_create. I guess it could be quickly rewritten for MacOS - possibly libpng can load data from a buffer instead of external file as well.

**Comment by riusksk** [comment]
clang 4.2.1 (update xcode to 8.1 )also not support the compile arg  '-fsanitize-coverage=trace-pc-guard,indriect-calls,trace-cmp'

>  clang: warning: argument unused during compilation: '-fsanitize-coverage=trace-pc-guard,indriect-calls,trace-cmp'
> /bin/sh ./libtool  --tag=CC   --mode=link gcc  -fsanitize-coverage=trace-pc-guard,indriect-calls,trace-cmp   -o timepng contrib/libtests/timepng.o libpng16.la -lz 
> libtool: link: gcc -fsanitize-coverage=trace-pc-guard,indriect-calls,trace-cmp -o .libs/timepng contrib/libtests/timepng.o  ./.libs/libpng16.dylib -lz
> jane@MacBook-Pro:~/riusksk/libpng$ clang --version
> Apple LLVM version 8.0.0 (clang-800.0.42.1)
> Target: x86_64-apple-darwin16.1.0
> Thread model: posix
> InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by robertswiecki** [comment]
IIRC clang-3.9 should work with trace-pc, which seems slower than trace-pc-guard.

I'm not sure if there's clang-4.2 yet, I think 4.0 is still "under construction"?

**Comment by riusksk** [comment]
I build from clang 4.0 sources use to compile libpng project, but have a error which maybe caused by symbols get underscore before name in MacOS. 
Do you have method can be used to solve this symbol problem?

> configure:3320: clang -fsanitize-coverage=trace-pc,indirect-calls,trace-cmp -g -Wl,-U,_sanitizer_cov_trace_pc   conftest.c  >&5
> Undefined symbols for architecture x86_64:
>   "___sanitizer_cov_trace_pc", referenced from:
>       _main in conftest-de8e5d.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> configure:3324: $? = 1
> configure:3362: result: no

**Comment by robertswiecki** [comment]
You need to link it with libhfuzz/libfuzz.a

If you use configure, you might want to set LIBS="<path_to_honggfuzz>/libhfuzz/libhfuzz.a"

My sample configure script for bind

LIBS="/home/user/src/honggfuzz/libhfuzz/*.o" CC=clang-4.0 CXX=clang++-4.0 CFLAGS="$CFLAGS -g -ggdb -march=skylake -fsanitize=address -fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp -fno-builtin" LDFLAGS="$CFLAGS" ./configure --prefix=/home/user/fuzz/bind/dist/ --enable-threads --without-gssapi --enable-querytrace --disable-chroot --disable-linux-caps --disable-seccomp --without-libtool

BTW, If you use -fsanitize=address then libFuzzer will provide your own symbol __sanitizer_cov_trace_pc, and it will take preference over libhfuzz.a. In such case I propose linkin adding path to

<honggfuzz>/libhfuzz/instrument.o

somewhere early in the linking command (e.g. with LDFLAGS)

**Comment by riusksk** [comment]
compiled ok with libhfuzz/libfuzz.a and libhfuzz/*.o，but it have a lot of timeout during fuzzing.
is it run normal?

> export CC=clang-4.0 CXX=clang++-4.0
> 
> export LIBS="~/honggfuzz/libhfuzz/*.o ~/honggfuzz/libhfuzz/libhfuzz.a"
> 
> ./configure CFLAGS='-fsanitize=address -fsanitize-coverage=trace-pc,indirect-calls,trace-cmp -g -Wl,-U,_LLVMFuzzerTestOneInput’
> 
> make
> 
> clang++ -std=c++11 -Wl,-U,_LLVMFuzzerCustomMutator -Wl,-U,_LLVMFuzzerInitialize libpng_read_fuzzer.cc -Ilibpng ~/honggfuzz/libhfuzz/libhfuzz.a .libs/libpng16.dylib -lz -o png_fuzzer
> 
> honggfuzz -z -P -f ~/samples/png -e png -- ./png_fuzzer

```
     Crashes : 0 (unique: 0, blacklist: 0, verified: 0)
     Timeouts : 2206 [10 sec]
  Corpus Size : 2, max size (bytes): 2866161
     Coverage :
        *** blocks seen:    294, comparison map: 11113
 -----------------------------------[ LOGS ]-----------------------------------
[2016-12-04T10:48:51+0800][W][57589] subproc_checkTimeLimit():333 PID 57591 took too much time (limit 10 s). Sending SIGKILL
[2016-12-04T10:48:51+0800][W][57589] subproc_checkTimeLimit():333 PID 57590 took too much time (limit 10 s). Sending SIGKILL
[2016-12-04T10:48:51+0800][W][57589] subproc_checkTimeLimit():333 PID 57591 took too much time (limit 10 s). Sending SIGKILL
[2016-12-04T10:48:51+0800][W][57589] subproc_checkTimeLimit():333 PID 57590 took too much time (limit 10 s). Sending SIGKILL
[2016-12-04T10:48:52+0800][W][57589] subproc_checkTimeLimit():333 PID 57591 took too much time (limit 10 s). Sending SIGKILL
[2016-12-04T10:48:52+0800][W][57589] subproc_checkTimeLimit():333 PID 57590 took too much time (limit 10 s). Sending SIGKILL
[2016-12-04T10:48:52+0800][W][57589] subproc_checkTimeLimit():333 PID 57591 took too much time (limit 10 s). Sending SIGKILL
[2016-12-04T10:48:52+0800][W][57589] subproc_checkTimeLimit():333 PID 57590 took too much time (limit 10 s). Sending SIGKILL

**Comment by riusksk** [comment]
maybe _LLVMFuzzerTestOneInput symbol error.

`clang-4.0: warning: -Wl,-U,_LLVMFuzzerTestOneInput: 'linker' input unused [-Wunused-command-line-argument]`

**Comment by robertswiecki** [comment]
Hm.. I don't think there's a code yet in mac/ to support persistent fuzzing?

You can try to compile with OS=POSIX, though as far as I can tell MacOSX doesn't support timers used in posix/

You can also try to add persistent fuzzing, basically you'd need to take a look at posix/arch.c use of -> persistent and adapt it to mac/

**Comment by robertswiecki** [comment]
Current;y your persistent session possibly starts, and maybe even input it sent to your persistent process, but there's no code which would be checking that the round has ended.

That's why we use poll() and waitpid(WNOHANG) in posix/arch.c

The mac code is using usleep waitpid(WNOHANG), and to make it work it needs to be made compatible with posix/arch.c

I guess you should start with checking whether there is some good way of inducing timer based interrupts in MacOS, and basically adapt code from posix/ after that (if MacOS X supports poll)

**Comment by robertswiecki** [comment]
To quickly check the hypothesis you can change

    if (hfuzz->tmOut) {
        options |= WNOHANG;
    }

to

    if (hfuzz->tmOut || hfuzz->persistent) {
        options |= WNOHANG;
    }

and add

                 if (subproc_persistentModeRoundDone(hfuzz, fuzzer) == true) {
                    break;
                }

to check for the round being done. If this condition is true (round done) you should exit the for(;;) loop (not the while() loop).
