### ISSUE TITLE
Death by infinite loop

### ISSUE THREAD

**Issue by nezetic** [google/honggfuzz#127]
Using honggfuzz (nice tool btw), I have faced an interesting issue.

I was fuzzing a dynamic library on Android (closed source), using persistent mode and basic hardware code coverage.
Several code paths were full of infinite loops, triggering tons of hangs.
And basically, honggfuzz was dying in a few seconds (with performances dropping from very good to very very bad).

After investigating, I've found that honggfuzz was killing the child due to a timeout, as expected, but feedback routines were still called.

Problem is, during an infinite loop, performance counter values are high.
So faulty test case was found interesting by _fuzz_perfFeedback_ and kept, literally poisoning the fuzzer by maximizing the hangs.

I've written a quick and dirty patch, and performances came from an average of 10 tests per seconds to more than 1000.

[ignore_hangs_patch.txt](https://github.com/google/honggfuzz/files/777858/ignore_hangs_patch.txt)

**Comment by nezetic** [comment]
Sorry for providing a lame .txt instead of a pull request, but I honestly didn't spend more than a few minutes on my patch, didn't thinking about better ways or consequences. As I said, a few thoughts and a dirty hack ;)

**Comment by robertswiecki** [comment]
I've added:

https://github.com/google/honggfuzz/commit/44f6b194a2dc0d684a12b5b2e7a7224f3345de8c

Hope this will help you

**Comment by nezetic** [comment]
Yup, should solve this corner case perfectly.

Thank you very much for the _faster than light_ patch.
