### ISSUE TITLE
Error when build arm on release version 0.9

### ISSUE THREAD

**Issue by TinyNiko** [google/honggfuzz#128]
~/Downloads/honggfuzz-0.9$ third_party/android/scripts/compile-libunwind.sh third_party/android/libunwind x86_64
fatal: Not a git repository (or any of the parent directories): .git
[-] git submodules init failed

~/Downloads/honggfuzz-0.9$ third_party/android/scripts/compile-libunwind.sh third_party/android/libunwind arm
fatal: Not a git repository (or any of the parent directories): .git
[-] git submodules init failed

**Comment by ChrysanthemumHW** [comment]
I think you need to run "git init" in "third_party/android/libunwind" directory first, and then do compile.
