### ISSUE TITLE
Honggfuzz exits unexpectedly

### ISSUE THREAD

**Issue by n30m1nd** [google/honggfuzz#132]
Having the following "mutator"
```bash
root@IPHONE9:/home/javier/Fuzzing/Sessions/hongg_resolv_conf# cat ../wot.sh 
#!/bin/sh
echo "WOT" > $1
```
And choosing `-s` switch for `stdin`, the following command exits unexpectedly after a while:
```bash
/home/javier/Fuzzing/Fuzzers/honggfuzz/honggfuzz -f . -c /home/javier/Fuzzing/Sessions/wot.sh -s -n 1 -- tee /tmp/test
```
With the following error:
```
[2017-04-05T20:08:09+0100][E][21756] subproc_System():315 Command '/home/javier/Fuzzing/Sessions/wot.sh' terminated with signal: 11
[2017-04-05T20:08:09+0100][E][21756] fuzz_prepareFileExternally():146 Subprocess '/home/javier/Fuzzing/Sessions/wot.sh' returned abnormally
[2017-04-05T20:08:09+0100][F][21756] fuzz_fuzzLoop():532 fuzz_prepareFileExternally() failed
```
~~Also it doesn't generate any `/tmp/test` file.~~ It does but still fails after a while.

**Comment by robertswiecki** [comment]
Hm... using "-f ." is tricky, as it will also pick up .honngfuzz files used for storing input files. Does it repeat with -f <some_external_file>

**Comment by n30m1nd** [comment]
Yes, still failed with.
```bash
honggfuzz -f Testcases/resolvconf/ --covdir /tmp/testcoverage/ -s -n 1 -c /home/javier/Fuzzing/Sessions/wot.sh -- tee /tmp/tees
```
Errors again:
```
[2017-04-26T00:12:18+0100][E][32732] subproc_System():315 Command '/home/javier/Fuzzing/Sessions/wot.sh' terminated with signal: 11
[2017-04-26T00:12:18+0100][E][32732] fuzz_prepareFileExternally():146 Subprocess '/home/javier/Fuzzing/Sessions/wot.sh' returned abnormally
[2017-04-26T00:12:18+0100][F][32732] fuzz_fuzzLoop():537 fuzz_prepareFileExternally() failed
```

**Comment by robertswiecki** [comment]
Hm.. The  command (wot.sh) files with SIGSEGV. It can be that it's actually our code after fork, but what do you have in wot.sh?

**Comment by n30m1nd** [comment]
This happens as well when using radamsa as an external fuzzer.
The contents of `wot.sh` are:
_wot.sh_
```bash
root@IPHONE9:/home/javier/Fuzzing/Sessions/hongg_resolv_conf# cat ../wot.sh 
#!/bin/sh
echo "WOT" > $1
```

**Comment by robertswiecki** [comment]
I changed external file generation with some patches, could you try with the newest pull?

BTW: It's possible to use now both -f and -c. The external mutator will be used on files read from -f <dir>

**Comment by n30m1nd** [comment]
Still fails with freshly git pull'd and make'd build... I am starting to be suspicious that it can be something to do with my setup more than your (awesome) fuzzer.
The errors are still the same (exits with code SIGSEGV code 11). 

Also when running with more than one thread it happens to have concurrency problems with the file __[UNSET]__ 
Shall I open a new issue for this or being that it is a problem of the same functionality (`-c`) report it here as well?

**Comment by dyjakan** [comment]
I have similar issue for versions > 0.7.

I'm calling `radamsa` from within a custom bash script and it's fails consistently.

**Comment by robertswiecki** [comment]
I'm pretty certain it's this https://sourceware.org/bugzilla/show_bug.cgi?id

Could you try running this with glibc-2.24 or newer (or glibc-2.23-ubuntu6 from Ubuntu) - Xenial should have it

**Comment by robertswiecki** [comment]
With https://github.com/google/honggfuzz/commit/810d2c973f33cddd54ef880df716f93e3fa1b038 I also implemented a fall-back mechanism for Linux.

If the glibc is safe-to-use (>=2.23), fork() is used. If not, clone() is used. clone() is not as good as safe-to-use fork(), but it's better than unsafe-fork().

In any case, using distro with glibc 2.24 or better is advised with honggfuzz.

**Comment by n30m1nd** [comment]
I can confirm it is not crashing anymore now! Thanks so much for the fix.
There is one little caveat now about cleanup: When stopping the fuzzer it will leave the following files:
```bash
-rw-r--r--  1 javier javier  2316 Jun  3 10:04 honggfuzz.input.0.fuzz
-rw-r--r--  1 javier javier  1320 Jun  3 10:04 honggfuzz.input.1.fuzz
-rw-r--r--  1 javier javier   378 Jun  3 10:04 honggfuzz.input.2.fuzz
-rw-r--r--  1 javier javier 31050 Jun  3 10:04 honggfuzz.input.3.fuzz
```
And since these files are there, the fuzzer won't run untill these are deleted.
Again, thanks for your time Robert, such an awesome job!

**Comment by dyjakan** [comment]
Oh btw, for me it also works like a charm now. 👍

**Comment by robertswiecki** [comment]
> And since these files are there, the fuzzer won't run untill these are deleted.

I've fixed the behavior in HEAD. The files should be generally deleted in fuzz_fuzzLoop() unless honggfuzz is killed with SIGKILL or so.
