### ISSUE TITLE
where is the file of fuzzedlib.c

### ISSUE THREAD

**Issue by xiaosatianyu** [google/honggfuzz#134]
when using compile-time instrumentation with clang as the FeedbackDrivenFuzzing.md in docs, it puzzles me a lot that how to execute the command of "clang-4.0 -fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp fuzzedlib.c -o fuzzedlib.o". 
Where is the file of fuzzedlib.c ? Strange! 
Thank you!

**Comment by robertswiecki** [comment]
It's the library that you're going to fuzz. It generally says you need to compile your library with instrumentation. E.g. for libjpeg it'd be

CFLAGS="-fsanitize-coverage=trace-pc-guard,indirect-calls,trace-cmp" CC=clang-4.0 ./configure

in the directory with the library you want to fuzz, e.g. inside jpeg-9b

fuzzedlib.c just assumes that your library is composed of a single file, but in 99% of cases, you need to compile the whole library with those options (e.g. via configure)
