### ISSUE TITLE
how to detect windows gui app crash by honggfuzz?

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#135]
honggfuzz not support to check windows gui app crash, beacause it only support to check command program crash with POSIX signal interface via CygWin .

WerFault.exe is launched when windows gui app crash, and windows GUI app process is still exist, so honggfuzz can't detect whether to crash.

![](http://123.57.62.158/crash.png)

do u have some solution to slove this issue? 

Here is  a few solutions what I think：
1、Loop check if the WerFault.exe process exist
2、close werfault. Exe warning if system allow, so that windows GUI app crash which can be catched by honggfuzz.

**Comment by riusksk** [comment]
`/* Return true if windows GUI app crash */

bool arch_checkCrash() {
    char buffer[128];
    char result[128];

    FILE* pipe = popen("taskkill /F /IM WerFault.exe", "r");
    if (!pipe){
          return 0;
    }

    while(!feof(pipe)) {
        if(fgets(buffer, 1024, pipe)){
                strcat(result,buffer);
        }
    }

    //if(strstr(result, "成功")){
    if(strstr(result, "PID")){
        //printf("crash\n");
        pclose(pipe);
        return true;
    }else{
        //printf("no crash\n");
        pclose(pipe);
        return false;
    }
}`

**Comment by robertswiecki** [comment]
Sure, if you come up with some working code, feel free to send a merge pull my way.
