### ISSUE TITLE
Missing contents on the website

### ISSUE THREAD

**Issue by x8-999-github** [google/honggfuzz#137]
On the website https://google.github.io/honggfuzz/ there text with a broken link to details on ho how to run hongfuzz on Android

The file however is not present in the hg-pages branch of the project and the link is therefore broken.

I found the file https://github.com/google/honggfuzz/blob/master/docs/Android.md on the master branch so either the link need to be changed or the file needs to exist in the hg-pages branch.

**Comment by robertswiecki** [comment]
Thanks for the report.

 Yes, the links were relative (both for docs/Android.md and for docs/USAGE.md).

I fixed it now.
