### ISSUE TITLE
Error occured when compile libunwind

### ISSUE THREAD

**Issue by ChrysanthemumHW** [google/honggfuzz#138]
When i try to compile libunwind by **third_party/android/scripts/compile-libunwind.sh third_party/android/libunwind arm64**, then I get a error  **“/mnt/disk/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lgcc_s”**. But I have found **libgcc_s.so** in **/usr/lib/gcc** path, and it is a valid soft_link to **/lib/x86_64-linux-gnu/libgcc_s.so.1**. 
i am so confused.

**Comment by anestisb** [comment]
Honggfuzz applies a set of patches to upstream libunwind to fix NDK compilation issues and some bugs/improvements for arm/aarch64 unwinding. If you get this error message it means that the patches have not been successfully applied or something conflicts in the submodule handling automation from the scripts.

Building honggfuzz vanilla upstream for all Android archs seems to work fine with latest ndk r14b, so something is broken or in a non-handled state in your workspace. I suggest that you hard reset to upstream master branch for main & submodules and try again.

I've created a branch to tide-up and improve the submodules/patches handling [here](https://github.com/anestisb/honggfuzz/tree/libunwind-patches), although I didn't find the time yet to carefully test it.

**Comment by robertswiecki** [comment]
On slightly different note: In https://github.com/google/honggfuzz/issues/139 we're preparing for 1.0 release (possibly next week). Maybe we can make sure that whatever doesn't work in 0.9, works in 1.0? Just a suggestion.

**Comment by anestisb** [comment]
@robertswiecki sure. Will test again the improvements and PR them before the 1.0 release.

**Comment by ChrysanthemumHW** [comment]
THANK you very much, i have been solved  that problem. 
BUT when i execute make with android PHONY to cross-compile from project's root directory, error occurs again. The OUTPUT is :
**running CONFIG_SHELL=/bin/sh /bin/sh ./configure --host=aarch64-linux-android --disable-coredump host_alias=aarch64-linux-android CC=/mnt/disk/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc --sysroot=/mnt/disk/android-ndk-r13b/platforms/android-21/arch-arm64 CXX=/mnt/disk/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ --sysroot=/mnt/disk/android-ndk-r13b/platforms/android-21/arch-arm64 --no-create --no-recursion
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... Invalid configuration `aarch64-linux-android': machine `aarch64-linux' not recognized
configure: error: /bin/sh config/config.sub aarch64-linux-android failed
make[1]: *** [config.status] Error 1
make[1]: Leaving directory `/mnt/disk/git_test/third_party/android/libunwind'
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
checking build system type... x86_64-unknown-linux-gnu
checking host system type... Invalid configuration `aarch64-linux-android': machine `aarch64-linux' not recognized
configure: error: /bin/sh config/config.sub aarch64-linux-android failed**
