### ISSUE TITLE
honggfuzz does not build with gcc7

### ISSUE THREAD

**Issue by bmwiedemann** [google/honggfuzz#145]
apparently gcc7 dropped the `-Wno-initializer-overrides -Wno-unknown-warning-option` options used in `Makefile`
and added some new warnings that become errors because of `-Werror`

**Comment by robertswiecki** [comment]
Thanks for the report. This might have been fixed by 

https://github.com/google/honggfuzz/commit/ab7134a040e865b8f2f0486c43f86f64442781f6

**Comment by bmwiedemann** [comment]
actually, that only solves the first part, but the extra warnings still trigger -Werror

**Comment by robertswiecki** [comment]
Hi, could you post the compilation log? Seems my ultra-fresh Ubuntu doesn't have gcc-7, only gcc-6

**Comment by bmwiedemann** [comment]
We have gcc7 in openSUSE Tumbleweed. But even on other/older OSes you can do
```bash
osc checkout devel:tools/honggfuzz ; cd $_
osc build --alternative-project openSUSE:Factory standard
```

I currently dropped -Werror there via gcc7.patch so it will not fail on the warnings.

Here is an extract:
```
cc -c -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -g -D_GNU_SOURCE -Wall -Wframe-larger-than=131072 -std=c11 -I/usr/local/include -I/usr/include -Wextra -Wno-override-init -funroll-loops -D_FILE_OFFSET_BITS=64 -D_HF_ARCH_LINUX -o util.o util.c
fuzz.c: In function 'fuzz_threadNew':
fuzz.c:275:40: warning: '.verified' directive output may be truncated writing 9 bytes into a region of size between 1 and 4096 [-Wformat-truncation=]
     snprintf(verFile, sizeof(verFile), "%s.verified", crashedFuzzer->crashFileName);
                                        ^~~~~~~~~~~~~
In file included from /usr/include/stdio.h:939:0,
                 from fuzz.c:36:
/usr/include/bits/stdio2.h:64:10: note: '__builtin___snprintf_chk' output between 10 and 4105 bytes into a destination of size 4096
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by robertswiecki** [comment]
Hm... this fortify source check here "is not the best one" ;). Thanks for the report. The snprintf() here is used as expected IMO, I'll see whether fortify source can be silenced/disabled for this code.
