### ISSUE TITLE
compilation error with hfuzz-gcc

### ISSUE THREAD

**Issue by RealBatCoin** [google/honggfuzz#148]
hi
i am trying to compile memcached with the help of hfuzz-gcc in order to instrument it
when i execute 
HFUZZ_CC_ASAN=1 CC=~/Desktop/honggfuzz-master/hfuzz_cc/hfuzz-gcc CXX=$CC ./configure
i receive the following error in the config.log :

Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
configure:3312: $? = 0
configure:3301: /home/da5h/Desktop/honggfuzz-master/hfuzz_cc/hfuzz-gcc -V >&5
cc: error: unrecognized command line option '-fsanitize-coverage=trace-pc'
cc: error: unrecognized command line option '-V'
configure:3312: $? = 1
configure:3301: /home/da5h/Desktop/honggfuzz-master/hfuzz_cc/hfuzz-gcc -qversion >&5
cc: error: unrecognized command line option '-fsanitize-coverage=trace-pc'
cc: error: unrecognized command line option '-qversion'
configure:3312: $? = 1
configure:3332: checking whether the C compiler works
configure:3354: /home/da5h/Desktop/honggfuzz-master/hfuzz_cc/hfuzz-gcc    conftest.c  >&5
cc: error: unrecognized command line option '-fsanitize-coverage=trace-pc'
configure:3358: $? = 1
configure:3396: result: no
configure: failed program was:
 /* confdefs.h */
| #define PACKAGE_NAME "memcached"
| #define PACKAGE_TARNAME "memcached"
| #define PACKAGE_VERSION "UNKNOWN"
| #define PACKAGE_STRING "memcached UNKNOWN"
| #define PACKAGE_BUGREPORT "memcached@googlegroups.com"
| #define PACKAGE_URL ""
| #define PACKAGE "memcached"
| #define VERSION "UNKNOWN"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3401: error: in `/home/da5h/Desktop/memcached-next':
configure:3403: error: C compiler cannot create executables

i checked and my gcc version should support this flags
any help would be appreciated

**Comment by robertswiecki** [comment]
Works for me with

$ gcc -v
Thread model: posix
gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2) 

Though, not with gcc 5

$ HFUZZ_CC_PATH=gcc-5 ~/src/honggfuzz/hfuzz_cc/hfuzz-gcc a.c -o a
cc: error: unrecognized command line option ‘-fsanitize-coverage=trace-pc’

**Comment by RealBatCoin** [comment]
updated gcc to gcc 7
