### ISSUE TITLE
 Compiling Error (Fuzz.o)

### ISSUE THREAD

**Issue by lmaohtp** [google/honggfuzz#149]
cc -c -O3 -D_GNU_SOURCE -Wall -Werror -Wframe-larger-than=131072 -std=c11 -I/usr/local/include -I/usr/include -Wextra -Wno-override-init -funroll-loops -D_FILE_OFFSET_BITS=64 -D_HF_ARCH_LINUX -o fuzz.o fuzz.c
fuzz.c: In function ‘fuzz_threadNew’:
fuzz.c:324:40: error: ‘.verified’ directive output may be truncated writing 9 bytes into a region of size between 1 and 4096 [-Werror=format-truncation=]
     snprintf(verFile, sizeof(verFile), "%s.verified", crashedFuzzer->crashFileName);
                                        ^~~~~~~~~~~~~
fuzz.c:324:5: note: ‘snprintf’ output between 10 and 4105 bytes into a destination of size 4096
     snprintf(verFile, sizeof(verFile), "%s.verified", crashedFuzzer->crashFileName);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:242: fuzz.o] Error 1

**Comment by robertswiecki** [comment]
Thanks, I've seen this warning before - if I'm not mistaken it's fortify-source thing? In any case I'll think on how to silence it, as it's not a bug in our code.

**Comment by robertswiecki** [comment]
Please try with https://github.com/google/honggfuzz/commit/bcbead20ab264e4ce38eb75c4cb5675cc4c3a4fb or with HEAD. Though, I don't have access to gcc-7 to test it.

**Comment by lmaohtp** [comment]
I just tested it and it worked but i've encountered another compiling error.
