### ISSUE TITLE
Compiling Error (libhfuzz/instrument.o)

### ISSUE THREAD

**Issue by lmaohtp** [google/honggfuzz#150]
libhfuzz/instrument.c: In function ‘__sanitizer_cov_trace_cmp’:
libhfuzz/instrument.c:180:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         __sanitizer_cov_trace_cmp1(Arg1, Arg2);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libhfuzz/instrument.c:181:5: note: here
     case (sizeof(uint16_t)):
     ^~~~
libhfuzz/instrument.c:182:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         __sanitizer_cov_trace_cmp2(Arg1, Arg2);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libhfuzz/instrument.c:183:5: note: here
     case (sizeof(uint32_t)):
     ^~~~
libhfuzz/instrument.c:184:9: error: this statement may fall through [-Werror=implicit-fallthrough=]
         __sanitizer_cov_trace_cmp4(Arg1, Arg2);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libhfuzz/instrument.c:185:5: note: here
     case (sizeof(uint64_t)):
     ^~~~
cc1: all warnings being treated as errors
make: *** [Makefile:257: libhfuzz/instrument.o] Error 1

**Comment by robertswiecki** [comment]
Well, gcc-7 seems fun :)

https://github.com/google/honggfuzz/commit/d9e96986c2b75c2c926221bd32e8b56541e1402b

**Comment by lmaohtp** [comment]
Well done and thanks for fixing it
