### ISSUE TITLE
Maximum number of concurrent fuzzing threads

### ISSUE THREAD

**Issue by prashast** [google/honggfuzz#154]
Hi, I am trying to use hongfuzz to fuzz a lighttpd webserver running in an emulated environment and listening at a particular socket. I am using hongfuzz as given below:
```
~/honggfuzz/honggfuzz -vn 4 -f corpus_http1 -w ./httpd.wordlist --covdir coverage/ -s -p "`pidof qemu-system-mips`" -- /bin/nc 192.168.0.100 80
```
As you can see in the command, I've been trying to specify the number of concurrent fuzzing threads, however when I try to do that it gives me this message `lowering maximum number of concurrent threads to 1` and then starts the fuzzing process using only one thread. Is there any other flag that I need to specify in order to get the fuzzer to run on multiple threads or a workaround for this?

**Comment by robertswiecki** [comment]
Not with -p, there's no code which would be attaching to multiple processes. In theory it's possible, just would require a day or two of coding.

I seriously suggest adapting code from apache - https://github.com/google/honggfuzz/blob/master/examples/apache/httpd-master.honggfuzz.patch - this will allow both for persistent fuzzing (faster), and for multiple threads. Though, I'm not sure how easy it would be given that you use qemu-system-mips

**Comment by robertswiecki** [comment]
One additional problem that you would face is that you'll have multiple lighthttpd processes listening on different ports. And there will be now way to tell 'nc' created from distinct threads that they should connect to different ports, as all 'nc' processes will be run with the same command-line. You could technically use a script and read _HF_THREAD_NO_ENV envvar, but using persistent mode will be faster/easier-to-maintain I guess.

**Comment by prashast** [comment]
Oh, I assumed by the `-n` switch description that it would allow me to run multiple fuzzing instances with a master-slave model that would sync up with each other like in AFL. So I assume that kind of functionality isn't present as of now. Though I'm curious as to what the `-n` switch can exactly be used for then?

Also, compiling it with hfuzz is not an option because what I have are these blackbox binaries that I'm running inside an emulator. There is only a single lighttpd webserver process which is listening on port 80 and 443, though right now I'm just testing on port 80.

Also, as you can see I'm monitoring the qemu pid for a crash but it's based on the assumption that the crashing input will crash the qemu emulation as well. Do you have any ideas as to how it could be possible for me to monitor the lighttpd process directly from the host?(Apart from running hongfuzz inside the emulated environment which doesn't seem feasible)

**Comment by robertswiecki** [comment]
-n directly enables multiple threads, which in turn can monitor multiple processes. It works in most of modes, except -p.

I think honggfuzz will work here with qemu because it uses ptrace, and therefore will see signals, even if these are handled by qemu. You don't seem to be using any instrumentation, therefore in your case -n 5 is equal to running honggfuzz 5 times separately. As no new feedback will be added to the corpus, it will be equivalent to dumb fuzzing.

**Comment by prashast** [comment]
Got it, thanks for answering. :+1:
