### ISSUE TITLE
Improve Apache example

### ISSUE THREAD

**Issue by frapik99** [google/honggfuzz#155]
Hi all,
I have noticed that if you clone the Apache repo the configure bash script is not present. I've created it via the following command:

```
./buildconf --with-apr=../apr-1.6.2 --with-apr-util=../apr-util-1.6.0
```

I think it can help everyone.

Thanks

**Comment by robertswiecki** [comment]
Thanks, done in https://github.com/google/honggfuzz/commit/d72f88829843080f91936426bc1f51036ff80c0d
