### ISSUE TITLE
Problem fuzzing Apache

### ISSUE THREAD

**Issue by frapik99** [google/honggfuzz#156]
Hi,
I followed the example that explains how to fuzz Apache and I think I have done all correctly. Unfortunately when I try to effectively fuzz it I have the following error:

```
[F][25041] fuzz_prepareFileDynamically():76 The dynamic file corpus is empty. Apparently, the initial fuzzing of the provided file corpus (-f) has not produced any follow-up files with positive coverage and/or CPU counters
```

The command I used was:

```
/honggfuzz -z -P -f ./examples/apache/corpus_http2 -w ./examples/apache/httpd.wordlist -- /home/fra/Desktop/fuzzing/apache/dist/bin/httpd -X -f ../apache/dist/conf/httpd.conf.h2 
```

The same happend with ```corpus_http1```

Anyone able to help?

Thanks

**Comment by robertswiecki** [comment]
Your httpd seems to be compiled w/o coverage? I guess you used hfuzz-clang as CC, and you have a fairly new version of clang (>=4.0)?

Feel free to try with newer compilation script from this patch: https://github.com/google/honggfuzz/blob/master/examples/apache/httpd-master.honggfuzz.patch

PS: @icing has created a more streamlined compilation setup for Apache (mainly HTTP/2 but should be easily convertible to HTTP1 by changing config and corpus paths) here: https://github.com/icing/h2fuzz

**Comment by robertswiecki** [comment]
One of the test you could try is to change CC from hfuzz-clang to hfuzz-gcc and see whether it has any effect
