### ISSUE TITLE
can we use honggfuzz to open input file , not mutate generate file?

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#158]
I want to test some crash files, so only need use honggfuzz to open these files and monitor crash.
Does it have this function?

**Comment by robertswiecki** [comment]
I guess might simply run it with -N <number of files in your queue>

I think we could add something like that (dry run)

**Comment by robertswiecki** [comment]
Hm.. actually there's verifier mode (-V), I'm not sure if this can help but maybe you can use it for dry mode.

From source code, you need to specifiy both -V and -r 0.0

**Comment by riusksk** [comment]
dose it can open all input files only one time if use -V and -r 0.0  ?
or open random file in input dir?
