### ISSUE TITLE
compiling on centos7 fail

### ISSUE THREAD

**Issue by KnoooW** [google/honggfuzz#164]
**1. use clang/clang++ as compiler**
clang version 3.7.0
```
$CC=clang CXX=clang++ make
clang -c -O3 -D_GNU_SOURCE -Wall -Werror -Wframe-larger-than=131072 -Wno-format-truncation -std=c11 -I/usr/local/include -I/usr/
include -Wextra -Wno-override-init -funroll-loops -D_FILE_OFFSET_BITS=64 -Wno-initializer-overrides -Wno-unknown-warning-option -fblocks -D_HF_ARCH_LINUX -o linux/ptrace_utils.o linux/ptrace_utils.cIn file included from linux/ptrace_utils.c:50:
/usr/include/unistd.h:1147:35: error: __block attribute not allowed, only allowed on local variables
extern void encrypt (char *__block, int __edflag) __THROW __nonnull ((1));
                                  ^
linux/ptrace_utils.c:1345:26: error: use of undeclared identifier 'PTRACE_O_EXITKILL'
        seize_options |= PTRACE_O_EXITKILL;
                         ^
2 errors generated.
make: *** [linux/ptrace_utils.o] Error 1
```
fix ptrace error with adding "#include <linux/ptrace.h>" in linux/ptrace_utils.c
but I'v not found method to fix the first error

**2. use gcc as compiler**
```
linux/ptrace_utils.c: In function ‘arch_ptraceAttach’:
linux/ptrace_utils.c:1345:26: error: ‘PTRACE_O_EXITKILL’ undeclared (first use in this function)
         seize_options |= PTRACE_O_EXITKILL;
                          ^
linux/ptrace_utils.c:1345:26: note: each undeclared identifier is reported only once for each function it appears in
linux/ptrace_utils.c: At top level:
cc1: error: unrecognized command line option "-Wno-format-truncation" [-Werror]
cc1: all warnings being treated as errors
make: *** [linux/ptrace_utils.o] Error 1
```

can be fixed by adding header include in ptrace_utils.c

But after  I fixed ptrace header error and continue to  make, another error happen:
```
libcommon/files.c:44:25: fatal error: linux/memfd.h: No such file or directory
 #include <linux/memfd.h>
                         ^
compilation terminated.
make: *** [libcommon/files.o] Error 1
```

I searched my /usr/include , there's no memfd.h.
My OS is too old that you dont support ??

all test on master branch.

**Comment by KnoooW** [comment]
OK, I have fixed the __block error by changing my unistd.h,
but memfd seems only on new version linux ?

**Comment by robertswiecki** [comment]
I've made it easier to compiler under older distros (re memfd) in https://github.com/google/honggfuzz/commit/c7da7e2919f9159ac457ce8acb2fd2d3809f334c

As for __block, this keyword is reserved in clang, not sure who maintains your /usr/include/unistd.h - maybe asking them to change the name to sth else (the argument name is arbitrary anyway) would work. I'm not sure if clang has an option to use a different keyword but I'll check (and I agree __block is too generic anyway).

As for gcc warning, please try with adding some options to the Makefile to silence the error - maybe:

```-Wno-unknown-warning```

or somesuch?

**Comment by robertswiecki** [comment]
I've added -Wno-unknown-warning in https://github.com/google/honggfuzz/commit/60b9f5686a152a434448898de7c547c5debbed54. Hope this helps

**Comment by KnoooW** [comment]
How can I get BlocksRuntime library, I've tried to compile llvm compiler-rt., but no libBlocksRuntime produced...

**Comment by robertswiecki** [comment]
gcc would be the best options for older distros as the support for clang's blocks might not be that good in them. I think the clang support is mostly for Android these days, though it'd be good to make it compilable under Linux/FreeBSD.

In any case, here seems to be a standalone repo - https://github.com/mackyle/blocksruntime

**Comment by robertswiecki** [comment]
As for PTRACE_O_EXITKILL, you might try to define it out if not present, though missing things in headers don't always mean that it's missing from the kernel. PTRACE_O_EXITKILL is there from at least kernel 3.8 or so.

```
#if !defined(PTRACE_O_EXITKILL)
 #define PTRACE_O_EXITKILL 0
#endif  /* !defined(PTRACE_O_EXITKILL) */
```

**Comment by KnoooW** [comment]
OK, successfully compile it in gcc centos7 now.

**Comment by robertswiecki** [comment]
BTW, what's the kernel version in centos7?

**Comment by robertswiecki** [comment]
In any case, I defined PTRACE_O_EXITKILL explicitly in https://github.com/google/honggfuzz/commit/54adb764906a304c9a3a2e3f435fb54f754a3a7d - afaik centos7 runs on kernel 3.10 which should support that

**Comment by KnoooW** [comment]
it did support that definition, but the original source code didn't include the header file <linux/ptrace.h>
, I included it in ptrace_util.c, it solved that error.
