### ISSUE TITLE
Remove SanCov support from honggfuzz

### ISSUE THREAD

**Issue by robertswiecki** [google/honggfuzz#168]
Given that trace-pc/trace-pc-guard seems to works with Android well now, is there any point in having the sancov logic inside honggfuzz?

It's a great piece of code, though by removing it we could clean-up some structures and asan/msan/ubsan handling a bit.

If there're still users of sancov (dumping coverage files, instead of in-process coverage callbacks), it's sure fine to leave it as is.

CC @anestisb @zachriggle

**Comment by anestisb** [comment]
The latest AOSP master [supports](https://android.googlesource.com/platform/build/+/master/core/config_sanitizers.mk) in-process fuzzing in build core, although the currently supported production releases (Nougat & Oreo) do [not](https://android.googlesource.com/platform/build/+/android-8.0.0_r34/core/config_sanitizers.mk).

Personally I'm still fuzzing with sancov in Nougat & Oreo and would be great if you can maintain it until in-process fuzzing support is added in stable release versions (probably the next one).

**Comment by robertswiecki** [comment]
Ah.. ok :) Thanks for the feedback.
