### ISSUE TITLE
Unable to compile on OS X

### ISSUE THREAD

**Issue by r3dsm0k3** [google/honggfuzz#169]
```
mac/arch.c:750:6: error: conflicting types for 'arch_archThreadInit'
bool arch_archThreadInit(honggfuzz_t* hfuzz UNUSED, run_t* run UNUSED) ...
     ^
./arch.h:33:13: note: previous declaration is here
extern bool arch_archThreadInit(run_t* run);
            ^
1 error generated.
make: *** [mac/arch.o] Error 1
```
Shouldn't it be `arch_archThreadInit(run_t* run UNUSED)` in  mac/arch.c ?

**Comment by robertswiecki** [comment]
Hm.. I don't have MacOSX handy, but please try with the master branch. Possibly it'll work after https://github.com/google/honggfuzz/commit/89c18748224cde2c09f235303664abb488c67b28

**Comment by r3dsm0k3** [comment]
I can confirm that the compiling work as I have changed it locally and compiled before I filed the issue. Thank you for providing a fix.
