### ISSUE TITLE
Problems with hardware feedback

### ISSUE THREAD

**Issue by tampe125** [google/honggfuzz#170]
I'm trying to fuzzing a blackbox executable, but I'm having problems using any hardware based feedback.  
I can only use the flags `--linux_perf_instr` and `--linux_perf_branch`; if I try to use any other flag (`--linux_perf_ipt_block` or `--linux_perf_bts_edge`) I get the following error:

    arch_perfCreate():179 perf_event_open() failed: Device or resource busy

This is the command I'm currently using (I'm fuzzing a local webserver):

```
sudo ./honggfuzz \
--linux_perf_ipt_block \
-W /home/tampe125/honggfuzz \
--covdir /home/tampe125/honggfuzz \
-f examples/apache-httpd/corpus_http1 \
-w examples/apache-httpd/httpd.wordlist \
-s \
-p 4678 -- \
/bin/nc -q2 -w2 127.0.0.1 1234
```
System details:
```
Linux 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
CPU: Intel i5-7400
```
Anyone else has this issue or I'm missing any system configuration?

**Comment by robertswiecki** [comment]
Hi,

a few ideas

a). check whether you have any honggfuzz still running - there might be some zombie processes, which can lock BTS/PT - try to kill them

b). check the setting of kernel.perf_event_paranoid - mine is 1 - with 2 it will probably won't work

**Comment by robertswiecki** [comment]
Also, please remember to run your apache's httpd with -X. Otherwise it'll run as multiple processes/threads, and PT/BTS will get coverage for one thread only.

**Comment by robertswiecki** [comment]
Please try with https://github.com/google/honggfuzz/commit/7e37f17aceb067f317e5c96e03d6b9206ab4367d

The PID attaching piece is a bit "messy", but this should help.

Also, as above, you'd probably need the following set of flags for httpd

```./dist/bin/httpd -X -DFOREGROUND=1 -DNO_FORK=1 -f /home/jagger/fuzz/apache/dist/conf/httpd.conf.h2```

Plus, you'd need for it to use the mpm_prefork module, otherwise it'll create a lot of threads, and PT/BTS will attach to only one of them.

**Comment by robertswiecki** [comment]
I think it's fixed, please re-open if the problem still persists

**Comment by tampe125** [comment]
Thank you very much for your info! I'll try them ASAP!
