### ISSUE TITLE
fuzzer run question.

### ISSUE THREAD

**Issue by wmmw123** [google/honggfuzz#173]
Hello,

I have a question.

Is there a way to know if the fuzzer is working properly?

I passed the wrong parameter to the program, but the fuzzer was executed.

I think the fuzzer only checks its own parameters.

Thanks.

**Comment by robertswiecki** [comment]
Hi,

Can you provide an example?

E.g. for me

```
$ ./honggfuzz --linux_perf_ipt_block_INCORRECT -f /tmp/IN/ -- /bin/ls
./honggfuzz: unrecognized option '--linux_perf_ipt_block_INCORRECT'
Usage: ./honggfuzz [options] -- path_to_command [args]
Options:
 --help|-h 
	Help plz..
 --input|-f VALUE
...
```

**Comment by wmmw123** [comment]
@robertswiecki 

Hello,

There is an example.

The Mutool Program does not have the - D option.

An error will occur if you run the command with the -D option.

But, It is executed in honggfuzz.

./mutool info -D test.pdf    <--- Error

honggfuzz -f in/ -W out/  -- ./mutool info -D  ___FILE___  <---- Run.

![error](https://user-images.githubusercontent.com/30585587/33931075-4bd8b912-e032-11e7-892c-89ed7f75c0ae.PNG)
![run](https://user-images.githubusercontent.com/30585587/33931076-4c05510c-e032-11e7-892b-4c0a4ae159ef.PNG)

Thanks.

**Comment by robertswiecki** [comment]
Ah...

Yeah, it's a good idea to run a few first honggfuzz iterations with the

```shell
-Q
```

option, to see the stdout/stderr of the program. Checking for the exit code and somehow alerting the user doesn't probably make sense, as with most invalid inputs honggfuzz produces, the exit code will be !=0

What I can do is to fix the example from --help. Maybe so it uses djpeg instead of libtiff. This way people won't simply re-use the command-line. WDYT?

**Comment by robertswiecki** [comment]
Ok, with https://github.com/google/honggfuzz/commit/216a4363eca17e2bfb56b5af3cd166dd9c0b47a1 usage examples use djpeg, so there's no confusion about special meaning of the ```-D``` flag for fuzzed programs.

But, as above, it's good to run honggfuzz with the ```-Q``` (i.e. don't close stdout/stderr) option first.

**Comment by wmmw123** [comment]
@robertswiecki 

Good!.

I used the -Q option and can check the run via the output.

Thanks.

**Comment by wmmw123** [comment]
@robertswiecki 

Hello.

There are additional questions.

I used the -W option to specify the crashes folder.

However, the runtime files are also stored.

Is there a way to store only unique crash files?

I am using sync to upload a unique crash file. 

However, runtime files cause errors.

I can solve the problem using a shell script, but it would be nice if this feature was supported by Fuzzer.

Thanks.

**Comment by robertswiecki** [comment]
Please try after this change

https://github.com/google/honggfuzz/commit/ced3ebaa5a4a96185dc92a40c98f6dbb8728743b

Now it's the ```--crashdir``` option
