### ISSUE TITLE
Regarding intel PT based tracing

### ISSUE THREAD

**Issue by tosanjay** [google/honggfuzz#177]
Hi,
** This is not an issue, but rather a query about Hongfuzz+PT mode. **
 
In the description, it is written that though Intel PT is way faster than BTS based tracing (which is clear), it is less precise. Can you provide some more info on this- why is it less precise?

I also looked at the pt.c file, I noticed that it seems you only check if the PT packet is TIP and if so, get the target IP, which is further used in BB maps. Is it correct?

I could not see any mention of TNT packets, which means hongfuzz + PT is agnostic to branches. Is this 
the reason it is "less precise"?

It also appears that here we do not try to rebuild the instruction trace and then compute the edge tuple <to-from> (as in the case of BTS). Is it true and if so, is it because of performance?

Thanks

**Comment by robertswiecki** [comment]
In short, yeah, it's because analysis with binary used to be sloooooooow :).

libipt has a mode (IIRC) in which it's possible to rebuild the flow with binary, so if you'd like to play with that, and if the speed is good, we could enable it in honggfuzz as well.

**Comment by tosanjay** [comment]
Thank you @robertswiecki for the response. So, it means (for my own understanding),in its present implementation, hongfuzz only records indirect jumps/calls without using the main binary for flow reconstruction.
Thank you for the clarification.
