### ISSUE TITLE
Intel BTS mmap error

### ISSUE THREAD

**Issue by acidghost** [google/honggfuzz#178]
Hi,
while running the fuzzer with BTS feedback enabled I get the following error:
```
arch_perfCreate():213 mmap(mmapAuxBuf) failed, try increasing the kernel.perf_event_mlock_kb sysctl (up to even 300000000): Cannot allocate memory
```
I obviously tried increasing the `perf_event_mlock_kb` to the suggested value. The error happens quite sparsely (I've been able to run the fuzzer even for 24 hours but the error can pop up after 1, 2, 5 or 8 hours in) and I cannot reproduce it at will.

Another detail is that if I run the fuzzer as a normal user after a previous run failed due to mmap error, I get another mmap error but this time on `mmapBuf: Operation not permitted`. If I retry as root, it runs fine until the next `mmapAuxBuf: Cannot allocate memory` error. To make it run as normal user again I have to reboot my machine.

OS details:
```
$ uname -a
Linux acidghost-MS-7816 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
``` 

Thanks for your help.

**Comment by robertswiecki** [comment]
Hi,

In short, Intel BTS/PT implementation was quite unstable in kernels around version ~4.4 (early implementation of the AUXTRACE feature). There were some problems with mutexes being left locked in the kernel.

I'm using personally 4.13 to test it, but IIRC it works kind-a stable since ~4.9

**Comment by acidghost** [comment]
Thanks for the info. I'm trying with 4.13 as suggested and I'll report here.

One more thing: would you suggest running as root or not? Does it affect the kernel implementation of BTS?

**Comment by robertswiecki** [comment]
It does, but also in its ability to track kernel addresses. With root you can trace kernel, which might be helpful for more advanced setups.

In any case, you can control access to kernel-level addresses with

$ sysctl kernel.perf_event_paranoid
kernel.perf_event_paranoid = 1

If it's set to 3, then you can get EPERM errors when accessing BTS/PT

**Comment by robertswiecki** [comment]
Please re-open if you bump into new problems with BTS
