### ISSUE TITLE
Darwin sigaction struct has no .sa_restorer member

### ISSUE THREAD

**Issue by anestisb** [google/honggfuzz#18]
Darwin sigaction struct has no ".sa_restorer" member. Bug was introduced at commit:https://github.com/google/honggfuzz/commit/0764ad7ba27a025b5761ec77c81d2e38c67b30d6

Member initialization can be wrapped with "_HF_ARCH_LINUX" ifdef or removed completely since it doesn't seem to affect timer logic.

Also just to let you know that display.c has a few errors under MAC due to gnu-zero-variadic-macro-arguments (dprintf macro) and integer format (different return values for __sync_add_and_fetch()).

New display timer is also not working in Android (no idea why). Will start investigating as soon feature reaches a stable state.

Cool stuff, cheers!

**Comment by robertswiecki** [comment]
Thanks for the report - I fixed sa_restorer with https://github.com/google/honggfuzz/commit/853593b9dfbc64516032fac4f93346ee800380ca

Thanks for reporting on the display - it's truly in an early state. I'll work on that - I know that dprintf is sparesely supported across OSs, so I'll probably create a wrapper for that.

**Comment by anestisb** [comment]
Have been using the display the past few days both under Android & OSX with no further issues. I think issue can be closed.
