### ISSUE TITLE
Coverage Module White / Blacklist

### ISSUE THREAD

**Issue by zachriggle** [google/honggfuzz#181]
For fuzzing on Android with the entire system image compiled with coverage, we end up counting coverage for blocks not in the library under test.

We should be able to whitelist / blacklist coverage data based on the module in which it's contained.

For example, running the MPEG4Extractor parser with trace-pc-guard registers coverage data for 66 modules with 320K different guards.

**Comment by robertswiecki** [comment]
Hm.. I'm not sure it's possible to figure out which guard belongs to which module without some bigger hackery inside clang's -fsanitize-coverage internals.

You probably would like to mark those guards as already taken? It's technically possible by modifying the initial feedback_t memory map, but not sure how to obtain data on which guards should be marked as 'hit' initially. We technically have access to the binary, but I'm not sure we have any tools which could help us here (analyzing the binary, figuring out mapping of guards to modules). I wonder what kcc@ will say about that.

**Comment by robertswiecki** [comment]
BTW, I've made some small change a couple of days ago

https://github.com/google/honggfuzz/commit/599dee1c204ab59e16e29a783601ffabf0aa7cd9#diff-892bfb083f61839bac3d2b6c1f111541R43

It's basically clearing the state of "new counters" which were hit before the first LLVMFuzzerTestOne input was called. This small change makes it possible to not attribute initialization functions to the first tested testcase.
