### ISSUE TITLE
how to prepare the input for the initial run

### ISSUE THREAD

**Issue by huangshiyou** [google/honggfuzz#185]
Hi, this is not an issue but a usage problem. I created a simple example which expects the input from stdin. But I don't know how to prepare the input file for the testing because the document about this part is not very clear. I tried to follow the examples shown in the examples folder. The testing goes forever and it seems no coverage is reported. 

The cmd I used:
honggfuzz -f input --linux_perf_ipt_block -x -s -- ./multithread __FILE__

I need some help on how to prepare the form of the initial input. Thanks.

**Comment by robertswiecki** [comment]
So, Intel PT doesn't support multi-threaded processes now. It sorta-a does, but it'll gather coverage for the main thread only.

But, assuming you wanted to start with e.g. djpeg (w/o source code) for JPEG decoding, you can do the following.

```honggfuzz -f EMPTY --linux_perf_ipt_block -- /usr/bin/djpeg ___FILE___```

or

```honggfuzz -f EMPTY --linux_perf_bts_edge -- /usr/bin/djpeg ___FILE___```

**Comment by huangshiyou** [comment]
Hi, thanks for your reply. 
> So, Intel PT doesn't support multi-threaded processes now. It sorta-a does, but it'll gather coverage for the main thread only.

I guess you mean that Intel PT does not support context switch? I think the trace actually can be decoded if using some extra information, like the context switch events by perf and the timestamp information.

**Comment by huangshiyou** [comment]
Another issue I am confusing is that Intel PT is core based recording, so how does the fuzzer only track the main thread?

**Comment by robertswiecki** [comment]
It's using standard perf_event_open() interface of the Linux kernel which is per-thread now for PT/BTS. Of course gathering feedback for all threads involved is possible, just the code would be non-trivial (attaching to new threads upon creation, possibly in the ptrace() path. Not sure if worth the effort, but if somebody would like to take a stab at it, I guess I'll hapilly merge such PR.

**Comment by robertswiecki** [comment]
Please re-open if you have any more questions about PT
