### ISSUE TITLE
Question regarding coverage-data generation

### ISSUE THREAD

**Issue by cndycc** [google/honggfuzz#190]
Hello,
I am fuzzing a network service. I have around 30 test-cases and after startup, honggfuzz keeps generating .cov data. This process keeps on generating data (see screenshot). I am not sure if I correctly understand honggfuzz: Is the coverage data already used for fuzzing different code paths or does the fuzzing process start after generationg coverage information?

*edit: Something else seemed to fill my disk. The coverage data did not cause it. My original question still stands: When does the fuzzing process start?

<img width="706" alt="screen shot 2018-02-20 at 12 36 01" src="https://user-images.githubusercontent.com/888329/36422173-5101aa0e-163b-11e8-9836-197ff82b71e0.png">

**Comment by robertswiecki** [comment]
It seems that you're hitting valid new coverage paths (the fourth param of log info), so it seems it works. How many output files do you have in your coverage directory? What's the maximum file size for samples you have (max size)? Is it small (like <64k), or big (e.g. >1MB)?

Also, is your fuzzed software simple - as in is it a simple library, or some bigger piece of code, which can, for example, run another binary - or load external .so modules. In such case the ASLR disabling might not work always. Also, we disable ASLR with Linux (via personality()), which OS do you use? Maybe we should try to disable ASLR for your OS as well somehow.

**Comment by robertswiecki** [comment]
Hm... your edge counter is at 903, and cmp-goodness-factor at 10268, so you have at maximum ~11k samples in your coverage directory, which would amount to 1GB of coverage data at 64k per sample maximum (```-F```). Maybe try to set ```-F``` to some reasonably small value (8k, 32k or 64k or so). You can also try to trim your input samples to some small value (e.g. with ```dd``` tool). If the biggest sample in your input dir is >8192 the maximum size (```-F```) will amount to that, unless you lower it manually with ```-F```

**Comment by cndycc** [comment]
At the moment I have 49 files which were my original test-cases and 301 .cov files in my input folder. The test-case sizes are rather small (from 20b up to 120b). I am fuzzing a really simple web-server which is loading:
`	linux-gate.so.1 =>  (0xb7709000)
	libcrypt.so.1 => /lib/i386-linux-gnu/libcrypt.so.1 (0xb76cd000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb76b0000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xb76a7000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb7652000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb764d000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb762f000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb7479000)
	/lib/ld-linux.so.2 (0x8007f000)
`
on Ubuntu 16.04.3 LTS (32-bit).

ASLR is turned on, my bad, thought it was turned of. I will disable it and restart the fuzzer. Will the coverage data have to be regenerated or can I keep it? Thanks for your hints!

**Comment by robertswiecki** [comment]
The coverage data will be appended, if they already don't exist. I.e. if you have some input files, the dry run will test them, and assume the coverage from those input files is useful.

If you'd like to create minimal coverage you can use ```--covdir_all```

```honggfuzz -f input_dir_with_inputs_and_current_coverage [other_options] --covdir_all new_minimal_coverage_dir -- [program_to_test]```

**Comment by cndycc** [comment]
Thanks! I will keep on fuzzing and report back!
