### ISSUE TITLE
Fuzzing tcpdump with BTS coverage

### ISSUE THREAD

**Issue by acidghost** [google/honggfuzz#194]
Hi,
I'm trying to fuzz tcpdump (4.9.0) with libpcap statically linked:
```
$ ldd ../../tcpdump-4.9.0/tcpdump                                  
	linux-vdso.so.1 =>  (0x00007ffff7ffa000)
	libcap-ng.so.0 => /usr/lib/x86_64-linux-gnu/libcap-ng.so.0 (0x00007ffff7bd2000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007ffff778e000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ffff73c4000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ffff7dd7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ffff71c0000)
```
When using `--linux_perf_bts_edge` no new files (increasing coverage) are found within 10mins. When instead I use `--linux_perf_branch` all goes fine and new files are saved. On other binaries BTS works just fine; ASLR is disabled.

What am I doing wrong? Suggestions on how to debug it?

**Comment by robertswiecki** [comment]
BTS/IntelPT code changed a lot since Feb 2018, please re-open if yo ustill have this problem
