### ISSUE TITLE
Running with --linux_perf_ipt_block

### ISSUE THREAD

**Issue by stevenagy** [google/honggfuzz#206]
Hello,

I'm wanting to run HonggFuzz with Intel PT block tracing. My syntax is as follows:
`honggfuzz -f hf_in --linux_perf_ipt_block -- djpeg ___FILE___`

However, I get the following error:
`[2018-06-04T16:27:51-0400][F][50409] arch_ptAnalyze():94 pt_errata() failed: unknown cpu`

Any suggestions would be greatly appreciated. I know my processor is Intel PT compatible - I'm also working on some perf_event_open stuff that I may have some questions on later, if you don't mind :).

Best wishes,
-Steve

**Comment by robertswiecki** [comment]
Maybe you can comment out code in pt_errata() which returns the error (i.e. downloading libipt and compiling it)? I guess the format of PT didn't change much recently.

**Comment by robertswiecki** [comment]
Here's what supported, check your /proc/cpuinfo to find out the model/stepping

```
	switch (cpu->family) {
	case 0x6:
		switch (cpu->model) {
		case 0x3d:
		case 0x47:
		case 0x4f:
		case 0x56:
			errata->bdm70 = 1;
			errata->bdm64 = 1;
			return 0;

		case 0x4e:
		case 0x5e:
			errata->bdm70 = 1;
			errata->skd007 = 1;
			errata->skd022 = 1;
			errata->skd010 = 1;
			errata->skl014 = 1;
			return 0;

		case 0x8e:
		case 0x9e:
			errata->bdm70 = 1;
			errata->skl014 = 1;
			errata->skd022 = 1;
			errata->skd010 = 1;
			errata->skd007 = 1;
			return 0;

		case 0x5c:
		case 0x5f:
			errata->apl12 = 1;
			errata->apl11 = 1;
			return 0;
		}
		break;
	}

	return -pte_bad_cpu;
}
```

**Comment by stevenagy** [comment]
```
cpu family	: 6
model		: 85
stepping		: 4
```
So it doesn't seem like my CPU is supported, despite IPT clearly working for me through both perf record and perf_event_open(). I have **libipt.so** in /usr/local/bin. Should I just comment out that code then?

**Comment by robertswiecki** [comment]
Think so... though maybe you should add 85 (0x55) along with the 0x5e which is Skylake (client), yours is Skylake (server), so probably that's a safe bet. Seems like libipt sets some flags (bugs workarounds) for certain types of cores.

**Comment by robertswiecki** [comment]
You can also create issue at https://github.com/01org/processor-trace - Intel engs might know better

**Comment by stevenagy** [comment]
Which file should I edit to ad 0x55 in?

**Comment by robertswiecki** [comment]
Here: https://github.com/01org/processor-trace/blob/master/libipt/src/pt_config.c#L61

**Comment by robertswiecki** [comment]
Hi @markus-metzger - I saw you commenting in https://github.com/01org/processor-trace/issues?utf8=%E2%9C%93&q=is%3Aissue - @stevenagy has a problem with running PT code with Skylake (server) as libipt doesn't seem to support it? Would it be ok to add 0x55 (Skylake - server) along 0x53 (Skylake - client) here https://github.com/01org/processor-trace/blob/master/libipt/src/pt_config.c#L61 ?

**Comment by stevenagy** [comment]
Thank you for the help, and poking Markus :).

I noticed HonggFuzz uses the perf_event_open() approach to collecting traces. I ran some experiments using my own AFL-style forkserver based IPT tracer (minus decoding... I'm only interested in comparing tracing performance) and got similar results to what you reported here: https://groups.google.com/d/msg/afl-users/iwuRLAjTzaU/YtN_JwEQGAAJ 

My question is - what kind of performance impact is HonggFuzz getting _with_ trace decoding enabled?

**Comment by robertswiecki** [comment]
I didn't perform any testing recently. From vague memories, I think it's somewhat close to 50%

**Comment by stevenagy** [comment]
Thank you both!

**Comment by v-p-b** [comment]
I ran into the same problem recently and found that honggfuzz passes a 0/0/0 `cpu` structure to the errata function. The input struct is expected to be populated by `pt_config_init()` but as you can see here the `cpu` substruct should be manually populated: 

https://github.com/01org/processor-trace/blob/master/doc/man/pt_config.3.md#example

I guess this may be the result of a recent change in libipt. I haven't figured out yet how to get a populated `pt_cpu` struct from libipt, so a workaround can be just to populate the `cpu` substruct like this:

```
ptc.cpu.vendor=pcv_intel;
ptc.cpu.family=6;
ptc.cpu.model=94;
ptc.cpu.stepping=3;
```

**Comment by robertswiecki** [comment]
Yup, there's some difference between libipt1 and libipt2 about that.

The simplest way would be to parse /proc/cpuinfo - I guess?

**Comment by robertswiecki** [comment]
Please try at HEAD with https://github.com/google/honggfuzz/commit/833b0f5144c03c402bdac93e9974544be1f90530

**Comment by v-p-b** [comment]
The latest master (a5fc628ad3a4f6a078a06845fb1c67af1175b1bf) works for me, thanks!

**Comment by markus-metzger** [comment]
The difference in libipt is that it used to silently ignore unknown cpus.  Recent versions return an error.

Users are expected to fill in the cpu family/model/stepping on which the trace was collected.  This is often not the machine on which the trace is decoded.
