### ISSUE TITLE
Unable to link on U18.04 LTS

### ISSUE THREAD

**Issue by fwsGonzo** [google/honggfuzz#207]
libblocksruntime-dev does not exist

**Comment by robertswiecki** [comment]
I think it's this one?

https://packages.ubuntu.com/bionic/libblocksruntime-dev

**Comment by robertswiecki** [comment]
Also, you can simply compile with gcc

**Comment by fwsGonzo** [comment]
Something must have happened with my APT lists, as it popped up today after updating. And yes, I was meaning to try with GCC as well, but now I dont have to :)
