### ISSUE TITLE
Compile error: no member named 'aux_tail' in 'struct perf_event_mmap_page'

### ISSUE THREAD

**Issue by JsHuang** [google/honggfuzz#209]
While complie honggfuzz in ubuntu 14.04 , I got the following error:
```
inux/pt.c:84:41: error: no member named 'aux_tail' in 'struct perf_event_mmap_page'
    uint64_t aux_tail = ATOMIC_GET(pem->aux_tail);
                                   ~~~  ^
./libhfcommon/util.h:43:41: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x) __atomic_load_n(&(x), __ATOMIC_SEQ_CST)
                                        ^
linux/pt.c:85:41: error: no member named 'aux_head' in 'struct perf_event_mmap_page'
    uint64_t aux_head = ATOMIC_GET(pem->aux_head);
                                   ~~~  ^
./libhfcommon/util.h:43:41: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x) __atomic_load_n(&(x), __ATOMIC_SEQ_CST)

```
system info:
```
Linux ubuntu 4.4.0-31-generic
```
perf version:
`perf version 4.4.13`

**Comment by robertswiecki** [comment]
What's your linux-headers?

$ dpkg -l  | grep linux-header
ii  linux-headers-4.9.0-6-amd64                       4.9.82-1+deb9u3                           amd64        Header files for Linux 4.9.0-6-amd64
ii  linux-headers-4.9.0-6-common                      4.9.82-1+deb9u3                           all          Common header files for Linux 4.9.0-6
ii  linux-headers-amd64                               4.9+80+deb9u4                             amd64        Header files for Linux amd64 configuration (meta-package)

I think AUXTRACE appeared around 4.4, so it should be OKeyeesh.

Generally, please take a look at your ```/usr/include/linux/perf_event.h```

it should have

```PERF_ATTR_SIZE_VER5```

and ```struct perf_event_mmap_page {```

should contain

```
        /*
         * AUX area is defined by aux_{offset,size} fields that should be set
         * by the userspace, so that
         *
         *   aux_offset >= data_offset + data_size
         *
         * prior to mmap()ing it. Size of the mmap()ed area should be aux_size.
         *
         * Ring buffer pointers aux_{head,tail} have the same semantics as
         * data_{head,tail} and same ordering rules apply.
         */
        __u64   aux_head;
        __u64   aux_tail;
        __u64   aux_offset;
        __u64   aux_size;
```

**Comment by JsHuang** [comment]
Thanks, I upgrade the kernel and solved it . @robertswiecki
