### ISSUE TITLE
Better cmp instrumentation

### ISSUE THREAD

**Issue by ntrippar** [google/honggfuzz#211]
Hi Robert, I saw that the cmp instrumentation here is too simple and takes lot time to resolve some cases. libfuzzer "traces" and match the memory from the input buffer and resolve the cases faster. is in the plan of the project modify that part or improve? I could work on it.

**Comment by robertswiecki** [comment]
Sure, please go ahead! 

Though, from your description it seems that you'd like somehow to find matching data from the fuzzed that, which would be itself slower (maybe faster in grand scheme of things, but not per function call), so in case I'm correct, this should be an opt-in mode, at least till we convince ourselves that it's worthwile to enable it by default.

**Comment by robertswiecki** [comment]
Hi, please re-open if you still would like to work on this
