### ISSUE TITLE
Binary to read a specific file from the directory

### ISSUE THREAD

**Issue by neox123** [google/honggfuzz#226]
Hi

The binary that I want to test, reads the specific file name from the directory.

Therefore, cannot use the input using honggfuzz.

Can I use the honggfuzz without modifying the source code?

for example:
```
ls directory/
1.txt
cat 1.txt
Hello
./a.out -d directory/
Hello
```

**Comment by robertswiecki** [comment]
If you compile a binary using hfuzz-cc than it can use a single file from standard input
