### ISSUE TITLE
Seems like targeted process exit is not detected?

### ISSUE THREAD

**Issue by cmichi** [google/honggfuzz#229]
Ok, so pretty sure that I'm using the tool wrong, but I haven't yet figured out what my misunderstanding is. The following minimal example is with the latest master. 

In one shell session I start `sleep 10m`. In another I start
```
sudo ./honggfuzz -f ./corpus/ -s -p "`pidof sleep`" -- echo "foo"
```
The UI shows the target correctly: `Target : [13085] 'sleep 10m'`.

If I then `sudo pkill sleep` the fuzzing still continues ‒ even though the process is gone ‒ and there is no crash detected. Appending `--exit_upon_crash` when invoking `honggfuzz` also doesn't help.

Instead of `sleep 10m` I have an HTTP server running and instead of `echo "foo"` I have a `curl` which forwards the data to the server.

Am I wrong assuming that `SIGKILL`/`SIGTERM` should be counted as a "crash"?

**Comment by robertswiecki** [comment]
Given that the -p mode has been removed from honggfuzz (in favor of the honggfuzz net driver, and persistent modes), closing this.
