### ISSUE TITLE
intel pt bug in windows subsystem for linux on win10

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#232]
Windows Subsystem for Linux on Windows 10 and CPU Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz :

root@TENCENT-Q7G68UA:/mnt/d/honggfuzz# ptfeature
Supports PT
toPA output support:            1
multiple toPA entries:          1
single range:                   1
trace transport output:         0
payloads are LIP:               0
cycle accurate mode / psb freq: 1
filtering / stop / mtc:         1
CR3 match:                      1
Number of address ranges:       2
Supports filter ranges:         1
Supports stop ranges:           1
Valid cycles thresholds:        1 2 3 4 5 6 7 8 9 10 11 12 13 14
Valid PSB frequencies:          1 2 3 4 5 6
Valid MTC frequencies:          1 4 7 10
TSC ratio:                      2 300
Bus frequency:                  150.000000
Family:                         6
Model:                          158
Stepping:                       9

then run honggfuzz to fuzz convert, it can't get the coverage info:

------------------------[  0 days 00 hrs 00 mins 40 secs ]----------------------
  Iterations : 2,600 [2.60k]
        Mode : [2/2] Feedback Driven Mode
      Target : /usr/bin/convert ___FILE___ out.jpg
     Threads : 4, CPUs: 8, CPU%: 622% [77%/CPU]
       Speed : 66/sec [avg: 65]
     Crashes : 0 [unique: 0, blacklist: 0, verified: 0]
    Timeouts : 0 [10 sec]
 Corpus Size : 1, max: 682,144 bytes, init: 215 files
  Cov Update : 0 days 00 hrs 00 mins 36 secs ago
    Coverage : edge: 0 pc: 0 cmp: 0     <==== no coverage info
---------------------------------- [ LOGS ] ------------------/ honggfuzz 1.7 /-

is it a bug or not supported on Windows Subsystem for Linux  ?

**Comment by robertswiecki** [comment]
Cam you try at HEAD, seems like libipt2 requires some additional initialization. Not sure if it'll help WSL, but maybe.

https://github.com/google/honggfuzz/commit/833b0f5144c03c402bdac93e9974544be1f90530

**Comment by riusksk** [comment]
this issue remains.
Will it default to use pt if the system supports pt in ubuntu? for example:
`honggfuzz -f emf_input -e emf -- /usr/bin/convert ___FILE___ out.bmp`

**Comment by robertswiecki** [comment]
Can you try sth? Basically changing this mmap

https://github.com/google/honggfuzz/blob/master/linux/perf.c#L199

from PROT_READ to PROT_READ|PROT_WRITE

Otherwise.. dunno, WSL is a nice try to make a compatible system table, but I wonder how much compatibility is actually there, esp. in such niche substsem as perf.

**Comment by riusksk** [comment]
Perf doesn't seem to support WSL
```
WARNING: perf not found for kernel 4.4.0-43

  You may need to install the following packages for this specific kernel:
    linux-tools-4.4.0-43-Microsoft
    linux-cloud-tools-4.4.0-43-Microsoft

  You may also want to install one of the following packages to keep up to date:
    linux-tools-Microsoft
    linux-cloud-tools-Microsoft
```

```
# apt install linux-tools-4.4.0-43-Microsoft
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-tools-4.4.0-43-Microsoft
E: Couldn't find any package by glob 'linux-tools-4.4.0-43-Microsoft'
E: Couldn't find any package by regex 'linux-tools-4.4.0-43-Microsoft'

# apt install linux-cloud-tools-4.4.0-43-Microsoft
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-cloud-tools-4.4.0-43-Microsoft
E: Couldn't find any package by glob 'linux-cloud-tools-4.4.0-43-Microsoft'
E: Couldn't find any package by regex 'linux-cloud-tools-4.4.0-43-Microsoft'
````

**Comment by robertswiecki** [comment]
I will not be able to test it soon, so closing it for the time being.
