### ISSUE TITLE
Track coverage achieved in Honggfuzz after fuzzing

### ISSUE THREAD

**Issue by prashast** [google/honggfuzz#233]
Hi, I wanted to get some stats on the coverage after a fuzzing run was finished.
Similar to something how `afl-showmap`shows the number of tuples hit. 

~~In the display log, there seems to be support for HW-based counters which are displayed
but there seems to be no support for displaying coverage using the information in the struct
[here](https://github.com/google/honggfuzz/blob/master/honggfuzz.h#L168) which is updated on
hitting trace instrumentation in the target binary.~~

~~I have modified Honggfuzz to dump the `feedback_t` struct if a user specifies so and am in the process of writing a tool that can parse the dumped struct and then deliver results based on which instrumentations were activated in the binary.~~

~~Just wanted to double-check if there is existing functionality that I am unaware of that can be used to deliver interpretable stats to the user using the bitmap info? If not, I'll probably just go ahead with implementing this tool.~~ 

EDIT: After looking further at the `hwcnt_t` struct it seems like
```C
typedef struct {
    uint64_t cpuInstrCnt;
    uint64_t cpuBranchCnt;
    uint64_t bbCnt;
    uint64_t newBBCnt;
    uint64_t softCntPc;
    uint64_t softCntEdge;
    uint64_t softCntCmp;
} hwcnt_t;
```
The last three members i.e. ```softCntPc, softCntEdge and SoftCntCmpy``` are the ones responsible for keeping track of software-based instrumentation coverage and are exactly what I was looking for.
Could you let me know what measure is maintained by `softCntPc` exactly?

**Comment by prashast** [comment]
EDIT: After looking further at the `hwcnt_t` struct it seems like
```C
typedef struct {
    uint64_t cpuInstrCnt;
    uint64_t cpuBranchCnt;
    uint64_t bbCnt;
    uint64_t newBBCnt;
    uint64_t softCntPc;
    uint64_t softCntEdge;
    uint64_t softCntCmp;
} hwcnt_t;
```
The last three members i.e. softCntPc, softCntEdge and SoftCntCmpy are the ones responsible for keeping track of software-based instrumentation coverage and are exactly what I was looking for.
Let me know if I am correct.

**Comment by robertswiecki** [comment]
softCntPc are basic-blocks and not edges, e.g. some block counting techniques are doing just that, providing just address of a basic block instead of edges.
