### ISSUE TITLE
running apache example

### ISSUE THREAD

**Issue by moqingyan** [google/honggfuzz#234]
Hi,

I am trying to run the apache example by 
```shell
../../honggfuzz -f ./corpus_http1 -w ./httpd.wordlist -- ./dist/bin/httpd -DFOREGROUND -f  ./dist/conf/httpd.conf.h1
```
according to my path setting.

However, honggfuzz have no update on the Coverage row, which keeps displaying `Coverage: edge: 0 pc: 0 amp: 0`
In addition, the log shows a bunch of messages as:  

> Persistent mode: Launched new persistent PID: 69668
[2018-10-24T19:42:13-0400][W][61989] arch_reapChild():409 Persistent mode: PID 69667 exited with status: EXITED, exit code: 1

I am using Mac OS system,
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
Linux system is also checked and has the same behavior as well.

The version of tools I am using: 
- httpd: 2.4.37
- apr: 1.6.5
- apr-util: 1.6.1
- nghttp2: 1.34.0

**Comment by Chobbes** [comment]
I'm having the same problem on linux. I've documented the steps that I have taken here:

https://github.com/Quick700/Quick700/tree/master/honggfuzz

**Comment by robertswiecki** [comment]
Please try with the full path to the config file. If this doesn't work, try running honggfuzz with ```-Q```, it'll show you httpd's error.log

This doesn't work for me

```
$ ~/src/honggfuzz/honggfuzz -f IN/ -w ~/src/honggfuzz/examples/apache/httpd.wordlist -- ./httpd/httpd -X -f dist/conf/httpd.conf.h1
...
[2018-10-28T02:40:21+0100][W][28301] arch_checkWait():308 Persistent mode: PID 28340 exited with status: EXITED, exit code: 1
```

but this does

```
$ ~/src/honggfuzz/honggfuzz -f IN/ -w ~/src/honggfuzz/examples/apache/httpd.wordlist -- ./httpd/httpd -X -f /home/jagger/fuzz/apache/dist/conf/httpd.conf.h1
```

**Comment by robertswiecki** [comment]
As for the original issue, could you try with ```-X``` instead of ```-DFOREGROUND```? Also, please try running honggfuzz with ```-Q```, it's noise but maybe it'll help you to find the problem

**Comment by Chobbes** [comment]
Having the full path to the config file fixed the issue for me, thanks!
