### ISSUE TITLE
Fuzzing dynamically linked libraries

### ISSUE THREAD

**Issue by joonazan** [google/honggfuzz#236]
Usually people want to avoid getting coverage on dlls, as they contain code from other projects.

However, I want to fuzz a graphics driver. Is it possible to make honggfuzz record Intel PT or BTS information from dynamically linked parts of the executable as well?

**Comment by robertswiecki** [comment]
By default PT/BTS record everything.

With BTS you can lower the limit (to exclude .so) with 

```--linux_perf_ignore_above```

But again, by default everything is recorded (except kernel addresses).

**Comment by joonazan** [comment]
Interesting. I had honggfuzz input generate SVG, which would then be parsed by a dll. It only found a corpus of about 70 files and then didn't expand it for 6 hours.

My fuzzing speed is about 1500/s. Is that way too slow to be useful?

**Comment by robertswiecki** [comment]
1500/s should be ok. Intel PT is good f there's nothing else to use, but if possible, you should be using compile-time instrumentation which is much more powerful
