### ISSUE TITLE
Coverage not working with hfuzz-gcc and attach pid

### ISSUE THREAD

**Issue by freetom** [google/honggfuzz#242]
Hi,

I am trying to fuzz `svnserve` from `subversion` software of Apache Software Foundation.
I successfully compiled it in by tweaking the config with something like `./config CC=/path/hfuzz-gcc CXX=/path/hfuzz-g++`
Then after a successful `make`, running `readelf -a /path/subversion/subversion/svnserve/svnserve | grep "cov_"` on the target executable gives:
```
  2701: 000000000019a310   103 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_cmp
  2741: 000000000019a5d0     1 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_cmp
  2745: 000000000019a5e0     1 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_cmp
  2772: 000000000019a310   103 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_con
  3070: 000000000019a4c0   139 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_swi
  3558: 000000000019a550   113 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_cmp
  3617: 000000000019a5f0    95 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_div
  3694: 000000000019a9b0    76 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_pc_
  3775: 000000000019a450   103 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_cmp
  3797: 000000000019a3f0    95 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_cmp
  3853: 000000000019a650    95 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_div
  4006: 000000000019a380   103 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_cmp
  4049: 000000000019a450   103 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_con
  4090: 000000000019a380   103 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_con
  4097: 000000000019a3f0    95 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_con
  4404: 000000000019a730   123 FUNC    WEAK   DEFAULT   14 __sanitizer_cov_indir_cal
  4436: 000000000019a2a0   107 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_pc
  5126: 000000000019a6b0   123 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_pc_
  5160: 000000000019a7b0   501 FUNC    GLOBAL DEFAULT   14 __sanitizer_cov_trace_pc_
```

So the coverage tracking routines seems to be in place.
But, when I run the fuzzer following [this instrucitons](https://github.com/google/honggfuzz/blob/master/docs/AttachingToPid.md) - I get zero coverage on all.

By looking at the log I see connections to the server so the fuzzer is connecting and is collecting timeouts, but no coverage. I run `honggfuzz` without `-c` but with `-f` specifying a folder with corpus to run.

Note: `svnserve` is run in `-d` (daemon mode)

Any idea of what's wrong?

**Comment by robertswiecki** [comment]
You probably attach to one of the threads. With ```-p``` honggfuzz attaches to a thread-id provided, and sometimes a process has multiple threads. 

Please check with

```ls -l /proc/<pid>/task```

for a list of threads, and try ```-p``` with those.

But, all in all, if you use TCP fuzzing, I'd suggest using this http://blog.swiecki.net/2018/01/fuzzing-tcp-servers.html

**Comment by freetom** [comment]
Thanks for the hint. But how do I attach the fuzzer to a thread spawned by the daemon dynamically? Maybe I should just try to fuzz directly the stubs that take SVN commands.. but how?

By running it with `-X` (listen once) and `-i` (inetd mode) I get a lot of `SEGV` that are basically null pointer dereferences that are false positives and hinder the fuzzing process (when delivering the same payloads to the daemon I don't get any crash).

So, I am kind of forced to fuzz the daemon.. 

Nice blog page btw, thanks!

**Comment by robertswiecki** [comment]
I'm insire how the daemon works, but if it exposes a TCP port, I'd suggest using the netdriver.

**Comment by freetom** [comment]
Thanks.

Any idea on how I could force honggfuzz to terminate the unused daemon processes? Where to hook in the code?

**Comment by robertswiecki** [comment]
Given that the attach PID mode has been removed from honggfuzz, closing this one.
