### ISSUE TITLE
Non-x86 platforms fail on latest version version

### ISSUE THREAD

**Issue by TheBlueMatt** [google/honggfuzz#243]
-march is an x86-specific argument so building projects with honggfuzz now fail with "error: unrecognized command line option -march=native; did you mean -mcpu=native"

**Comment by robertswiecki** [comment]
Thanks for the report.

Swapped -march for -mtune in https://github.com/google/honggfuzz/commit/feb21152a6ce30913e536be383703dfb7de0d5dc

gcc complains about -mcpu.

```cc: warning: ‘-mcpu=’ is deprecated; use ‘-mtune=’ or ‘-march=’ instead```

**Comment by TheBlueMatt** [comment]
mtune has a different meaning - it won't actually use native features, it will only do instruction costing based on the native costing (AFAIU)

**Comment by robertswiecki** [comment]
Hm.. given that gcc complains about mcpu and march is x86-only, is there a better way of doing that except -mtune?

I can maybe disable the option, but given that there are CPU-intensive procedures in there, using newer instructions can help greately. E.g. I'm already forcing SSE2 with hamming distanca computing bits, to make use of SSE2's popcnt under x86: https://github.com/google/honggfuzz/blob/master/libhfuzz/instrument.c#L24

**Comment by TheBlueMatt** [comment]
I'm not aware of anything without doing platform-dependant checks I'm not aware of a way, no. Luckily SSE2 is assumed on x86-64 (is anyone still using i686?).
