### ISSUE TITLE
--linux_perf_ipt_block: pt_pkt_sync_forward() failed: reached end of trace stream

### ISSUE THREAD

**Issue by pdknsk** [google/honggfuzz#246]
I get this warning every few thousand iterations.
```
[W][26922] arch_ptAnalyze():163 pt_pkt_sync_forward() failed: reached end of trace stream
```

**Comment by robertswiecki** [comment]
Yup, this happens sometimes, some strange interaction with the kernel, where only some PT packets are written into the buffer.

Nothing can be easily done about it, and at some point we shoudl rewrite the Intel PT support to support the binary input (full-decode).
