### ISSUE TITLE
how to monitor cross process crash ？

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#247]
I want to fuzz xpc server in macos, but I have to modify code to detect the existence of the xpc server process for the different xpc service each time.

for example,
`honggfuzz -f msg -t3 -n3 -- ./sender ___FILE___`

the above cmd monitor `sender` process crash by default , but what I need to monitor is xpc_server process which receiver message from sender.

Does honggfuzz have this ability to monitor across processes crash？

**Comment by robertswiecki** [comment]
If your sender TCP based (as in, is sender sending just some TCP stream)? Maybe you can use th HonggFuzz NetDrvier instead?

**Comment by riusksk** [comment]
it's not tcp stream, it's ipc message in macOS.

**Comment by robertswiecki** [comment]
So, I guess the answer would be that there's no such functionality :(

**Comment by phretor** [comment]
@robertswiecki I don't mean to reopen this, but I've been wondering about the same thing. Is it possible to use HonggFuzz merely as a process/crash monitor? Some targets—at least in my case—are very, very custom.

**Comment by robertswiecki** [comment]
There used to be -p <pid> option in older versions of honggfuzz. It should be a OK for crash monitoring. Maybe this?
