### ISSUE TITLE
inconsistence between docs and code: max_file_size

### ISSUE THREAD

**Issue by zjuchenyuan** [google/honggfuzz#251]
From [docs/USAGE.md](https://github.com/google/honggfuzz/blob/251ee7cf631b31ef92b2426f84e6a44da1748fc8/docs/USAGE.md): Which told me the default max file size is 1MB

```
 --max_file_size|-F VALUE
	Maximal size of files processed by the fuzzer in bytes (default: '1048576')
```

This command line argument is processed in [cmdline.c](https://github.com/google/honggfuzz/blob/251ee7cf631b31ef92b2426f84e6a44da1748fc8/cmdline.c), which set `hfuzz->mutate.maxFileSz` default to 0

```
            case 'F':
                hfuzz->mutate.maxFileSz = strtoul(optarg, NULL, 0);
                break;
```

Then, in [input.c](https://github.com/google/honggfuzz/blob/251ee7cf631b31ef92b2426f84e6a44da1748fc8/input.c), 0 changed to 8192, which means **8KB**

```
    if (hfuzz->mutate.maxFileSz == 0U) {
        if (maxSize < 8192) {
            hfuzz->mutate.maxFileSz = 8192;
        } else if (maxSize > _HF_INPUT_MAX_SIZE) {
            hfuzz->mutate.maxFileSz = _HF_INPUT_MAX_SIZE;
        } else {
            hfuzz->mutate.maxFileSz = maxSize;
        }
    }
```

So, it this an inconsistence between docs and code? What will happen if I feed seed files more than 8KB to honggfuzz?

Besides, by searching 1048576, the only occurences are in the docs, and no code used this value.

**Comment by robertswiecki** [comment]
Yeah, the USAGE is too old. I will fix tat.

**Comment by robertswiecki** [comment]
But, overall, if you provide -F with some specific value (!=0), then this will be the max file size processed. If you provide input of 1MB and set -F to 256, only first 256bytes of each input file will be read.
