### ISSUE TITLE
socketfuzzer fork child in every loop

### ISSUE THREAD

**Issue by Ch4r1l3** [google/honggfuzz#253]
i am not sure if it is normal behaviour, but when i test socketfuzzer demo, i found that it will fork a new process in every loop
there is one line code in fuzz.c:408 might be main reason of this bug
`run->pid = 0;`
i comment this line of code and it works well

**Comment by Ch4r1l3** [comment]
I read the source code and found out that comment that line is not enough, it might need to kill the child process if external socketfuzzer response bad! but the child process is still alive.

**Comment by robertswiecki** [comment]
@dobin

**Comment by dobin** [comment]
I will have a look.

**Comment by dobin** [comment]
@Ch4r1l3 will https://github.com/dobin/honggfuzz/tree/socketfuzzer_fix fix your issues?

**Comment by Ch4r1l3** [comment]
> @Ch4r1l3 will https://github.com/dobin/honggfuzz/tree/socketfuzzer_fix fix your issues?

Yes, Thanks!
