### ISSUE TITLE
`Cmp` instrumentation bitmap update

### ISSUE THREAD

**Issue by prashast** [google/honggfuzz#257]
Hi, I was looking at the `cmp` instrumentation guard code:<
```c
ATTRIBUTE_X86_REQUIRE_SSE42 void __sanitizer_cov_trace_cmp1(uint8_t Arg1, uint8_t Arg2) {
    uintptr_t pos = (uintptr_t)__builtin_return_address(0) % _HF_PERF_BITMAP_SIZE_16M;
    register uint8_t v = ((sizeof(Arg1) * 8) - __builtin_popcount(Arg1 ^ Arg2));
    uint8_t prev = ATOMIC_GET(feedback->bbMapCmp[pos]);                         
    if (prev < v) {                                                             
        ATOMIC_SET(feedback->bbMapCmp[pos], v);                                 
        ATOMIC_POST_ADD(feedback->pidFeedbackCmp[my_thread_no], v - prev);         
    }                                                                           
}        
```
If I understand correctly the Cmp bitmap will keep getting added to until both the args passed to this cmp instruction are equal (in which case `v` reaches its max value). Do you think this policy can be an issue if for example while fuzzing, equal args are passed during the first fuzz iteration itself. In that case, we would never know if an alternative data flow where unequal args are passed is ever hit or not.

**Comment by robertswiecki** [comment]
Yup, I see the problem, though I don't think it's easily fixable. We can, e.g. only increase bitmap value for __sanitizer_cov_trace_const_cmp* functions and not for __sanitizer_cov_trace_cmp. WDYT?

**Comment by prashast** [comment]
Hmm, so if I understand correctly by only updating bitmap for `const_cmp*` family of functions, you will have at most only one fuzzer argument to keep track of at which point you can make the bitmap update similar to like `__sanitizer_cov_trace_div4` I guess? 

This should take care of being complete for all `cmp` instructions where a comparison is being made against a constant but I guess I am concerned about the completeness of this solution. Wouldn't it mean then that because of this policy HonggFuzz would then stop keeping track of any `cmp` instructions which do not have a comparison against an immediate constant? If so, that sort of incompleteness would make this tracking really limiting IMO.

**Comment by robertswiecki** [comment]
Yeah,

Also, the earlier version of clang didn't emit the *const* variant, so for the time being I will keep it as is, i.e. const and non-const being treated equally.
