### ISSUE TITLE
undefined reference to `HonggfuzzNetDriver_main'

### ISSUE THREAD

**Issue by h0rs3fa11** [google/honggfuzz#261]
I try to fuzz bitcoin-core binary file,and I run the following command:
1. change `main` to `HFND_FUZZING_ENTRY_FUNCTION` in bitcoind.cpp
2. configure bitcoin file
`CC=hfuzz-clang CXX=hfuzz-clang++ ./configure`
3. run `make`

and I got these error:
`
make[2]: Leaving directory '/home/hhh/work/bitcoin-0.17'
  CXXLD    bitcoind
/tmp/libhfnetdriver.1000.4654975b555f3899.a(netdriver.o): In function netDriver_mainProgram':
netdriver.c:(.text+0x37f): undefined reference to HonggfuzzNetDriver_main'
/tmp/libhfnetdriver.1000.4654975b555f3899.a(netdriver.o): In function LLVMFuzzerInitialize':
netdriver.c:(.text+0xaec): undefined reference to HonggfuzzNetDriver_main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:3855: recipe for target 'bitcoind' failed
make[1]: *** [bitcoind] Error 1
make[1]: Leaving directory '/home/hhh/work/bitcoin-0.17/src'
Makefile:1280: recipe for target 'src/bitcoind' failed
make: *** [src/bitcoind] Error 2
`

**Comment by robertswiecki** [comment]
Please try with HFND_FUZZING_ENTRY_FUNCTION_CXX

**Comment by robertswiecki** [comment]
After that I was able to run it with

```honggfuzz -E HFND_TCP_PORT=8333 -f IN/ -- ./bitcoin-0.18.0/src/bitcoind --datadir=/tmp/FUZZ```

**Comment by h0rs3fa11** [comment]
It works, thank you so much
