### ISSUE TITLE
lowBytesIncrease.py returning abnormally on OSX

### ISSUE THREAD

**Issue by pinnace** [google/honggfuzz#263]
First off, thank you for your work on honggfuzz.

I am having problems getting the external fuzzer to work on a fresh install of honggfuzz on High Sierra.

I am running the command `sh run-honggfuzz-on-badcode1-with-externalfuzzer.sh` after building the `badcode` binary and receiving the following error message:

`[2019-07-15T07:48:32-0400][E][11505] subproc_System():446 Command '../externalfuzzers/lowBytesIncrease.py' returned with exit code 1
[2019-07-15T07:48:32-0400][E][11505] input_prepareExternalFile():377 Subprocess '../externalfuzzers/lowBytesIncrease.py' returned abnormally
[2019-07-15T07:48:32-0400][E][11505] fuzz_fetchInput():331 input_prepareFileExternally() failed
[2019-07-15T07:48:32-0400][F][11505] fuzz_fuzzLoop():395 Cound't prepare input for fuzzing`

The `run-honggfuzz-on-badcode1.sh` script works as expected, it is only the external fuzzer that is failing. I am seeing that `lowBytesIncrease.py` script is receiving an argument of `/dev/fd/7`. When using the external fuzzer with other Mac default apps, for example Safari, I am seeing Safari trying to open `/dev/fd/7` when called by the fuzzer.

**Comment by robertswiecki** [comment]
I don't work with MacOSX myself, but does it have /dev/fd at all?

**Comment by pinnace** [comment]
Yes, it does have `/dev/fd`

**Comment by robertswiecki** [comment]
Could you try fuzzing with ```-Q```, then the ```lowBytesIncrease.py``` script will tell you what the problem is. But, generally, this script has been submitted by someone loong time ago, what's your goal with using it?

**Comment by pinnace** [comment]
Hmm, so this is the output I got with -Q

`$ ../../honggfuzz -Q -n1 -u -f inputfiles -c ../externalfuzzers/lowBytesIncrease.py -- targets/badcode1 ___FILE___
cmdline:'targets/badcode1 ___FILE___', bin:'targets/badcode1' inputDir:'inputfiles', fuzzStdin:false, mutationsPerRun:6, externalCommand:'../externalfuzzers/lowBytesIncrease.py', timeout:10, mutationsMax:0, threadsMax:1

------------------------[  0 days 00 hrs 00 mins 00 secs ]----------------------
  Iterations : 3
  Mode [3/3] : Feedback Driven Mode
      Target : targets/badcode1 ___FILE___
     Threads : 1, CPUs: 2, CPU%: 0% [0%/CPU]
       Speed : 6/sec [avg: 0]
     Crashes : 0 [unique: 0, blacklist: 0, verified: 0]
    Timeouts : 0 [10 sec]
 Corpus Size : 1, max: 8192 bytes, init: 2 files
  Cov Update : 0 days 00 hrs 00 mins 00 secs ago
    Coverage : edge: 0 pc: 0 cmp: 0
---------------------------------- [ LOGS ] ------------------/ honggfuzz 1.9 /-
[2019-07-16T07:42:09-0400][E][918] subproc_System():446 Command '../externalfuzzers/lowBytesIncrease.py' returned with exit code 1
[2019-07-16T07:42:09-0400][E][918] input_prepareExternalFile():377 Subprocess '../externalfuzzers/lowBytesIncrease.py' returned abnormally
[2019-07-16T07:42:09-0400][E][918] fuzz_fetchInput():331 input_prepareFileExternally() failed
[2019-07-16T07:42:09-0400][F][918] fuzz_fuzzLoop():395 Cound't prepare input for fuzzing`

But it actually works if I just take out `-c ../externalfuzzers/lowBytesIncrease.py`

I'm brand new to the fuzzing world, but my end goal is to fuzz some of Apple's PrivateFrameworks (`/System/Library/PrivateFrameworks/`). I eventually want to do instrumented fuzzing against the libraries, but Apple doesn't supply headers for their PrivateFrameworks, so I'm trying to work around that. I figured I would start external fuzzing in the meantime, e.g. against their default PDF viewer Preview (which loads, for example, the CorePDF private framework), and can just be launched with something like `/Applications/Preview.app/Contents/MacOS/Preview /path/to/file.pdf`. Which brings me back to the original problem, where Preview is trying to open `/dev/fd/7` instead of a file in the corpus directory.

**Comment by robertswiecki** [comment]
Spring cleaning, please re-open if needed

**Comment by ploppelop** [comment]
also encountering unexplainable sporadic problems with the /dev/fd functionality on osx
