### ISSUE TITLE
persistent mode (-P) makes fuzzing results worse?

### ISSUE THREAD

**Issue by baptistapedro** [google/honggfuzz#265]
im running honggfuzz on `persistent mode (-P)` and I am having several logs like `2019-07-23T05:13:10-0700][W][34396] arch_checkWait():249 Persistent mode: pid=11688 exited with status: EXITED, exit code: 1

 I am not sure if thats alright or it is damaging the results of the fuzzing? Should I stop using -P ?

I've compiled the source code with hfuzz-clang etc.

**Comment by robertswiecki** [comment]
Persistent mode requires special fuzzed binary setup - it's described here https://github.com/google/honggfuzz/blob/master/docs/PersistentFuzzing.md
