### ISSUE TITLE
A/B testing with Honggfuzz

### ISSUE THREAD

**Issue by prashast** [google/honggfuzz#267]
I was running some personal experiments which leverage Honggfuzz as a fuzzing backend. Due to experimental reasons, I want to run two separate single-core instances of honggfuzz fuzzing the same application.

 It seems to work without a hitch and I've looked through the source code and there does not seem to be any shared state that could muddle the experimental runs. However, I just wanted to get your opinion as well that is it safe to run two separate instances of Honggfuzz on the same machine fuzzing the same application? Or is there some shared state that might cause results to be incorrect for the separate fuzzing runs?

**Comment by robertswiecki** [comment]
Yeah, sure, it's safe. It's probably better to run in separate directories, but it's probably not even required. Yeah, should be safe.
