### ISSUE TITLE
Binary-only instrumentation

### ISSUE THREAD

**Issue by thebabush** [google/honggfuzz#268]
Hi,

I've made a quick'n'dirty QEMU patch that emulates honggfuzz-style coverage on binaries (no forkserver for now).

I was wondering whether you could be interested in upstreaming the patch (ala `qemu_mode` folder in AFL) and/or if you could review / give advice on how to improve it.

The next step would be to implement the forkserver but that requires some modifications to honggfuzz itself I guess.

Anyway: https://github.com/thebabush/honggfuzz-qemu

To compile it, just patch `honggfuzz.h` with the patch in `fuzz/honggfuzz.patch` (it's a simple ifdef to bypass some errors) and then the usual:

```sh
HONGGFUZZ_PATH=~/projects/honggfuzz_qemu/ ./configure --disable-system --target-list=x86_64-linux-user
make
/path/to/honggfuzz -s -f /tmp/asd -- ./x86_64-linux-user/qemu-x86_64 target-program
```

**Comment by robertswiecki** [comment]
This is super interesting. Lemme play with it.

As for upstreaming, sure, please create some directory for this inside honggfuzz main dir, and I'll certainly pull it in.

**Comment by thebabush** [comment]
#269

**Comment by robertswiecki** [comment]
Thanks, pulled in, a comment from there:

As for your code, What do you think about linking the final qemu binary with libhfuzz.a ? You're currently duplicating some code from there, adding a custom helper function for PC and CMP. Could we add it natively to libhfuzz, and later link qemu with libhfuzz.a ?

**Comment by robertswiecki** [comment]
BTW, I made some changes so it's easier to integrate qemu with honggfuzz.

https://github.com/google/honggfuzz/commit/8d1a77ed91647051fcf54fb67b30a21efdb278b0

Here's patch for your honggfuzz-qemu which makes use of that:

https://pastebin.com/6P6Xc2jy

The final qemu binary still needs to be linked with hfuzz-g++

**Comment by robertswiecki** [comment]
Also, probably the procedure for computing honggfuzz_qemu_end_code is incorrect. I think it should be compared/set to vaddr_af or vaddr_em and not to vaddr.

**Comment by thebabush** [comment]
Thank you for your patches to honggfuzz and my qemu fork, that's exactly what I wanted to do next and how (well, better actually). It also removes the need for the pragma hack.

As for using hfuzz-g++, doesn't that have side-effects? From a quick glance at the code it looks like it wraps functions. I think directly linking `libhfuzz.a` is better. See https://github.com/thebabush/honggfuzz-qemu/commit/08958490ef56430d74d3f3fa5268aac15519d839

Regarding the vaddr thing, I'm dumb. I managed to make a mistake copy-paste'ing from AFL :/ will fix now thanks.

Also, I really need to `sed s/honggfuzz/hfuzz/g` my fork.

**Comment by robertswiecki** [comment]
Maybe in AFL they wanted to set it only once, when the main program's text section (as opposed to dynamic libs) is loaded? I'm not sure how qemu-user works internally, maybe the qemu code overlaps with dynamic libs and doing it unconditionally would catch also pcs/cmps from qemu-user

**Comment by robertswiecki** [comment]
For djpeg, it seems that manually setting _start to 0, and _end to 0x100000000 works, as the /proc/<pid>/maps looks like:

I'll check what kind of addresses the qemu elfloader reports.

```
$ cat /proc/1278053/maps 
4000000000-4000002000 r--p 00000000 fd:00 42340714                       /usr/bin/djpeg
4000002000-4000007000 r-xp 00002000 fd:00 42340714                       /usr/bin/djpeg
4000007000-400000a000 r--p 00007000 fd:00 42340714                       /usr/bin/djpeg
400000a000-400000b000 r--p 00009000 fd:00 42340714                       /usr/bin/djpeg
400000b000-400000c000 rw-p 0000a000 fd:00 42340714                       /usr/bin/djpeg
400000c000-400000d000 ---p 00000000 00:00 0 
400000d000-400080d000 rw-p 00000000 00:00 0 
400080d000-400080e000 r--p 00000000 fd:00 25952289                       /lib/x86_64-linux-gnu/ld-2.29.so
400080e000-4000831000 r-xp 00001000 fd:00 25952289                       /lib/x86_64-linux-gnu/ld-2.29.so
4000831000-4000839000 r--p 00024000 fd:00 25952289                       /lib/x86_64-linux-gnu/ld-2.29.so
4000839000-400083a000 ---p 00000000 00:00 0 
400083a000-400083b000 r--p 0002c000 fd:00 25952289                       /lib/x86_64-linux-gnu/ld-2.29.so
400083b000-400083c000 rw-p 0002d000 fd:00 25952289                       /lib/x86_64-linux-gnu/ld-2.29.so
400083c000-400083f000 rw-p 00000000 00:00 0 
4000867000-400086b000 r--p 00000000 fd:00 38803550                       /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2
400086b000-40008ae000 r-xp 00004000 fd:00 38803550                       /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2
40008ae000-40008e8000 r--p 00047000 fd:00 38803550                       /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2
40008e8000-40008e9000 r--p 00080000 fd:00 38803550                       /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2
40008e9000-40008ea000 rw-p 00081000 fd:00 38803550                       /usr/lib/x86_64-linux-gnu/libjpeg.so.8.2.2
40008ea000-40008ec000 rw-p 00000000 00:00 0 
40008ec000-4000911000 r--p 00000000 fd:00 25952296                       /lib/x86_64-linux-gnu/libc-2.29.so
4000911000-4000a89000 r-xp 00025000 fd:00 25952296                       /lib/x86_64-linux-gnu/libc-2.29.so
4000a89000-4000ad2000 r--p 0019d000 fd:00 25952296                       /lib/x86_64-linux-gnu/libc-2.29.so
4000ad2000-4000ad5000 r--p 001e5000 fd:00 25952296                       /lib/x86_64-linux-gnu/libc-2.29.so
4000ad5000-4000ad8000 rw-p 001e8000 fd:00 25952296                       /lib/x86_64-linux-gnu/libc-2.29.so
4000ad8000-4000bde000 rw-p 00000000 00:00 0 
559732f81000-559732fc0000 r--p 00000000 fd:00 39193113                   /home/jagger/src/honggfuzz/qemu_mode/honggfuzz-qemu/x86_64-linux-user/qemu-x86_64 (deleted)
...
```

**Comment by robertswiecki** [comment]
Well, elfload doesn't report loading addresses of dynamic libs, which can actually have relevant, fuzzable, code (here, in libjpeg.so). Without looking deeper into the code, for now, for my own testing I'll set _code_end to 0x5000000000 or so.

**Comment by thebabush** [comment]
`afl-qemu-cpu-inl.h` has a specific env var for this:

```c
  if (getenv("AFL_INST_LIBS")) {

    afl_start_code = 0;
    afl_end_code   = (abi_ulong)-1;

  }
```

I can just put that back in.

**Comment by robertswiecki** [comment]
Up to you, I guess having it configurable (even based on envvar) would be good.

**Comment by thebabush** [comment]
Done. It makes sense and it's consistent with AFL.

**Comment by robertswiecki** [comment]
Thanks, awesome!

**Comment by riusksk** [comment]
does it support for macos?

**Comment by thebabush** [comment]
I have no idea. Never used a mac in my life. It uses qemu user (linux). I doubt it though.

**Comment by thebabush** [comment]
I have implemented the forkserver in QEMU (I'm leveraging persistent mode... not sure it's the best idea).
Tbh it seems there's something wrong going on. My instrumentation might be unstable, because it takes too much time to guess a 64-bit constant value even if I `-F 8`.

**Comment by robertswiecki** [comment]
Thanks, I'll check it out.

**Comment by robertswiecki** [comment]
With https://github.com/google/honggfuzz/commit/99559afa16ca275e443e6111000407ff3a4de0e6 you don't need the code in fuzz/hfuzz.c any more (pretty much). Here's the diff

https://pastebin.com/UWhSX8wM

The idea is that honggfuzz's inputs are files anyway (in tmpfs, or memfd), and we can access them through /dev/fd/x.

So, now, you can simply

```$ ~/src/honggfuzz/honggfuzz -s -F8 -f IN/ -- ~/src/honggfuzz/qemu_mode/honggfuzz-qemu/x86_64-linux-user/qemu-x86_64 ./a```

and if ```./a``` reads from stdin, it will have input at fd=0. The same with using ```___FILE___ ```

**Comment by thebabush** [comment]
Cool.

Have you tried `___FILE___`? I'll double check with your patch but I get `No such file or directory` on `fopen()` in my test program.
`argv` is correct (`/dev/fd/lownumber`) though...

doing `snprintf(inputFile, sizeof(inputFile), "/dev/fd/%d", _HF_INPUT_FD);` works.

Seems like there's no fd=lownumber in `/proc/self/fd` of programs launched with `___FILE___` + qemu.

I'll look into it when I have some time.

**Comment by robertswiecki** [comment]
A yeah, the run->dynamicFileFd is CLOEXEC, so it'll be closed upon exec. Should be fixed with 

https://github.com/google/honggfuzz/commit/65880af52e3111d631b2b024e6e11295e48a4846

**Comment by thebabush** [comment]
Oh, I missed that it was opened with `CLOEXEC`. Everything seems to work fine now.

**Comment by robertswiecki** [comment]
This works very well, so closing. Thanks for working on this. Feel free to open if you'd like to add anything, or if you think the work is not complete yet.

**Comment by aug2uag** [comment]
Hi @thebabush thanks for this contribution. Re: seed files, would you please let me know what kind of files or structure there was in `/tmp/asd` for fuzzing this way. Is there a bank of seeds you'd recommend for unknown binaries?

**Comment by thebabush** [comment]
@aug2uag from your question I guess you are new to fuzzing. I don't think this is the best forum to ask this kind of questions. That being said, every fuzzer need some sample files to be effective. I'm not aware of bank of seeds. If you are fuzzing binaries parsing popular file formats you can maybe download the corpora generated by fuzzbench or similar projects. That being said, building a corpus of valid files must be done on a case-by-case basis... TL;DR: there's no free lunch (:
Other than that, you can find tons of tutorials/videos/talks online on how to fuzz binaries. Finally, note that my support for binaries in honggfuzz is pretty basic so you might have better results with AFLplusplus (which uses a more advanced QEMU patch).
