### ISSUE TITLE
python-hfuzz

### ISSUE THREAD

**Issue by thebabush** [google/honggfuzz#272]
Hi again,

during last DEF CON CTF I really would have loved to have a scriptable interface to hfuzz (or whatever fuzzer, really) to use with custom coverage-like feedback (e.g.: see [this tweet of mine](https://twitter.com/pmontesel/status/1161062287223881728)).
This is the first step in that direction. I have yet to test whether it integrates well with DBIs, but it works pretty well on its own it seems.

I'm opening the issue just to inform you in case you want to add it to the list in the README.

Use cases:
- scriptable hfuzz w/ DBIs when it makes sense
- fuzz python programs (this needs bytecode rewriting or source-code instrumentation)
- alternative to https://github.com/Battelle/afl-unicorn

Feel free to not care about this :)

EDIT: for reference, `persistent.py`, which is a 64-bit comparison, runs at ~300k execs/sec on my 6-core laptop.
EDIT2: https://github.com/thebabush/python-hfuzz

**Comment by robertswiecki** [comment]
Nice, if you want to add some documentation/links, or reference your repo from the main honggfuzz repo somehow, please go ahead!
