### ISSUE TITLE
Question: resume honggfuzz

### ISSUE THREAD

**Issue by redfast00** [google/honggfuzz#274]
When I stop honggfuzz by sending it a SIGINT signal (Ctrl+C), does it keep its progress when I then restart it with the same parameters? Or, in other words, is there any penalty if I restart the process?

**Comment by robertswiecki** [comment]
Not really, it'll go through the current corpus and "naively" minimize it, but not picking duplicates (in terms of code coverage), but generally, no, there's no penalty as far as I can tell.
