### ISSUE TITLE
Error using ___FILE___

### ISSUE THREAD

**Issue by 0xAcid** [google/honggfuzz#275]
Starting with commits 99559afa16ca275e443e6111000407ff3a4de0e6 and 65880af52e3111d631b2b024e6e11295e48a4846 implemented for issue #268, i do not manage to fuzz binaries using ___ FILE___ .

I did this to make it work, not sure the fix is good though.

```
diff --git a/subproc.c b/subproc.c
index f037f252..517d29a2 100644
--- a/subproc.c
+++ b/subproc.c
@@ -257,8 +257,7 @@ static bool subproc_PrepareExecv(run_t* run) {
     }
 
     /* The input file to _HF_INPUT_FD */
-    if (run->global->exe.persistent &&
-        TEMP_FAILURE_RETRY(dup2(run->dynamicFileFd, _HF_INPUT_FD)) == -1) {
+    if (TEMP_FAILURE_RETRY(dup2(run->dynamicFileFd, _HF_INPUT_FD)) == -1) {
         PLOG_E("dup2('%d', _HF_INPUT_FD='%d')", run->dynamicFileFd, _HF_INPUT_FD);
         return false;
     }

```

**Comment by robertswiecki** [comment]
Ah yes, should be fixed now with https://github.com/google/honggfuzz/commit/6432ff95d1bbe764b3941015591753901e8cd6c0

Thanks for the report
