### ISSUE TITLE
How to use examples

### ISSUE THREAD

**Issue by shishirjessu** [google/honggfuzz#276]
I am trying to follow the "Feedback-driven fuzzing" documentation, in which compile-time instrumentation using clang/gcc is discussed. The instructions ask you to compile your library, and then your test file, in order to fuzz. 

For the libjpeg example, a test file is present (persistent-jpeg.c), but the library itself is not available in a C file. Typically, libraries aren't encapsulated in single C files, and requite some more complicated linking. Is there an easy way to use the libjpeg example here, or do I need to do something else to use this file? Thanks!

**Comment by robertswiecki** [comment]
https://github.com/google/honggfuzz/tree/master/examples/libjpeg/README.md

Enjoy your fuzzing! :)
