### ISSUE TITLE
/usr/bin/ld: cannot find -lFuzzer

### ISSUE THREAD

**Issue by Porlockzzz** [google/honggfuzz#278]
I am trying to build the environment of openssl in example dir.
When i follow the README.md in the step 5. "Prepare fuzzing binaries",as u can see below
----------------------------------
5. Prepare fuzzing binaries
The _make.sh_ script will compile honggfuzz and libFuzzer binaries. Syntax:
```shell
make.sh <directory-with-open/libre/boring-ssl> [address|memory|undefined]
```
```shell
$ cd ..
$ /home/jagger/src/honggfuzz/examples/openssl/make.sh openssl-master address
```
----------------------------------
and i run command is `./openssl/make.sh openssl address`

the error is :
----------------------------------
/usr/bin/ld: cannot find -lFuzzer
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
----------------------------------

I believe the problem is because i missing the libFuzzer

SO,how can i get this lib?

I try the solve in https://github.com/google/fuzzing/blob/master/tutorial/libFuzzerTutorial.md

and i successed install follow the tutorial,but the error is still live

**Comment by Porlockzzz** [comment]
I fix it

**Comment by robertswiecki** [comment]
FWIW the last part with -lFuzzer builds libfuzzer fuzzers, it's not needed if you plan on using honggfuzz only.

**Comment by robertswiecki** [comment]
I modified make.sh so it only builds honggfuzz fuzzers by default https://github.com/google/honggfuzz/commit/44609d51065b5f62861ba4f821cc39a5ec749fc1

**Comment by Porlockzzz** [comment]
thank you,now i understand it.I removed "-lFuzzer" and finish the build   hhh :)
