### ISSUE TITLE
Possibly missing OOBs with ASan ?

### ISSUE THREAD

**Issue by oliverchang** [google/honggfuzz#282]
Might be missing something here, but taking a cursory look at https://github.com/google/honggfuzz/blob/ac7df4eddcbf10a870e94933e13405544550bac4/libhfuzz/fetch.c#L37 and https://github.com/google/honggfuzz/blob/ac7df4eddcbf10a870e94933e13405544550bac4/libhfuzz/persistent.c#L72,

It looks like honggfuzz uses a shared mmap'ed buffer for storing all input which is passed directly to LLVMFuzzerTestOneInput. It seems like OOB accesses may be missed here, since an OOB access can happen in between the actual input contents and the end of the mmap region.

Note that libFuzzer creates a new buffer for every new input to avoid this: https://github.com/llvm-mirror/compiler-rt/blob/92e35995a6175bd255489b469d7179b504b6c7bf/lib/fuzzer/FuzzerLoop.cpp#L542

**Comment by robertswiecki** [comment]
Hi,

The underlying buffer (memfd_create() in case of Linux, shm for other Unices) is dynamically resized for each input - https://github.com/google/honggfuzz/blob/master/input.c#L57

If memory which is mmap()'d but not underpinned by the file is touched, SIGBUS is generated in such case.

```
SIGBUS

Attempted access to a portion of the buffer that does not correspond to the file (for example, beyond the end of the file, including the case where another process has truncated the file).
```

**Comment by robertswiecki** [comment]
Tho, I need to confirm all that. It might depend on implementation whether the case you pointed out is handled this way.

**Comment by robertswiecki** [comment]
So, you were right, Linux doesn't report access within the same memory page, which is not underpinned by a storage. So, it's per-page granularity. Shame... well, the only thing I can image is to use some asan/msan code to define such buffer's lenght in its shadow maping. I'll play with it.

**Comment by oliverchang** [comment]
Thanks! Or alternatively.. allocate a separate buffer of the exact size and copy the contents as libFuzzer does. 

In any case, I don't think we can catch SIGBUS on CF due to https://github.com/google/honggfuzz/issues/281 :)

**Comment by robertswiecki** [comment]
The problem here is that honggfuzz is compiled w/o asan support itself, and the buffer allocation is part of a library which is part of honggfuzz, therefore the library doesn't have access to asan internal functions (it's not guaranteed that it's linked/compiled with asan itself) to register buffers with asan internal functions. A bit of chicken and egg here :). I'll think about it a bit more, but I don't have hopes.

**Comment by robertswiecki** [comment]
I don't see a good way of fixing this. libhfuzz doesn't need to be compiled with the same set of options as the target binary, so we cannot force it to use msan/asan functions to mark input buffer to be of a specific length, b/c the final binary could be compiled w/o ASAN.

I don't see a good solution here unfortunately.
