### ISSUE TITLE
honggfuzz fuzz dynamoRIO subprcess fail

### ISSUE THREAD

**Issue by LH-413x** [google/honggfuzz#285]
hi,
I am trying to write a blackbox fuzz tool based on  honggfuzz and dynamoRIO, but it always crash as bellow:
Crash: saved as './SIGILL.PC.71124306.STACK.badbad0cfbc45e93.CODE.-6.ADDR.(nil).INSTR.pop____%rbx.2019-11-22.17:13:57.3720.fuzz'
Signal 2 (Interrupt) received, terminating

run the command, you will see it
honggfuzz -f /tmp/tmp -- ~/tools/fuzzer/dynamorio/7.1.0-1-build/bin64/drrun -- ~/workstation/compare-fuzzers/test  ___FILE___

**Comment by LH-413x** [comment]
I didn't make any change to honggfuzz and dynamoRIO

**Comment by robertswiecki** [comment]
I image that DynamoRIO is doing a lot of interesting tricks to make the code work, probably also testing some invalid instructions.

Maybe try to remove SIGILL from linux/trace.c (set .important = false for SIGILL) and see how it works.

Or, maybe try to compile honggfuzz for POSIX

```shell
OS=POSIX make clean all
```

This way, honggfuzz will not report handled sigtraps (this SIGILL is probably handled by DynamoRIO code0.

Alternatively, if you're trying to fuzz a black-box binary, maybe you can take a look at the qemu_mode/ directory, which is helping exactly with this.
