### ISSUE TITLE
No splicing in honggfuzz?

### ISSUE THREAD

**Issue by thebabush** [google/honggfuzz#286]
Hi again,

I was looking around the code for the splicing/merging logic but I can't seem to find it (I might be dumb ofc).

Was it because it was never implemented or you have data that suggests it's not useful?
I wanted to add `libprotobuf-mutator` support to honggfuzz but without the splicing it's not really that useful for my use case.

babush

**Comment by robertswiecki** [comment]
I've never implemented it, I guess it can be useful. It didn't come to my mind. Feel free to take a stab at it if you have some ideas around it. I don't mind additional code in the mutator.c

**Comment by robertswiecki** [comment]
I'll close it, b/c I don't see me working on it soon, but it'd be a good functionality to have in honggfuzz

**Comment by robertswiecki** [comment]
FYI: first version implemented in https://github.com/google/honggfuzz/commit/150cbd741c7346571e5a9c47b7819d2e37500a64

**Comment by thebabush** [comment]
Nice! Thanks for letting me know
