### ISSUE TITLE
How honggfuzz cover cmp

### ISSUE THREAD

**Issue by LH-413x** [google/honggfuzz#290]
Hi, 
I am trying read honggfuzz source code,  honggfuzz can cover below code, however I don't know why
 ```cpp
 if (buf[0] == 'P') {
        if (buf[1] == 'W') {
            if (buf[2] == 'N') {
                if (buf[3] == 'I') {
                    //if (buf[4] == 'T') {
                        printf("Found it!\n");
                        ((void(*)())0x0)();
                    //}
                }
            }
        }
    }
```
below is honggfuzz source code, I guess Arg1 and Arg1 come from `cmp Arg1, Arg2`. bbMapCmp only store `((sizeof(Arg1) * 8) - __builtin_popcount(Arg1 ^ Arg2))`, how honggfuzz recover the value to characters like 'P', 'W', 'N', 'I', 'T'? 
```cpp
ATTRIBUTE_X86_REQUIRE_SSE42 static inline void hfuzz_trace_cmp4_internal(
    uintptr_t pc, uint32_t Arg1, uint32_t Arg2) {
    uintptr_t pos = pc % _HF_PERF_BITMAP_SIZE_16M;
    register uint8_t v = ((sizeof(Arg1) * 8) - __builtin_popcount(Arg1 ^ Arg2));
    uint8_t prev = ATOMIC_GET(feedback->bbMapCmp[pos]);
    if (prev < v) {
        ATOMIC_SET(feedback->bbMapCmp[pos], v);
        ATOMIC_POST_ADD(feedback->pidFeedbackCmp[my_thread_no], v - prev);
    }
}

```

**Comment by robertswiecki** [comment]
Exactly that :). The smaller the (Hamming distance)[https://en.wikipedia.org/wiki/Hamming_distance] between the input byte and the const value, the greater the score (cmp goodness) for a given comparison. Inputs which improve cmp goodness get retained. Retaining (adding to the corpus) better input (in terms of hamming distance) makes it likely to improve it even more.

In short, it's just hill climbing on per-bit basis.

**Comment by robertswiecki** [comment]
Also, compilers might optimize it to if (*(uint32_t*), "PWNIT") or even to memcmp.

**Comment by LH-413x** [comment]
thanks ! !
