### ISSUE TITLE
Dry-run only

### ISSUE THREAD

**Issue by ahpaleus** [google/honggfuzz#296]
Hi, 
Honggfuzz is very useful for me to execute binaries in different threads & monitor for crashes from previously mutated testcases (from dharma, for example). 
What's the best way to run honggfuzz with Dry Run phase only?

**Comment by robertswiecki** [comment]
You can use the verifier (-V) for that with -r0

```honggfuzz -r0 -V --input corpus -- /usr/bin/djpeg ___FILE___```

I think -V should imply -r0, will check.

**Comment by robertswiecki** [comment]
Ah.. noes, actually both ```-V``` and ```-r0``` are required, as per original author's comment

```
253     if (hfuzz->mutate.mutationsPerRun == 0U && hfuzz->cfg.useVerifier) {◅                                                                                                            
254         LOG_I("Verifier enabled with mutationsPerRun == 0, activating the dry run mode");◅
255     }◅
```

**Comment by ahpaleus** [comment]
@robertswiecki, thank you
