### ISSUE TITLE
Persistent fuzzer backwards compatibility

### ISSUE THREAD

**Issue by mjkoo** [google/honggfuzz#297]
It looks like the size/format of the feedback_t structure was changed at https://github.com/google/honggfuzz/commit/76191f2c2ecfdfccf7d1453b5f08d7adf7016015 causing persistent fuzzing harnesses linked against older versions of libhfuzz to be incompatible with newer versions of honggfuzz, and vice-versa. It would be nice if either some backwards compatibility were supported, or if an easy way of determining what version of libhfuzz a binary target is linked with were available.

**Comment by robertswiecki** [comment]
Yes, I was too hit it by it in my personal/corp setups, so I need to rethink my approach to it.

In any case, I should make a promise not to change the fuzzer/fuzzee interface unless a reasonably long deprecation period expired or a backwards compatibility solution is implemented.

Thanks for pointing this out!

**Comment by robertswiecki** [comment]
For the last few releases I kept the interface between fuzzer and fuzzees unchanged or backwards compatible. I intend to keep it this way, and if need arises to change it, I'll try to make either backwards-compatible or to notify potential users.
