### ISSUE TITLE
Null deference

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/honggfuzz#298]
There is no check for the failed malloc

https://github.com/google/honggfuzz/blob/4612f676291c47a1a8344789c804a6a95c78df84/socketfuzzer/vulnserver_cov.c#L26

This in turn would cause a segfault， when buff is dereferenced

**Comment by robertswiecki** [comment]
Thanks for the report, fixed in https://github.com/google/honggfuzz/commit/ce13a2f0e0b8f487d6707a0de94b0b99328002b3
