### ISSUE TITLE
Performances regression following 16de698a

### ISSUE THREAD

**Issue by 0xAcid** [google/honggfuzz#299]
Hey there, not sure I am the only one experiencing this, but following commit 16de698a3d5a08327194254115288c464549cbf5 i have some performances regression while fuzzing client binaries.  (for instance, on a simple sample that just reads an input and parses it, i go down from 800 execs/s to 150 exec/s on a single core).
I did not investigate further, nor have any solution in mind, I just thought I would let you know.

Keep up the good work,
Cheers

**Comment by robertswiecki** [comment]
Hi,

Which OS are you using? If Linux, could you remove the MAP_POPULATE related code, and try w/o it

```C
#if defined(MAP_POPULATE)
    flag |= MAP_POPULATE;
#endif /* defined(MAP_POPULATE) */
```

**Comment by 0xAcid** [comment]
Indeed, removing the MAP_POPULATE related code fixes the performance issue.
Thanks for your help!

**Comment by robertswiecki** [comment]
Ok, flag removed with https://github.com/google/honggfuzz/commit/09aa445897d7650d3cac23865a13a5926ac10dd1
