### ISSUE TITLE
Null deference

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/honggfuzz#302]
There is no check for the failed strstr
https://github.com/google/honggfuzz/blob/199428ed6fd32958eb90f88c6137864c2103bff5/mac/arch.c#L302
This in turn would cause a segfault， when off is dereferenced
https://github.com/google/honggfuzz/blob/199428ed6fd32958eb90f88c6137864c2103bff5/mac/arch.c#L303

**Comment by robertswiecki** [comment]
Thanks,

fixed with https://github.com/google/honggfuzz/commit/36ddc3bbc4402a7a1a680986cb40e963f4aa1311
