### ISSUE TITLE
Error: This process has too many PC guards

### ISSUE THREAD

**Issue by kianenigma** [google/honggfuzz#304]
## Problem 

- using hoggfuzz-rs
- Run status: 

```
Persistent signature found in 'hfuzz_target/x86_64-apple-darwin/release/submit_solution'. Enabling persistent fuzzing mode
cmdline:'hfuzz_target/x86_64-apple-darwin/release/xxx', bin:'hfuzz_target/x86_64-apple-darwin/release/xxx' inputDir:'hfuzz_workspace/xxx/input', fuzzStdin:false, mutationsPerRun:6, externalCommand:'', timeout:30, mutationsMax:0, threadsMax:16
```

All fuzz threads are terminated via 

```
[2020-02-20T08:59:30+0100][F][7115] __sanitizer_cov_trace_pc_guard_init():299 This process has too many PC guards:67108864 (current module:108108 start:0x10cc96308 stop:0x10cd6956c)
```

namely 

https://github.com/google/honggfuzz/blob/67db30a280ff46335b2ef9aaf71fa4c8cb89005b/libhfuzz/instrument.c#L341-L345

## More context

- I have tried combinations of `-P` and `-x` for different mode and none changes anything. 

I couldn't find any issue pertaining to this error message. For now I am interested in learning what can lead to this message. This happens to me on a rather big codebase and I am working on getting a small reproducible example. Thanks!

**Comment by robertswiecki** [comment]
Which honggfuzz version are you using? There were some changes along the way which limited the number of required pc guards for MacOS X. Please try with honggfuzz at HEAD.

If this doesn't work, I'd suggest recompiling honggfuzz and your fuzzed programs with increased _HF_PC_GUARD_MAX to (1024ULL * 1024ULL * 128ULL) or even more if needed.

Also... >64M guards is a looooot, are you sure your fuzzed code is complex enough to have so many? A typical code (like openssl binary) will not have more than 50k, a bigger program mayb 2M. If not, maybe there's a bug somewhere in sanitizer-coverage or in honggfuzz libs.

**Comment by kianenigma** [comment]
> There were some changes along the way which limited the number of required pc guards for MacOS X. Please try with honggfuzz at HEAD.

AFAIK last I built the HEAD with some minor tweaks to get it to work on the latest OSX.

> Also... >64M guards is a looooot, are you sure your fuzzed code is complex enough to have so many? A typical code (like openssl binary) will not have more than 50k, a bigger program mayb 2M. If not, maybe there's a bug somewhere in sanitizer-coverage or in honggfuzz libs.

That's a good point. I am not sure what PC guards exactly match to but all in all: 
- No my code is def. smaller than openssl :D
- It is a rather long and iterative algorithm though. Running it usually takes a few seconds per iteration. 

Could this make sense?

**Comment by robertswiecki** [comment]
I can only recommend looking into the ```__sanitizer_cov_trace_pc_guard_init``` function, and adding some debug info there, to see how many modules its initializing, and what's the range of start-stop params for each module. 

Maybe this way you can figure out which module is responsible for those millions of guards.
