### ISSUE TITLE
Persistent mode signature added when it should not

### ISSUE THREAD

**Issue by cnheitman** [google/honggfuzz#308]
Hey there, I'm having an issue when compiling a target with hfuzz-cc. It is adding the persistent signature (`_HF_PERSISTENT_SIG`) despite not using the feature (which leads to honggfuzz to autodetect and enable persistent mode when it is not the case).

Was there a change in that regard that I'm missing?

I looked a little bit into it and this commit 77ea4dc4b499799e20ba33ef5df0152ecd113925 seems to be causing the issue.

**Comment by robertswiecki** [comment]
Thanks for the report. Yes, I think I know what's going on. Will look into it soon.

**Comment by robertswiecki** [comment]
Should be fixed with https://github.com/google/honggfuzz/commit/4887bbeee207da835af743b9abcbb7f6fd6e54b4
