### ISSUE TITLE
Honggfuzz produces a huge number of HF.sanitizer.log files with a detect_odr_violation warning

### ISSUE THREAD

**Issue by farazsth98** [google/honggfuzz#309]
Hello there,

I was attempting to use `honggfuzz` + `dharma` to fuzz v8. I downloaded v8 compiled with ASan from [here](https://commondatastorage.googleapis.com/v8-asan/index.html), specifically [this version](https://www.googleapis.com/download/storage/v1/b/v8-asan/o/linux-release%2Fd8-asan-no-inline-linux-release-v8-component-53466.zip?generation=152782).

I created a bunch of test cases using `dharma`, and then ran `honggfuzz` as follows:

`./honggfuzz -t 5 -i inputs/ -- ./d8 ___FILE___`

While the fuzzer runs, it generates an insane number of `HF.sanitizer.log.*` files, all with just the following text:

```
WARNING: found 2 unrecognized flag(s):                                          
    detect_odr_violation                                                        
    detect_odr_violation
```

I'm not exactly sure what the issue is. `detect_odr_violation` is a valid flag within ASan, and I don't get any warnings like this when running `d8` normally.

I could technically just download the v8 source and build it with `hclang` and test. I could also run the fuzzer from a garbage directory and ignore all the log files, but I feel like that's a workaround, not a solution, so I would like to see if there's a solution for this.

**Comment by robertswiecki** [comment]
Hi,

Feell free to remove this flag from sanitizers.c in honggfuzz, and running without it. Newer clang/asan versions (as in 7, 8, 9, 10) certainly have it. Maybe whoever builds those v8 binaries uses either some ancient or some very, very new clang+asan version.

**Comment by farazsth98** [comment]
Hi,

Thank you. You are correct, the binary I'm using was built around early 2018, so it makes sense for `detect_odr_violation` to not have existed back then I suppose.

For reference, [here is a patch file that will fix this issue](https://gist.github.com/farazsth98/23146cb1fa5c36e5951feed8976018c8) if anyone else ends up running into it. It applies cleanly to commit 8db2a2b8fe90d1bde58b5ee54c7d718da279f4d5.
