### ISSUE TITLE
ld.lld error: unable to find library -lrt

### ISSUE THREAD

**Issue by yeshen4328** [google/honggfuzz#318]
I am able to compile a demo.c with honggfuzz-clang++, but when I use honggfuzz-clang++ to compile a project vie ninja, it goes wrong.
![image](https://user-images.githubusercontent.com/12472005/80307049-59b71a80-87f9-11ea-946a-a45fe16655d4.png)

**Comment by robertswiecki** [comment]
Can you remove the ```args[j++] = "-lrt";``` from hfuzz-cc.c and recompile it and give it a try. I never tried actually to compile anything except honggfuzz itself under Android.

**Comment by yeshen4328** [comment]
> Can you remove the `args[j++] = "-lrt";` from hfuzz-cc.c and recompile it and give it a try. I never tried actually to compile anything except honggfuzz itself under Android.

I tried, but it reported another error:
![image](https://user-images.githubusercontent.com/12472005/80325908-a89c9880-8869-11ea-8907-2bd53e5c74ca.png)
(I wanna fuzz a service of android with honggfuzz, and this step aims to instrument the source code with hfuzz-clang++).

**Comment by robertswiecki** [comment]
How did you compile honggfuzz itself, with which CC?

**Comment by robertswiecki** [comment]
Please re-open if it's still broken, or you'd like to discuss this further.
