### ISSUE TITLE
pthread_mutex_lock  Undefined error on macOS

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#319]
Run environment:

1. macOS 10.14
2. Xcode 10
3. honggfuzz 2.2

honggfuzz run error after update version to 2.2, it must appear every time:

Entering phase 1/3: Dry Run
Launched new fuzzing thread, no. #0
Launched new fuzzing thread, no. #1
[2020-04-29T18:59:02+0800][F][36119] util_mutexLock():280 input_getNext():127 pthread_mutex_lock(0x102c7e378): Undefined error: 0

run cmd:
honggfuzz  -V -f ../input  -P  -- ./pmain

**Comment by robertswiecki** [comment]
Thanks for the report - yhe mutex was not initialized properly, please check at HEAD or with https://github.com/google/honggfuzz/commit/8bf78b88afe5310f1e9b0a41c1c239588cdf1d98
