### ISSUE TITLE
Add ASLR-disable support for macOS

### ISSUE THREAD

**Issue by pwn0rz** [google/honggfuzz#322]
Hi, it seems that macOS has options for disable ASLR too, that might be helpful when doing feedback-driven fuzz, got that from LLDB source code https://github.com/llvm/llvm-project/blob/master/lldb/tools/darwin-debug/darwin-debug.cpp , will you please consider adding this feature?

**Comment by robertswiecki** [comment]
Yes, definitely. The current code uses fork(), switching to this family of functions seems possible I guess, but will require some testing.

**Comment by robertswiecki** [comment]
Spring cleaning, please re-open if needed
