### ISSUE TITLE
honggfuzz target exiting just after start if number of threads are >= 16

### ISSUE THREAD

**Issue by vladqqq** [google/honggfuzz#325]
Trying to fuzz simple test target. Host machine is dual xeon e5 2699 v3 (total 36 cores), os is ubuntu 18.04.
If i specify -threads with <16, all works fine (number 16 is approximation, it differs when different fuzz targets used).
If i specify >16, i see next output:

Persistent signature found in '/home/test/honggfuzz_target'. Enabling persistent fuzzing mode
Start time:'2020-05-05.14.41.42' bin:'/home/test/honggfuzz_target', input:'corpus', output:'corpus', persistent:true, stdin:false, mutation_rate:5, timeout:100, max_runs:0, threads:32, minimize:false, git_commit:71c712fd2cc2c15e545ca447fc9219a246be82fb
Entering phase 1/3: Dry Run
Launched new fuzzing thread, no. #0
Launched new fuzzing thread, no. #1
Launched new fuzzing thread, no. #2
Launched new fuzzing thread, no. #3
Launched new fuzzing thread, no. #8
Launched new fuzzing thread, no. #5
Launched new fuzzing thread, no. #6
Launched new fuzzing thread, no. #7
Launched new fuzzing thread, no. #4
Launched new fuzzing thread, no. #9
Launched new fuzzing thread, no. #10
Launched new fuzzing thread, no. #11
Launched new fuzzing thread, no. #12
Launched new fuzzing thread, no. #30
Launched new fuzzing thread, no. #14
Launched new fuzzing thread, no. #15
Launched new fuzzing thread, no. #16
Launched new fuzzing thread, no. #17
Launched new fuzzing thread, no. #18
Launched new fuzzing thread, no. #19
Launched new fuzzing thread, no. #20
Launched new fuzzing thread, no. #21
Launched new fuzzing thread, no. #22
Launched new fuzzing thread, no. #23
Launched new fuzzing thread, no. #24
Launched new fuzzing thread, no. #25
Launched new fuzzing thread, no. #26
Launched new fuzzing thread, no. #27
Launched new fuzzing thread, no. #28
Launched new fuzzing thread, no. #29
Launched new fuzzing thread, no. #13
Launched new fuzzing thread, no. #31
Entering phase 2/3: Switching to the Feedback Driven Mode
Persistent mode: Launched new persistent pid=10621
Sz:4 Tm:82,971us (i/b/h/e/p/c) New:0/0/0/3/0/79, Cur:0/0/0/3/0/3
Sz:8 Tm:68us (i/b/h/e/p/c) New:0/0/0/0/0/6, Cur:0/0/0/3/0/7
Sz:16 Tm:47us (i/b/h/e/p/c) New:0/0/0/0/0/2, Cur:0/0/0/3/0/15
Sz:64 Tm:46us (i/b/h/e/p/c) New:0/0/0/0/0/1, Cur:0/0/0/3/0/63
Sz:103 Tm:59us (i/b/h/e/p/c) New:0/0/0/0/0/12, Cur:0/0/0/3/0/101
Persistent mode: Launched new persistent pid=10626
Persistent mode: Launched new persistent pid=10627
Persistent mode: Launched new persistent pid=10630
Persistent mode: Launched new persistent pid=10631
Persistent mode: Launched new persistent pid=10632
Persistent mode: Launched new persistent pid=10635
Persistent mode: Launched new persistent pid=10639
Persistent mode: Launched new persistent pid=10641
Persistent mode: Launched new persistent pid=10650
Persistent mode: Launched new persistent pid=10654
Persistent mode: Launched new persistent pid=10659
Persistent mode: Launched new persistent pid=10660
Persistent mode: Launched new persistent pid=10661
[2020-05-05T14:41:43+0000][W][10637] arch_traceWaitForPidStop():879 PID 10663 not in a stopped state - status:14
[2020-05-05T14:41:43+0000][W][10637] arch_attachToNewPid():169 arch_traceAttach(pid=10663) failed
[2020-05-05T14:41:43+0000][F][10637] arch_prepareParentAfterFork():199 Couldn't attach to pid=10663

I've tried to debug this situation and was found that at the moment, when we see "PID 10663 not in a stopped state - status:14" target process already exited.

I've attached test project that i've used.
[src.tar.gz](https://github.com/google/honggfuzz/files/4581611/src.tar.gz)

**Comment by robertswiecki** [comment]
On my 8C/16T CPU it works ok. Could it be that you reach some limits on your machine? Like some cgroup limits, or maybe nproc (ulimit -a) limits?

**Comment by robertswiecki** [comment]
Though, status 14 means exited with signal 14 (SIGALRM). Interesting. We only disable alarm() with https://github.com/google/honggfuzz/blob/649e48630afce64727e7416e7867d1a302b999d1/linux/arch.c#L148 - so it's probably not it.

**Comment by vladqqq** [comment]
There are no errors in dmesg/syslog. 

root@dev1:~/honggfuzz# ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2062969
max locked memory       (kbytes, -l) 16384
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2062969
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by vladqqq** [comment]
just installed fresh ubuntu 18.04 on second server with similiar configuration (also 36 cpu cores) and it's doesn't have such problems.... seems that this is my local problem with clang.

**Comment by robertswiecki** [comment]
I think I know what's going on. The network namespacing under Linux is somewhat broken, and when starting many processes at once it causes deadlocks in the kernel.

You can try fuzzing with ```--linux_ns_net=no```. This should fix the problem

**Comment by vladqqq** [comment]
You are right! --linux_ns_net=no fixed problem.
Thanks!

**Comment by robertswiecki** [comment]
FYI: I disabled the opportunistic net-ns creation with https://github.com/google/honggfuzz/commit/8317fdec700811930a8364bceb5246bccbff5445
