### ISSUE TITLE
Randomly terminated

### ISSUE THREAD

**Issue by winter2020** [google/honggfuzz#329]
I run honggfuzz on very simple program, it always terminated before reaching the maximum iterations. 
logs:
```
19045 [2020-05-10T21:05:58+0800][E][364011] input_getRandomInputAsBuf():572 The dynamic input queue shouldn't be empty
19046 [2020-05-10T21:05:58+0800][D][364011] subproc_New():368 Forking new process for thread: 0
19047 [2020-05-10T21:05:58+0800][D][364011] subproc_New():419 Launched new process, pid=367335, thread: 0 (concurrency: 1)
19048 [2020-05-10T21:05:58+0800][D][367335] subproc_New():407 Launching '../hello' on file '/dev/fd/1021' (file mode)
19049 [2020-05-10T21:05:59+0800][W][364011] arch_traceWaitForPidStop():881 PID 367335 not in a stopped state - status:14 (SIGNALED, signal: 14 (Alarm clock))
19050 [2020-05-10T21:05:59+0800][W][364011] arch_attachToNewPid():169 arch_traceAttach(pid=367335) failed
19051 [2020-05-10T21:05:59+0800][F][364011] arch_prepareParentAfterFork():199 Couldn't attach to pid=367335

```
It seems that honggfuzz is failed to attach the children process after spawning, is there any way to fix this or something wrong on my environment? The alarm clock signal is not sent by my program.

**Comment by robertswiecki** [comment]
I think it's the same as https://github.com/google/honggfuzz/issues/325

I disabled the optional creation of network namespaces now with https://github.com/google/honggfuzz/commit/8317fdec700811930a8364bceb5246bccbff5445 so please try at HEAD.

But, if I'm not mistaken, this problem has been fixed in newer kernel versions, so upgrading the kernel could help as well.

**Comment by robertswiecki** [comment]
Please re-open if that didn't solve the problem.

**Comment by winter2020** [comment]
I jumped to honggfuzz tags/2.0, the issue disappears. I think this issue is the same as #325 .  Thanks for your help.
