### ISSUE TITLE
unable to open file for adobe on macOS

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#335]
`honggfuzz -i input -e pdf -t4 -- /Applications/Adobe\ Acrobat\ Reader\ DC.app/Contents/MacOS/AdobeReader ___FILE___`

it can't open the mutated file for GUI app on macOS, because '/dev/fd/%d' is invalid for GUI app on macOS.

> Entering phase 1/3: Dry Run
> Launched new fuzzing thread, no. #0
> Launched new fuzzing thread, no. #101 
> [2020-05-17T21:11:02+0800][W][34650] arch_launchChild():356 args:/Applications/Adobe Acrobat Reader DC.app/Contents/MacOS/AdobeReader /dev/fd/1021
> [2020-05-17T21:11:02+0800][W][34651] arch_launchChild():356 args:/Applications/Adobe Acrobat Reader DC.app/Contents/MacOS/AdobeReader /dev/fd/1021
> [2020-05-17T21:11:06+0800][W][34671] arch_launchChild():356 args:/Applications/Adobe Acrobat Reader DC.app/Contents/MacOS/AdobeReader /dev/fd/1021

**Comment by robertswiecki** [comment]
Hi riusksk

I'm not MacOS expert, so not sure how it works, but are you saying that /dev/fd/<n> is valid for console apps, but not for gui apps?

**Comment by robertswiecki** [comment]
Spring cleaning, please re-open if needed
