### ISSUE TITLE
Error message "LLVMFuzzerTestOneInput is not defined" also when LLVMFuzzerTestOneInput is defined?

### ISSUE THREAD

**Issue by practicalswift** [google/honggfuzz#336]
Thanks a lot for writing and maintaining a very nice fuzzer!

In Bitcoin Core we encourage our users to fuzz our code using various fuzzers including the excellent Honggfuzz.

These are the quick start instructions we provide at https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md:

```
$ git clone https://github.com/bitcoin/bitcoin
$ cd bitcoin/
$ ./autogen.sh
$ git clone https://github.com/google/honggfuzz
$ cd honggfuzz/
$ make
$ cd ..
$ CC=$(pwd)/honggfuzz/hfuzz_cc/hfuzz-clang CXX=$(pwd)/honggfuzz/hfuzz_cc/hfuzz-clang++ ./configure --enable-fuzz --with-sanitizers=address,undefined --enable-c++17
$ make
$ mkdir -p inputs/
$ honggfuzz/honggfuzz -i inputs/ -- src/test/fuzz/process_message
```

These instructions have been working fine up until quite recently when they [no longer appear to work when using a fresh `honggfuzz` compiled from `master`](https://github.com/bitcoin/bitcoin/pull/18739#issuecomment-629504388). (The only thing that has changed on our side is a recent switch to C++17 for the fuzzers, but I assume that is unrelated.)

The error message reported is `LLVMFuzzerTestOneInput():38 Define 'int LLVMFuzzerTestOneInput(uint8_t * buf, size_t len)' in your code to make it work`, but [we do define `LLVMFuzzerTestOneInput`](https://github.com/bitcoin/bitcoin/blob/54f812d9d29893c690ae06b84aaeab128186aa36/src/test/fuzz/fuzz.cpp#L34-L47) (and `libFuzzer` works as expected).

I assume our quick start instructions are incorrect in some way: are we missing something obvious here? :)

**Comment by MarcoFalke** [comment]
I am running a299f3f17074663c0dffba029b2171a0c09d4dee from https://bodhi.fedoraproject.org/updates/FEDORA-2020-a8efa72ccf , not self-compiled. Not sure which commit @practicalswift is using, but it shouldn't be too hard to bisect (assuming this is a reproducible bug).

**Comment by practicalswift** [comment]
FWIW:

```
$ src/test/fuzz/multiplication_overflow < /dev/null
Accepting input from '[STDIN]'
Usage for fuzzing: honggfuzz -P [flags] -- src/test/fuzz/multiplication_overflow
[2020-05-19T19:05:28+0000][F][17104] LLVMFuzzerTestOneInput():39 Define 'int LLVMFuzzerTestOneInput(uint8_t * buf, size_t len)' in your code to make it work
$ nm src/test/fuzz/multiplication_overflow | grep LLVMFuzzer
00000000000d8740 W LLVMFuzzerInitialize
00000000000d8750 W LLVMFuzzerMutate
00000000000d8780 W LLVMFuzzerTestOneInput
$ cd honggfuzz/
$ git rev-parse HEAD
d083bf81eb1c8a3b2dd702def5281afa5a7f74d2
```

d083bf81eb1c8a3b2dd702def5281afa5a7f74d2 is current `master` :)

**Comment by robertswiecki** [comment]
weak symbols are honggfuzz's symbols, which provide this "You should define LLVM().. " info. I think you want to see those as ```T``` type of symbols and not ```W``` symbols.

**Comment by robertswiecki** [comment]
I'll take a look at it sometime next week, unless somebody beats me to it.

**Comment by MarcoFalke** [comment]
Is there any way we can help resolve this issue? Is this a bug on our side or on the side of honggfuzz?

If the bug is on the side of honggfuzz, it would be best to remove the honggfuzz compile steps from our readme for now until the bug has been addressed.

**Comment by robertswiecki** [comment]
The problem is here https://github.com/bitcoin/bitcoin/blob/171cd05ae3413e18fd6382572c86f2bb21ab2fd9/src/test/fuzz/fuzz.cpp#L20

Changing

```C
#if defined(__AFL_COMPILER) || !defined(MAC_OSX)```
```

to


```C
#if defined(__AFL_COMPILER)
```

should fix it.

Background: bitcoin fuzzing harness provides its own main function (weak), which takes precedence over honggfuzz's main (also weak). Making sure it's not compiled in solves the problem. The reason why it works with libfuzzer is that libfuzzer provides a non-weak main, which takes precedence over bitcoin's one.

If you'd like to change bitcoin's code to make it work with honggfuzz, please let me know, I'll maybe suggest a better macro check. Otherwise, feel free to modify the code as above.

**Comment by MarcoFalke** [comment]
@robertswiecki Thanks!
@practicalswift Can this be closed?

**Comment by practicalswift** [comment]
@robertswiecki Thanks a lot! Now solved in our tree.

@MarcoFalke Absolutely! Closing :)

**Comment by b1tg** [comment]
I solved this issue by add `extern "C"` before the function.

```c++
extern "C" int LLVMFuzzerTestOneInput(uint8_t* buf, size_t len) {
}
```

**Comment by jiridanek** [comment]
> ```c++
> uint8_t
> ```

My problem seems to be the ordering on the compiler command line. If `-lFuzzingEngine` comes _after_ the fuzz target `.o` file, I get a `W` symbol, and if I flip the order, with `.o` going last, I end up with a `T` symbol.

```
root@cb5aeadeaffb:/src/qpid-proton/build/c/tests/fuzz# /usr/local/bin/clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -stdlib=libc++ -fvisibility=hidden -O3 -lFuzzingEngine -DNDEBUG -flto=thin "CMakeFiles/fuzz-sniff-header.dir/fuzz-sniff-header.c.o" "CMakeFiles/fuzz-sniff-header.dir/__/__/src/core/autodetect.c.o" -o fuzz-sniff-header  -lpthread -lc -ldl -lrt
root@cb5aeadeaffb:/src/qpid-proton/build/c/tests/fuzz# nm fuzz-sniff-header | grep Input
000000000040c4c0 T LLVMFuzzerTestOneInput
0000000000406310 T fetchIsInputAvailable
0000000009421b48 b firstInputUSecs
root@cb5aeadeaffb:/src/qpid-proton/build/c/tests/fuzz# /usr/local/bin/clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -stdlib=libc++ -fvisibility=hidden -O3 -DNDEBUG -flto=thin "CMakeFiles/fuzz-sniff-header.dir/fuzz-sniff-header.c.o" "CMakeFiles/fuzz-sniff-header.dir/__/__/src/core/autodetect.c.o" -o fuzz-sniff-header  -lFuzzingEngine -lpthread -lc -ldl -lrt
root@cb5aeadeaffb:/src/qpid-proton/build/c/tests/fuzz# nm fuzz-sniff-header | grep Input
0000000000402790 W LLVMFuzzerTestOneInput
0000000000406450 T fetchIsInputAvailable
0000000009421b48 b firstInputUSecs
```

**Comment by jiridanek** [comment]
> > weak symbols are honggfuzz's symbols, which provide this "You should define LLVM().. " info. I think you want to see those as T type of symbols and not W symbols.
> 
> My problem seems to be the ordering on the compiler command line. If `-lFuzzingEngine` comes _after_ the fuzz target `.o` file, I get a `W` symbol, and if I flip the order, with `.o` going last, I end up with a `T` symbol.

That's not it. My current guess is that it is a combination of effects from LTO and symbol visibility (meant for our library, but the `-fvisibility=hidden` leaks into fuzzer compilation as well). https://clang.llvm.org/docs/LTOVisibility.html
