### ISSUE TITLE
`libhfuzz.so` not getting installed

### ISSUE THREAD

**Issue by ckaran** [google/honggfuzz#339]
I'm trying to install hongfuzz via `sudo make install`, but this doesn't install `libhfuzz.so` or `libhfuzz.a`.  Looking through the Makefile, it appears that while the header files are installed correctly, there is no mention of the libraries themselves; perhaps this is an oversight?

**Comment by robertswiecki** [comment]
Spring cleaning, please re-open if needed

**Comment by ckaran** [comment]
It seems to be working at this point, so whatever was broken got fixed.  Thanks!
