### ISSUE TITLE
hfuzz-cc is missing on android build

### ISSUE THREAD

**Issue by George0x0** [google/honggfuzz#341]
Hi, I'm trying to compile honggfuzz for android(tried all available architectures), using a Ubuntu x64 machine as a host. While the honggfuzz binary itself is compiled successfully, the hfuzz-cc binary is missing. I used "make android ANDROID_APP_ABI=<arch>" and there were no errors during the build process.
If I compile the project for the host, linux x64, the hfuzz-cc binary is in place.
Any clue as to why that is? Any environment variables that should be set in order for this to work?

Thanks

**Comment by robertswiecki** [comment]
Please take a look at https://github.com/google/honggfuzz/issues/342 - it discusses it. You need to add some clang flags to enable coverage.

The reason for why there's no hfuzz-cc under Android, is that the fuzzed binaries were supposed to be built by the Android build system, where such flags are specified in build rules' definitions, and hfuzz-cc would not be needed in such case.

**Comment by Robert-Ostrowski-Jagoda** [comment]
Not all compilation flags are in the manual, it would be helpful if it would be in the manual.
As I'v figured out, it should look like that:
<path-to-ndk>\toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi26-clang++ -o test.exe test.cpp -I MY-INCLUDES-DIR -L MY-LIBRARIES-DIR -l hfuzz -l other-lib -llog -g -O3 -static-libstdc++ -static-libsan -fno-omit-frame-pointer -fsanitize=address,leak,undefined -fsanitize-coverage=trace-pc-guard,trace-cmp,trace-div,indirect-calls -mllvm -sanitizer-coverage-prune-blocks=0 -mllvm -sanitizer-coverage-level=3 -mllvm -inline-threshold=2000 

- sanitizers are optional
- MY-LIBRARIES-DIR should contain libhfuzz.a which can be found (after AOSP module compilation) in AOSP/out/target/product/generic/obj/STATIC_LIBRARIES/honggfuzz_libhfuzz_intermediates (not so obvious OO)
