### ISSUE TITLE
performance issue when trace-cmp is enabled

### ISSUE THREAD

**Issue by liumuqing** [google/honggfuzz#345]
`check64_cb` will be called at every `cmp` instruction, to check if the operand exists in fuzzed binary.

In my case it will takes about 20% cpu.

![Screenshot from 2020-06-18 17-15-44](https://user-images.githubusercontent.com/1625020/85013038-84d53f00-b196-11ea-9c4b-76781d7613c5.png)
![Screenshot from 2020-06-18 19-11-26](https://user-images.githubusercontent.com/1625020/85013659-88b59100-b197-11ea-8e92-a0d47b3e3bc7.png)

I think all 64bit values can be cached when `check64_cb` is called. Then following calls would be very fast. (by binary search or hash table lookup). 

check64_cb: https://github.com/google/honggfuzz/blob/4fff3e8/libhfcommon/util.c#L868

**Comment by robertswiecki** [comment]
Yes.. that's somewhat understandable. 

This mode of looking for constants inside binary yields very good results, so we can accept some CPU penalty.

Though, it can be controlled by this call: https://github.com/google/honggfuzz/blob/9e34b1bc435462e5e568b0ec079ea0769dfed617/libhfuzz/instrument.c#L375

I think 10% cpu penalty (or maybe 5%) would be a good tradeoff for the benefits. Could you try modifying (increasing) arguments to instrumentLimitEvery( )   (there are couple of such calls across this library), untill you hit 5 ot 10% overhead? Then we can implement those values (arguments to instrumentLimitEvery( )) based on your research

**Comment by liumuqing** [comment]
@robertswiecki  thank you for your repley, I didn't notice `instrumentLimitEvery` before...
while I still think `looking for constants inside binary` can be done much faster. 
the binary can be scanned only once, to record all distinct 64/32bit values into a hash set or a sorted vector.

Then `check64_cb` can be much faster, it will just take  O(1) or O(lg(n)).

**Comment by robertswiecki** [comment]
I think we can close it with https://github.com/google/honggfuzz/pull/351 now in. Thank you for working on that.
