### ISSUE TITLE
performace issue introduced by `wmb()`

### ISSUE THREAD

**Issue by liumuqing** [google/honggfuzz#346]
a `mfence` instruction (`wmb`) is added in `__sanitizer_cov_trace_pc_guard`, in commit f23dbfe1899bcc160055a42e747b993135e90acd.

On my environment, If I comment out `wmb()`, I can gain about 5~10% more runs per second (17000/s -> 19000/s)

If I understand correctly, since we are already using the atomic operation in `trace_pc_gurad`, memory barrier may be not necessary?

**Comment by robertswiecki** [comment]
Yup,

We use it quite indiscriminately (just in case). I should take a look at it, and limit the use to those really necessary cases. Some of them are probably needed though.
