### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by krytarowski** [google/honggfuzz#355]
Can we release a new release? Thanks.

**Comment by robertswiecki** [comment]
Yup, let me test that on couple of archs first, and I will release then

- [x] Linux amd64
- [ ] NetBSD
- [ ] OpenBSD
- [ ] MacOS X
- [ ] WSL2
- [ ] Cygwin
- [ ] Android

**Comment by robertswiecki** [comment]
Here it is https://github.com/google/honggfuzz/releases/tag/2.3

**Comment by krytarowski** [comment]
Great, thanks!

**Comment by krytarowski** [comment]
Sorry, for the trouble here is a quick fix: https://github.com/google/honggfuzz/pull/356

Can we release it as 2.3.1?

**Comment by robertswiecki** [comment]
Done - https://github.com/google/honggfuzz/releases/tag/2.3.1 - though let's treat it as a ninja release, w/o changing headers and changelogs.

**Comment by krytarowski** [comment]
Thanks!
