### ISSUE TITLE
Build Failure on macOS 10.14

### ISSUE THREAD

**Issue by ankane** [google/honggfuzz#357]
Hi, I'm hoping to add Honggfuzz to Homebrew, so Mac users can do `brew install honggfuzz`. Everything works great on macOS 10.13 and 10.15, but there's a compilation error with 10.14:

```txt
mac/mach_excServer.c:1:1: error: ISO C requires a translation unit to contain at least one declaration [-Werror,-Wempty-translation-unit]
```

Honggfuzz version: 2.3.1
Build logs: https://github.com/Homebrew/homebrew-core/pull/58418/checks?check_run_id=900590659
Ref: https://github.com/Homebrew/homebrew-core/pull/58418

**Comment by robertswiecki** [comment]
I have only access to Mac OS Sierra (10.12), and just fixed some compilation issues - https://github.com/google/honggfuzz/commit/6520ed24d0f569be0acfa28d13fbd0b88ddf0bb2

If there's some easy fix for newer ones, feel free to send some PRs my way, especially if it's a Makefile change.

E.g. in this case you probably want to add to Darwin's ```ARCH_CFLAGS``` in the ```Makefile``` the following:

```
-Wno-error=empty-translation-unit
```

**Comment by ankane** [comment]
Hey @robertswiecki, thanks for the response! I'll try to resubmit when the next release is out, or if it's close to EOL for 10.14 (later this year), just wait until then.
