### ISSUE TITLE
Where are the corpus files?

### ISSUE THREAD

**Issue by imanoracle** [google/honggfuzz#358]
Hi,

When we're using AFL, we can see queue folder to pass it to gcov (or use afl-cov) to check the coverage of each source code file. Where is this queue folder (based on my assumptions, corpus folder) when we are using Honggfuzz?

**Comment by robertswiecki** [comment]
With honggfuzz the input folder is the same as the output folder. You can change that behavior using ```--save_all``` or/and ```--output```
