### ISSUE TITLE
About the `--linux_ns_net` feature

### ISSUE THREAD

**Issue by elnx** [google/honggfuzz#362]
In the result of `honggfuzz -h`, there are something about the namespace feature:
```
 --linux_ns_net VALUE
        Use Linux NET namespace isolation (yes/no/maybe [default:maybe/if_supported])
```
When I tried `--linux_ns_net yes`, I found some problems:

- Actually, its default value is `HF_NO`.
- In `cmdline.c`, `cmdlineParseTriState` returns true/false instead of `tristate_t`, so `yes` equals to `maybe` .
- In main process, `arch_archInit` will create a namespace, <https://github.com/google/honggfuzz/blob/master/linux/arch.c#L373>
- When a sub process comes to <https://github.com/google/honggfuzz/blob/master/linux/arch.c#L106>, only if `run->global->arch_linux.useNetNs == HF_MAYBE`, will it create a new name space for itself.

So even if I use `--linux_ns_net yes`, honggfuzz only creates a namespace in the main process, not the sub process. According to my understanding , this feature should work like the graph below

```
                                          +----------------------------------+
                                          |               +---------------+  |
                                          | namespace 1   |   target      |  |
                                  +-------+               +---------------+  |
                                  |       +----------------------------------+
                                  |
+---------------------------------+       +----------------------------------+
|                                 |       |               +---------------+  |
|                                 +-------+ namespace 2   |   target      |  |
|          honggfuzz -n 4         |       |               +---------------+  |
|                                 |       +----------------------------------+
|                                 |
+---------------------------------+       +----------------------------------+
                                  |       |               +---------------+  |
                                  +-------+ namespace 3   |   target      |  |
                                  |       |               +---------------+  |
                                  |       +----------------------------------+
                                  |
                                  |       +----------------------------------+
                                  |       |               +---------------+  |
                                  |       | namespace 4   |   target      |  |
                                  +-------+               +---------------+  |
                                          +----------------------------------+

```

I am not sure what is the difference between the `yes` and `maybe`. A workaround is let the `cmdlineParseTriState` returns `tristate_t` and the `--linux_ns_net maybe` will work fine for me. (https://github.com/elnx/honggfuzz/commit/9b4bddf9f4a1f7d82a56017a0537182f099ddc48)

**Comment by robertswiecki** [comment]
Thanks for the report. It should be fixed now with https://github.com/google/honggfuzz/commit/90880cc6680e3d316db9aa6beb5974f8bebb39d8 and with https://github.com/google/honggfuzz/commit/075a51221c21fda506eddc0ff5aaa41e4af9df83
