### ISSUE TITLE
cannot find -lrt when Cross-Compiling fuzzer for Android

### ISSUE THREAD

**Issue by tr4v3ler** [google/honggfuzz#364]
`xxx@virtualbox:~/Downloads/honggfuzz/lessons/04$ hfuzz-cc first_fuzzer.cc -o first_fuzzer -fsanitize=address -fsanitize-coverage=trace-pc-guard -rpath /home/xxx/Tools/android-ndk-r21b/platforms/android-26/arch-arm64/usr/lib
/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)
xxx@virtualbox:~/Downloads/honggfuzz/lessons/04$ hfuzz-cc -v
Android (6317467 based on r365631c1) clang version 9.0.8 (https://android.googlesource.com/toolchain/llvm-project e0caee08e5f09b374a27a676d04978c81fcb1928) (based on LLVM 9.0.8svn)
Target: aarch64-unknown-linux-android26
Thread model: posix
InstalledDir: /home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin
Found candidate GCC installation: /home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x
Selected GCC installation: /home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld" -pie -z noexecstack -EL --fix-cortex-a53-843419 --warn-shared-textrel -z now -z relro -z max-page-size=4096 --hash-style=gnu --enable-new-dtags --eh-frame-hdr -m aarch64linux -dynamic-linker /system/bin/linker64 -o a.out /home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/26/crtbegin_dynamic.o -L/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.8/lib/linux/aarch64 -L/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x -L/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/../lib64 -L/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/26 -L/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android -L/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib -L/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib /home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/9.0.8/lib/linux/libclang_rt.ubsan_standalone-aarch64-android.so --wrap=strcmp --wrap=strcasecmp --wrap=strncmp --wrap=strncasecmp --wrap=strstr --wrap=strcasestr --wrap=memcmp --wrap=bcmp --wrap=memmem --wrap=strcpy --wrap=ap_cstr_casecmp --wrap=ap_cstr_casecmpn --wrap=ap_strcasestr --wrap=apr_cstr_casecmp --wrap=apr_cstr_casecmpn --wrap=CRYPTO_memcmp --wrap=OPENSSL_memcmp --wrap=OPENSSL_strcasecmp --wrap=OPENSSL_strncasecmp --wrap=memcmpct --wrap=xmlStrncmp --wrap=xmlStrcmp --wrap=xmlStrEqual --wrap=xmlStrcasecmp --wrap=xmlStrncasecmp --wrap=xmlStrstr --wrap=xmlStrcasestr --wrap=memcmp_const_time --wrap=strcsequal -u HonggfuzzNetDriver_main -u LIBHFUZZ_module_instrument -u LIBHFUZZ_module_memorycmp /home/xxx/Downloads/honggfuzz/obj/local/arm64-v8a/libhfnetdriver.a /home/xxx/Downloads/honggfuzz/obj/local/arm64-v8a/libhfuzz.a /home/xxx/Downloads/honggfuzz/obj/local/arm64-v8a/libcommon.a -ldl -lrt -lgcc -ldl -lc -lgcc -ldl /home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/lib/aarch64-linux-android/26/crtend_android.o
/home/xxx/Tools/android-ndk-r21b/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: cannot find -lrt
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I solved this problem by commenting out a line in the hfuzz-cc.c file :
#if !defined(_HF_ARCH_DARWIN) && !defined(__OpenBSD__)
    args[j++] = "-lrt";                                                                              // <-- comment this line
#endif /* !defined(_HF_ARCH_DARWIN) && !defined(__OpenBSD__) */

And I found out that there was no librt Library in Android from the [site](https://developer.android.com/ndk/guides/stable_apis):
`Note that on Android, unlike Linux, there are no separate libpthread or librt libraries. That functionality is included directly in libc, which does not need to be explicitly linked against.`
So I submitted this issue in the hope that it can be modified to avoid the same problem in the future！

**Comment by robertswiecki** [comment]
It compiles for me now (at HEAD). Please re-open if that's not the case for you.
