### ISSUE TITLE
Namespaces not enabled for FreeBSD 11.3

### ISSUE THREAD

**Issue by Fans0n-Fan** [google/honggfuzz#365]
netDriver_initNsIfNeeded():124 Honggfuzz Net Driver (pid=3572): Namespaces not enabled for this OS platform

Although Linux network namespaces can solve the problem of starting multiple TCP servers using same TCP ports，they work with Linux OS only.

So... how to solve this problem?

**Comment by Crypt-iQ** [comment]
I receive the same log message when running macOS Catalina v10.15.4

**Comment by robertswiecki** [comment]
It's Linux only feature. I think FreeBSD has jails, and maybe they could be repurposed, but AFAIR they're not as easy to set-up, e.g. they require root and additional IP?
