### ISSUE TITLE
Feature request: introspection into honggfuzz

### ISSUE THREAD

**Issue by vanhauser-thc** [google/honggfuzz#367]
Hey Robert,

I find honggfuzz' effectiveness really amazing.
On the other hand I find it very hard and a lot of effort to analyze what makes it possible to find a specific path or a bug.
Maybe could you add some introspection feature?
Best as an ifdef and make target so it does not hurt performance.

Basically if a new path or crash was triggered:
 * which queue entry was the fuzz attempt based on?
 * which mutations strategies were applied?
 * what target introspection was used? (e.g. dictionary, auto-dictionary, ...)

Thanks!

**Comment by robertswiecki** [comment]
I'll keep it mind for future development, but it won't be a fast addion :(

**Comment by vanhauser-thc** [comment]
as an incentive: you could use this to identify mutation strategies that are more successful than others and then give them a higher chance to be selected and hence improving fuzzing results.
