### ISSUE TITLE
Set HF_TEST_ADDR_CMPHASH as runtime flag

### ISSUE THREAD

**Issue by 0xAcid** [google/honggfuzz#369]
Hey there !
By playing around on a target, i noticed perf differences between older versions of Honggfuzz and master (x4 slowdown). I tracked that down to the `HF_TEST_ADDR_CMPHASH` define in https://github.com/google/honggfuzz/blob/master/libhfuzz/memorycmp.c#L18-L22

I can just set it to false, but I was wondering if adding it as a runtime option could be a thing ? (Or if you have any other plans for this maybe).

Thanks, and keep up the good work !

**Comment by robertswiecki** [comment]
Hi,

One can disable the functionality with ```--export_feedback=false```, but it'll disable much more. We can probably add a flag or experimental flag for this, CLs welcome anyone :)
