### ISSUE TITLE
Build Failure on macOS Big Sur 11.1

### ISSUE THREAD

**Issue by 4cce1er** [google/honggfuzz#375]
**1. first modify makeFile**
![image](https://user-images.githubusercontent.com/38617792/104724631-eaf56500-576b-11eb-9fea-9f179ec317d8.png)

**2. i guess this bug**
![image](https://user-images.githubusercontent.com/38617792/104724897-4d4e6580-576c-11eb-818d-ede5e0127d60.png)

stdout
`$ make
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o honggfuzz cmdline.o display.o fuzz.o honggfuzz.o input.o mangle.o report.o sanitizers.o socketfuzzer.o subproc.o mac/arch.o mac/mach_excServer.o mac/mach_excUser.o libhfcommon/libhfcommon.a  -pthread -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -lm -F/Applications/Xcode.app/Contents/SharedFrameworks -framework CoreSymbolicationDT -framework IOKit -F/System/Library/Frameworks -F/System/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/PrivateFrameworks -framework Foundation -framework ApplicationServices -framework CrashReporterSupport -F/Applications/Xcode.app/Contents/SharedFrameworks -framework SymbolicationDT -framework CoreServices -framework CoreFoundation -framework CommerceKit third_party/mac/CrashReport_Sierra.o
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_VMUProcInfo", referenced from:
      objc-class-ref in CrashReport_Sierra.o
  "_OBJC_CLASS_$_VMUSampler", referenced from:
      objc-class-ref in CrashReport_Sierra.o
  "_OBJC_CLASS_$_VMUVMRegionIdentifier", referenced from:
      objc-class-ref in CrashReport_Sierra.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [honggfuzz] Error 1`

**Comment by 4cce1er** [comment]
So I think third_party/mac/CrashReport_Sierra.o be renew compiled on MacOS 11.1 can fix this bug.

**Comment by robertswiecki** [comment]
Closing as duplicate of #371

**Comment by singleghost2** [comment]
> **1. first modify makeFile**
> ![image](https://user-images.githubusercontent.com/38617792/104724631-eaf56500-576b-11eb-9fea-9f179ec317d8.png)
> 
> **2. i guess this bug**
> ![image](https://user-images.githubusercontent.com/38617792/104724897-4d4e6580-576c-11eb-818d-ede5e0127d60.png)
> 
> stdout
> `$ make /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -o honggfuzz cmdline.o display.o fuzz.o honggfuzz.o input.o mangle.o report.o sanitizers.o socketfuzzer.o subproc.o mac/arch.o mac/mach_excServer.o mac/mach_excUser.o libhfcommon/libhfcommon.a -pthread -L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib -lm -F/Applications/Xcode.app/Contents/SharedFrameworks -framework CoreSymbolicationDT -framework IOKit -F/System/Library/Frameworks -F/System/Library/PrivateFrameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/PrivateFrameworks -framework Foundation -framework ApplicationServices -framework CrashReporterSupport -F/Applications/Xcode.app/Contents/SharedFrameworks -framework SymbolicationDT -framework CoreServices -framework CoreFoundation -framework CommerceKit third_party/mac/CrashReport_Sierra.o Undefined symbols for architecture x86_64: "_OBJC_CLASS_$_VMUProcInfo", referenced from: objc-class-ref in CrashReport_Sierra.o "_OBJC_CLASS_$_VMUSampler", referenced from: objc-class-ref in CrashReport_Sierra.o "_OBJC_CLASS_$_VMUVMRegionIdentifier", referenced from: objc-class-ref in CrashReport_Sierra.o ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [honggfuzz] Error 1`

Do you have a patch file? Or could you open an pull request to merge it to the master branch? Thansk! :>
