### ISSUE TITLE
ptrace() instrumentation and shared libraries

### ISSUE THREAD

**Issue by marklandosek** [google/honggfuzz#377]
Hi

When I use ptrace() for binary fuzzing the loaded shared libraries (.so) are 'ptrace() instrumented' too? If no there is a flag that allows me todo that (e.g. like afl++ qemu mode AFL_INST_LIBS=1)

**Comment by robertswiecki** [comment]
We don't have ```ptrace()``` instrumentation, only software, hardware and qemu. Which one are you referring to?

**Comment by robertswiecki** [comment]
Please re-open if needed.
