### ISSUE TITLE
Add Option to consider timeout equivalent to a crash

### ISSUE THREAD

**Issue by TheBlueMatt** [google/honggfuzz#378]
I may be dense and just missing how to do this, but it would be nice to have an option which allows me to consider a timeout a test failure - its easy to add timeouts which will catch infinite loops which its reasonable to care about detecting using honggfuzz.

**Comment by robertswiecki** [comment]
It's ```-T```

**Comment by TheBlueMatt** [comment]
Ah! Thanks. Maybe the docs for `-T` could be updated to be slightly clearer? Its not clear to me that SIGVTALRM implies that.

**Comment by robertswiecki** [comment]
Good idea! - I added more explanatory description in https://github.com/google/honggfuzz/commit/97095d7b5e481fe29da74bd882a1137728a7ee32
