### ISSUE TITLE
/dev/fd/<n> breaking some applications

### ISSUE THREAD

**Issue by ploppelop** [google/honggfuzz#391]
the convention of /dev/fd/<n> breaks any applications which expect a certain file extension for the input

**Comment by robertswiecki** [comment]
What about the following mode?

In cwd you create a symlink

```ln -s /dev/fd/1021 input.<yourdesiredextension>```

Then, you run honggfuzz as

```honggfuzz -s -- path/to/binary input.<yourdesiredextension>```

**Comment by ploppelop** [comment]
while true ; do file /tmp/input.pdf 2>&1 | grep -vi "broken symbolic link" ; done
<nothing>
 while true ; do ls -laF /dev/fd/1021 2>/dev/null ; done
<nothing>

honggfuzz is being executed via:
honggfuzz -s -t 3 -n 14 -e pdf -c /Users/ploppelop/gen.sh -i arc/ -v -d -Q -x -- /Applications/Adobe\ Acrobat\ Reader\ DC.app/Contents/MacOS/AdobeReader /tmp/input.pdf

gen.sh basically does this:

#!/bin/sh
echo called with $*
generate-pdf > $*

Regular launching of /Applications/Adobe\ Acrobat\ Reader\ DC.app/Contents/MacOS/AdobeReader /tmp/<the generated pdf files>.pdf works fine, and maybe 1 in 20 executions succeed

**Comment by robertswiecki** [comment]
I'm not sure if I see the whole picture.

Did you do 

```ln -s /dev/fd/1021 /tmp/input.pdf``` first?

**Comment by ploppelop** [comment]
Sorry, yes I did make the symlink. Things actually work as expected for this if I remove the external mutator - back when I last used honggfuzz (and it was still creating files on disk) it was enough to just take the first argument fed to the mutator, modify things and put it back in the same file for it to be picked up by the launching mechanisms - has this changed significantly or am I missing something else? It (being nothing working properly) reproduces with this for -c 

cat /tmp/mutate.sh
#!/bin/sh
echo hello
cat $1 > tmpdoc
echo not doing anything
cat tmpdoc > $1

**Comment by ploppelop** [comment]
hm I was apparently running on an old version, everything works as intended with git version, thanks for the tip on the extension though, and thanks for honggfuzz
