### ISSUE TITLE
Dictionary Size Limit

### ISSUE THREAD

**Issue by mvanotti** [google/honggfuzz#403]
Is there a reason for the size limit in the dictionary?

```text
[2021-06-06T22:56:28-0700][W][103485] input_parseDictionary():217 Maximum number of dictionary entries '1024' alread loaded. Skipping the rest
```

I am trying to fuzz nasm, the netwide assembler, and I thought it would be fine to add a dictionary with all the instructions that are supported, which are quite a lot (>2000). Is this not a correct use for a dictionary?

**Comment by robertswiecki** [comment]
Hi,

The size has been increased with https://github.com/google/honggfuzz/commit/7eecfc991d0ae540d9773a6feb8fac5012a55ed6

**Comment by mvanotti** [comment]
Thanks for fixing this, Robert!
