### ISSUE TITLE
RISC-V support

### ISSUE THREAD

**Issue by smargome** [google/honggfuzz#407]
More of a question, to save me some precious time, than an issue. Will Honggfuzz compile and run successfully on a RISC-V processor (BOOM)?

**Comment by robertswiecki** [comment]
For full suport you'd have to add proper register definitions and some small stub code (for fetching the current program counter) somewhere here - https://github.com/google/honggfuzz/blob/6f89ccc9c43c6c1d9f938c81a47b72cd5ada61ba/linux/trace.c#L77

Alternatively, it might just work with OS=POSIX but you will not get all features (unwinding, tracing etc.) with it

OS=POSIX make all

**Comment by smargome** [comment]
So, something similar to [this](https://github.com/thebabush/honggfuzz-qemu/blob/honggfuzz/gdb-xml/riscv-32bit-cpu.xml), but in the file you mentioned, with proper format and some extra code to handle the RISCV case, correct?
