### ISSUE TITLE
Not be staying new input

### ISSUE THREAD

**Issue by Savitar407** [google/honggfuzz#423]
Hi I am very new to honggfuzz and I am fuzzing my first binary with this program. I have been running the fuzzer for 20 hours now and the fuzzer is not generating new inputs (I only see about 5 in the input folder and I started with one called input.txt) I instrumented with hfuzz-cc. And new coverage is not bring found

Thanks,

**Comment by robertswiecki** [comment]
You might get more answers, if you send such requests to e.g. https://groups.google.com/g/honggfuzz - there're more honggfuzz users there.
