### ISSUE TITLE
hfuzz-clang doesn't seem to be compatible with -target bpf

### ISSUE THREAD

**Issue by evverx** [google/honggfuzz#434]
systemd uses `-target bpf` to compile bpf skeletons that are loaded by libbpf via the "bpf" system call and as far as I understand code compiled with `-target bpf` shouldn't be instrumented (though I don't know whether there are other use cases where it should be instrumented). For now, I just replaced `clang-hfuzz` with `clang` in https://github.com/systemd/systemd/pull/21859

```
$ hfuzz-clang --version
clang version 13.0.0 (Fedora 13.0.0-3.fc35)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

git clone --depth=1 https://github.com/systemd/systemd &&
    cd systemd &&
    hfuzz-clang -Wno-compare-distinct-pointer-types -O2 -target bpf -g -c -D__x86_64__ -I.   src/core/bpf/restrict_ifaces/restrict-ifaces.bpf.c -o src/core/bpf/restrict_ifaces/restrict-ifaces.bpf.unstripped.o

PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: clang -I/home/vagrant/honggfuzz/includes/ -Wno-unused-command-line-argument -mllvm -inline-threshold=1000 -fno-builtin -fno-omit-frame-pointer -D__NO_STRING_INLINES "-DHFND_FUZZING_ENTRY_FUNCTION_CXX(x,y)=extern const char* LIBHFNETDRIVER_module_netdriver;const char** LIBHFNETDRIVER_tmp1 = &LIBHFNETDRIVER_module_netdriver;extern \"C\" int HonggfuzzNetDriver_main(x,y);int HonggfuzzNetDriver_main(x,y)" "-DHFND_FUZZING_ENTRY_FUNCTION(x,y)=extern const char* LIBHFNETDRIVER_module_netdriver;const char** LIBHFNETDRIVER_tmp1 = &LIBHFNETDRIVER_module_netdriver;int HonggfuzzNetDriver_main(x,y);int HonggfuzzNetDriver_main(x,y)" -Wno-compare-distinct-pointer-types -O2 -target bpf -g -c -D__x86_64__ -I. src/core/bpf/restrict_ifaces/restrict-ifaces.bpf.c -o src/core/bpf/restrict_ifaces/restrict-ifaces.bpf.unstripped.o -fsanitize-coverage=trace-pc-guard,trace-cmp,trace-div,indirect-calls
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module 'src/core/bpf/restrict_ifaces/restrict-ifaces.bpf.c'.
4.	Running pass 'BPF Assembly Printer' on function '@sancov.module_ctor_trace_pc_guard'
 #0 0x00007f4b49ee29a6 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM-13.so+0xb5f9a6)
 #1 0x00007f4b49ee0734 llvm::sys::RunSignalHandlers() (/lib64/libLLVM-13.so+0xb5d734)
```

**Comment by robertswiecki** [comment]
Thanks for the report. Given it seems like a bug (?) in llvm, and this seems to be rather nuanced use of instrumentation, I don't think I'll work on it any time soon. I guess we'll leave this bug for the record then, so others might find it in case they hit the same problem? Please re-open if you'd like to work on it, or think that it's important to make it work for others too.

**Comment by evverx** [comment]
>  I guess we'll leave this bug for the record then, so others might find it in case they hit the same problem? 

Agreed.

> Please re-open if you'd like to work on it, or think that it's important to make it work for others too

As far as I understand BPF skeletons are relatively new in general and they are usually used in tools like https://github.com/iovisor/bcc that aren't fuzzable (in user space at least) so I doubt other projects will run into anything like that in the foreseeable future. I think that workaround should suffice for now. Thanks!
