### ISSUE TITLE
honggfuzz seems to crash on Fedora 36

### ISSUE THREAD

**Issue by evverx** [google/honggfuzz#463]
I tried to fuzz `systemd` in a Fedora 36 container and somehow triggered the following crash:
```sh
LD_LIBRARY_PATH=/systemd/zstd/lib honggfuzz -i INPUT -o OUT -t 30 -- ./build/fuzz-compress ___FILE___
```
```sh
Thread 2 "honggfuzz" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeeb9a640 (LWP 51209)]
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00000000004151e7 in arch_bfdDisasm (pid=51387, mem=0x7fffeeb867b0 "\305~oD\026\340H)\376H\203\341\340H\001\316\020", size=16, instr=0x7fffeeb8a930 "[UNKNOWN]") at linux/bfd.c:249
#2  0x00000000004169c7 in arch_getInstrStr (pid=51387, pc=140737197724044, status_reg=66054, pcRegSz=216, instr=0x7fffeeb8a930 "[UNKNOWN]") at linux/trace.c:552
#3  0x0000000000416f14 in arch_traceSaveData (run=0x7fffeeb8ab10, pid=51387) at linux/trace.c:688
#4  0x0000000000417c0d in arch_traceAnalyze (run=0x7fffeeb8ab10, status=2943, pid=51387) at linux/trace.c:921
#5  0x0000000000413f9e in arch_checkWait (run=0x7fffeeb8ab10) at linux/arch.c:232
#6  0x0000000000414107 in arch_reapChild (run=0x7fffeeb8ab10) at linux/arch.c:265
#7  0x0000000000412fa5 in subproc_Run (run=0x7fffeeb8ab10) at subproc.c:441
#8  0x000000000040996d in fuzz_fuzzLoop (run=0x7fffeeb8ab10) at fuzz.c:406
#9  0x000000000040a040 in fuzz_threadNew (arg=0x70b0e0 <hfuzz>) at fuzz.c:542
#10 0x00007ffff7cece1d in start_thread (arg=<optimized out>) at pthread_create.c:442
#11 0x00007ffff7d725e0 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```
I can't seem to reproduce it on Fedora 35 so I suspect it probably has something to do with the build dependencies. `hongfuzz` was compiled with `gcc-12` and `glibc-2.35-11.fc36.x86_64`, `libgcc-12.1.1-1.fc36.x86_64`, `libunwind-1.6.2-2.fc36` and `binutils-devel-2.37-27.fc36.src.rpm` were installed there.

**Comment by robertswiecki** [comment]
Could you try with HEAD or https://github.com/google/honggfuzz/commit/90fdf81006614664ef05e5e3c6f94d91610f11b2 ? Unfortunately libbfd has an unstable public API, and it's problematic to keep in sync with it.

**Comment by evverx** [comment]
The fuzz target has been running for about 5 minutes without any crashes and it triggered a couple of crashes related to https://github.com/advisories/GHSA-gmc7-pqv9-966m as expected. Thanks!

**Comment by evverx** [comment]
What's weird though is that the same crashes were marked unique. It could be I screwed something up so I'll try to double-check and report back. Thanks again!
