### ISSUE TITLE
Build Error on Linux with libbfd-2.38

### ISSUE THREAD

**Issue by Vectrixx** [google/honggfuzz#464]
Hello,
Honggfuzz doesn't build on Linux Ubuntu 22.04 with libbfd version 2.38.
libbfd-dev is in version 2.34 on Ubuntu 20.04. 
![image](https://user-images.githubusercontent.com/12973424/172633444-45f6ea68-063a-43f1-ba44-f95be6869fb9.png)

![image](https://user-images.githubusercontent.com/12973424/172634005-945f79be-10b0-47c4-8d62-80700d955f6e.png)

**Comment by robertswiecki** [comment]
Please try at https://github.com/google/honggfuzz/commit/8c03e5253536f692350fd71dac7b9129ba4f9323 - but I don't think there's ultimately a good way to discover those libopcode changes at build-time.
