### ISSUE TITLE
strlcat and strlcpy break Samba configure

### ISSUE THREAD

**Issue by douglasbagnall** [google/honggfuzz#496]
After the recent addition of `strlcat` and `strlcpy`, Samba's configure system no longer works with hfuzz-clang.

What it comes down to, is we compile this
```
extern char strlcpy();
int main() { return strlcpy(); }
```
and try to link it with or without `-lbsd`. Ordinarily on Linux the linking fails without `-lbsd`, but now it succeeds with hfuzz-clang. There are also compile checks for macro aliases that look like this:
```
int main(void) { void *__x = (void *)strlcpy; return (int)__x;  }
```
but those don't get run in the hfuzz-clang case, because the first linking check succceeds.

Samba has its own versions of the `strlc..` functions, but if the they are found either natively or in libbsd, then the respective library is used (i.e. by skipping Samba's ones, including `bsd/string.h` in the libbsd case).

What happens now is hfuzz-clang *appears* to have these functions at configure time, but when it comes to the actual compilation, it seems not to, resulting in this kind of error:

```
../../lib/replace/replace.c:837:3: error: implicit declaration of function 'strlcpy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                strlcpy(buf, s, buflen);
                ^
```

I am not sure what is up, or whether the bug lies in Samba's build system or with Honggfuzz.

To reproduce with Samba and Honggfuzz main branches:
```
$ PYTHONHASHSEED=1 buildtools/bin/waf  --without-gettext --enable-debug --enable-developer --enable-libfuzzer   CC=~/src/honggfuzz/hfuzz_cc/hfuzz-clang configure LINK_CC=~/src/honggfuzz/hfuzz_cc/hfuzz-clang --disable-warnings-as-errors  --abi-check-disable

$ make -j8
```
The configure line write a log in `bin/config.log` which includes all the test files and compiler calls.

For more verbosity, add `-vvv` to the configure line, and replace the make with `$ WAF=PYTHONHASHSEED=1 WAF_MAKE=1 ./buildtools/bin/waf build -vvv`.

@devnexen maybe you have thoughts.

I'll post the full successful and unsuccessful compiler calls in a following comment.

**Comment by douglasbagnall** [comment]
So, of course, what I missed is the configure test is checking for library symbols, while the compilation is failing on the functions not being declared in the source code. That is, Samba's configure is using the linkability of `strlcpy` and `strlcat` as a proxy for the necessity of adding `#include <bsd/string.h>`. That's wrong. 

OTOH, I think Honggfuzz might be slightly  treading new ground here. I'm guessing normally if you have those symbols in the system library, you have them in system headers, as per https://man.freebsd.org/cgi/man.cgi?query=strlcpy&sektion=3?

```
hfuzz_cc/hfuzz-clang -D_SAMBA_BUILD_=4 -DHAVE_CONFIG_H=1 -MMD -D_GNU_SOURCE=1 -D_XOPEN_SOURCE_EXTENDED=1 -I. -I../.. -I. -I../.. ../../test.c -c -osamba-fuzz/bin/.conf_check_cfeb54db47c3c14d04c387915dd5ff43/testbuild/default/test.c.1.o
hfuzz-clang test.c.1.o -osamba-fuzz/bin/.conf_check_cfeb54db47c3c14d04c387915dd5ff43/testbuild/default/testprog -Wl,-Bstatic -Wl,-Bdynamic -L/usr/local/lib
```
vs
```
hfuzz-clang -D_SAMBA_BUILD_=4 -DHAVE_CONFIG_H=1 -MMD -D_GNU_SOURCE=1 -D_XOPEN_SOURCE_EXTENDED=1 -DHAVE_CONFIG_H=1 -D_SAMBA_HOSTCC_ -DDEVELOPER -DDEBUG_PASSWORD -fPIC -D__STDC_WANT_LIB_EXT1__=1 -D_REENTRANT -DDEVELOPER -DDEBUG_PASSWORD -fstack-protector-strong -fstack-clash-protection -g -g -Wall -Wshadow -Wmissing-prototypes -Wmissing-field-initializers -Wformat-zero-length -Wcast-align -Wcast-qual -fno-common -Werror=address -Werror=strict-prototypes -Wstrict-prototypes -Werror=write-strings -Wwrite-strings -Werror-implicit-function-declaration -Werror=implicit-int -Werror=pointer-arith -Wpointer-arith -Werror=declaration-after-statement -Wdeclaration-after-statement -Werror=return-type -Wreturn-type -Werror=uninitialized -Wuninitialized -Wimplicit-fallthrough -Werror=strict-overflow -Wstrict-overflow=2 -Werror=old-style-definition -Wold-style-definition -Wformat=2 -Wno-format-y2k -Wno-format-zero-length -Werror=format-security -Wformat-security -Werror=format -DSTATIC_LIBREPLACE_HOSTCC_MODULES=NULL -DSTATIC_LIBREPLACE_HOSTCC_MODULES_PROTO=extern void __LIBREPLACE_HOSTCC_dummy_module_proto(void) -Ilib/replace -I../../lib/replace -Iinclude/public -I../../include/public -Isource4 -I../../source4 -Ilib -I../../lib -Isource4/lib -I../../source4/lib -Isource4/include -I../../source4/include -Iinclude -I../../include -I. -I../.. ../../lib/replace/replace.c -c -osamba-fuzz/bin/default/lib/replace/replace.c.1.o

../../lib/replace/replace.c:837:3: error: implicit declaration of function 'strlcpy' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                strlcpy(buf, s, buflen);
```

**Comment by robertswiecki** [comment]
Hi,

IMO, this is a more preprocessing error, than anything related to compilation. hfuzz-clang changes some compilation options, but rather nothing related to inclusion of headers, and it seems that replace.c simply is missing some header?

As in, hfuzz-clang during the linking stage is providing its own weak symbols for strlcpy and such, but this error looks like something happening at compilation stage.

Maybe if you removed this https://github.com/google/honggfuzz/blob/master/hfuzz_cc/hfuzz-cc.c#L366C5-L366C5 it will start working?

**Comment by douglasbagnall** [comment]
Yes, I also came to the conclusion it was a bug in the Samba build assumptions, to be fixed with something like
https://gitlab.com/samba-team/devel/samba/-/commit/ed7383cad34d84abca8c15dae8746ccafada0051

So I haven't tried this:
> Maybe if you removed this https://github.com/google/honggfuzz/blob/master/hfuzz_cc/hfuzz-cc.c#L366C5-L366C5 it will start working?

as the Samba patch works.

Thanks.
