### ISSUE TITLE
fuzz bug about open fuzzed file with app 

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#59]
some time use honggfuzz to fuzz, it can't open the file with fuzzed app,for example(Preview in Mac OSX):

honggfuzz -f /Volumes/Macintosh/Samples/pdf/ -n 3  -- /Applications/Preview.app/Contents/MacOS/Preview  ___FILE___

it only open the Preview, but it can't open the fuzzed pdf file with Preview.

**Comment by robertswiecki** [comment]
You need to find out how to open a file with Preview, maybe it uses some other positional arguments?

/Applications/Preview.app/Contents/MacOS/Preview -f ___FILE___ or somesuch?

Also, if it's a graphical application it'd be good to lower the time limit (-t) and maybe increase concurrency (-n) so you'r fuzzer don't wait on doing nothing.

**Comment by riusksk** [comment]
In console, use the following command to open fuzzed file is ok, but open with honggfuzz is bad.
`/Applications/Preview.app/Contents/MacOS/Preview  /test/test.pdf`

it's a graphical app，using -t  and -n params are still invaild.

**Comment by robertswiecki** [comment]
From what I can see looking at https://github.com/google/honggfuzz/blob/master/mac/arch.c the MacOS X code doesn't do much before executing the binary. So, as I don't have access to mac, I'm not sure how to help

PS. Maybe @tl0gic or @felixgr  would be able to take a look, as they're our resident MacOS experts

**Comment by robertswiecki** [comment]
I'm closing this, as it seems it's related to use of a specific app. Please re-open if you think we can help you somehow.
