### ISSUE TITLE
ARM CoreSight Tracing

### ISSUE THREAD

**Issue by Manouchehri** [google/honggfuzz#63]
Similar to Intel PT, ARM has a feature called [CoreSight Tracing](http://www.arm.com/products/system-ip/debug-trace/). I'm not sure how useful it would be to honggfuzz, but I thought I'd mention it and see if anyone else is interested.

- Using the OpenCSD library with perf - https://github.com/Linaro/OpenCSD/blob/arm-dev/HOWTO.md
- Python Based ARM CoreSight Debug and Trace Tools - https://github.com/deadsy/pycs

**Comment by robertswiecki** [comment]
I played a bit with CoreSight on Raspberry PI and it doesn't seem to be in usable state. Kernel and perf patches are needed to make it work (OpenCSD). I think we'll have to wait some time to make them into the mainline kernel.

**Comment by rpw** [comment]
The Raspberry Pi is not suitable hardware since Broadcom does not expose the ETM Macrocell in the device tree. Try a Dragonboard 410c with Linaro 17.06 -- this gets you a Linux 4.9 kernel that exposes CoreSight tracing through the perf subsystem.

Might be able to contribute a patch for this.
