### ISSUE TITLE
Benchmarks of different feedback-driven fuzzing types?

### ISSUE THREAD

**Issue by Manouchehri** [google/honggfuzz#76]
It would be useful if someone with a Skylake CPU could post some example benchmarks of the different types of feedback-driven fuzzing.
- `--linux_perf_bts_block`
- `--linux_perf_bts_edge`
- `--linux_perf_ipt_block`
- `--linux_perf_instr`
- `--linux_perf_branch`

I would do it myself, but I don't have any Skylake CPUs and all the cloud instances I've seen don't allow using PT or BTS.

**Comment by slyrz** [comment]
I ran 250.000 iterations on a persistent program with a well-behaved function 
(that does not crash), these were the timings I measured:

|NAME                       |  TIME | ITER/S |
|---------------------------|------:|-------:|
|fsanitize_coverage         | 0.30s | 833333 |
|finstrument_functions      | 0.36s | 694444 |
|linux_perf_instr           | 0.43s | 581395 |
|linux_perf_branch          | 0.46s | 543478 |
|linux_perf_ipt_block       | 5.33s |  46904 |
|linux_perf_bts_block       | 9.47s |  26399 |
|linux_perf_bts_edge        | 9.74s |  25667 |

**Comment by Manouchehri** [comment]
Thanks!
