### ISSUE TITLE
about unique crash check bug

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#80]
the function of unique crash check have a bug, for example, the fllowing crash files are same bug, beacause stack is dynamic addr(they are diff in each run) ,but both pc and instr are same.
```
SIGABRT.PC.7ffff695ecc9.STACK.187f3bf740.CODE.-6.ADDR.(nil).INSTR.cmp____$0xfffffffffffff000,%rax.pdf
SIGABRT.PC.7ffff695ecc9.STACK.18b82e134b.CODE.-6.ADDR.(nil).INSTR.cmp____$0xfffffffffffff000,%rax.pdf
SIGABRT.PC.7ffff695ecc9.STACK.29504b171.CODE.-6.ADDR.(nil).INSTR.cmp____$0xfffffffffffff000,%rax.pdf
```

**Comment by robertswiecki** [comment]
Hi,

What stack-traces do you see in HONGGFUZZ.REPORT.TXT for those crashes?

**Comment by robertswiecki** [comment]
SIGABRT gives the same add/pc because it's almost always called thtough abort() function. Therefore it's the same process's location. But only stack-trace can tell you how program got there - and that's why you have differing STACK values.

**Comment by riusksk** [comment]
stack-traces are same:
STACK:
 <0x00007ffff69620d8> [[UNKNOWN]():0]
 <0x0000000000f1ee69> [_Z23FX_OutOfMemoryTerminatev():0]
 <0x000000000057d68e> [_Z13FX_AllocOrDiemm():43]
……

**Comment by robertswiecki** [comment]
Hi,

what's important is below those functions.. The stack shows how you got to a function calling SIGABRT, even if SIGABRT is called from the same function.

If your stack-traces are totally identical, please let me know, and I'll take a look. But it'd be good if you pasted them complete.
