### ISSUE TITLE
files_mapSharedMem() is failing on Android

### ISSUE THREAD

**Issue by anestisb** [google/honggfuzz#87]
Android has no "/tmp" as such files_mapSharedMem() will fail:

https://github.com/google/honggfuzz/blob/master/files.c#L494
```
void *files_mapSharedMem(size_t sz, int *fd)
{
    char template[] = "/tmp/hfuzz.XXXXXX";
    if ((*fd = mkstemp(template)) == -1) {
        PLOG_W("mkstemp('%s')", template);
        return MAP_FAILED;
    }
    unlink(template);
```

Also considering the SELinux enforcing limitations if fuzzing against Android production images, I think the best approach would be to create file under the workspace directory (`hfuzz->workDir`).

Something like the following:
```
    char template[PATH_MAX] = { 0 };
    snprintf(template, sizeof(template), "%s/%s", hfuzz->workDir, "hfuzz_SHMEM.XXXXXX");
    if ((*fd = mkstemp(template)) == -1) {
```

I haven't pushed a pull request since I'm not sure what would be your preferred way of dealing with the func arguments in case you want to keep the method as abstract as possible for other usages too.

**Comment by robertswiecki** [comment]
Good idea, implemented in 5b81a507643556cb8a07e157e21572494a44dee9
