### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [google/honggfuzz#9]
I suggest to add the key word "const" to the type specifiers for parameters like the following.
* fileName (function "[files_readFileToBufMax](https://github.com/google/honggfuzz/blob/4f1124fb655c0dab2e18a130199e5f15ab013585/files.h#L32)")
* s (function "[report_Report](https://github.com/google/honggfuzz/blob/3b630b47e7d39e7b36c749290385e284bc5eb950/report.h#L27)")

Would you like to apply the advices from [an article](https://en.wikipedia.org/w/index.php?title=Const_%28computer_programming%29#Consequences "const-correctness") to more places in your source files?

**Comment by robertswiecki** [comment]
Sure, do you wish to create a patch, or would you like for project collaborators to do it?

**Comment by robertswiecki** [comment]
I think we're good with this regard, and I additionally improved const-correctness here and there. Please feel free to submit patches for whatever else you feel would be good to have.

**Comment by elfring** [comment]
* To which commits would you like to refer to for the mentioned const-correctness improvements?
* Why were [the places I pointed out](https://github.com/google/honggfuzz/blob/876a74cb9c3300543b346da7bf9a965b601af137/files.h#L32 "Update candidates") not picked up so far?
