### ISSUE TITLE
Won't build on OS X: El Capitan 10.11.6

### ISSUE THREAD

**Issue by varnerac** [google/honggfuzz#90]
When I run

```
make
Makefile:94: *** "macosx10.11" not found in /Library/Developer/CommandLineTools.  Stop.
```

Machine info:

```
uname -a
Darwin mac.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_
```

Let me know what other info I can provide.

**Comment by anestisb** [comment]
Have you installed xcode command line tools? If not, run from a terminal the following:
```
xcode-select --install
```

**Comment by varnerac** [comment]
```
xcode-select --install
xcode-select: error: command line tools are already installed, use "Software Update" to install updates
```

**Comment by anestisb** [comment]
Xmm then probably something is wrong with you xcode env paths. Does you machine output matches the following:
```
anestisb@blackbird:[~]: xcrun --sdk "macosx10.11" --show-sdk-path; xcode-select -p
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
/Applications/Xcode.app/Contents/Developer
```

**Comment by varnerac** [comment]
```
xcrun --sdk "macosx10.11" --show-sdk-path; xcode-select -p

/Library/Developer/CommandLineTools
```

The newline in the middle appears in the output and is not a formatting artifact.

**Comment by anestisb** [comment]
Ok so something in you env has modified wrongly the xcode path. Run the following to repair and you should be ok:
```
sudo xcode-select -r
```

**Comment by varnerac** [comment]
```
mac$ sudo xcode-select -r
mac$ make
Makefile:94: *** "macosx10.11" not found in /Library/Developer/CommandLineTools.  Stop.
```

**Comment by anestisb** [comment]
That is very weird. Have you installed Xcode in a directory other than /Applications? Also try the following since the default paths seems to be broken:
```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

Replace the path with the correct one in case you installed Xcode in a different location.

**Comment by varnerac** [comment]
Ok, I think I have a better grasp on this. I have downloaded the XCode command line tools only. I did not download the entire IDE. I believe these are two different options. I do not intend to download the IDE. It looks like the `Makefile` is simply looking for my compiler, which it shows. However, the error message that is printed beforehand seems to mess things up.

```
$ xcrun --show-sdk-version
10.11
$ xcrun --sdk 10.11 --find cc
xcrun: error: SDK "10.11" cannot be located
/Library/Developer/CommandLineTools/usr/bin/cc
$ xcrun --find cc
/Library/Developer/CommandLineTools/usr/bin/cc
```

**Comment by anestisb** [comment]
If you don't install the entire Xcode IDE you'll be missing the framework libraries & other bits. As such I don't think your approach will work. At any case you can comment line 94 at the Makefile and give a try in case you can circumvent the problems that will arise.

**Comment by varnerac** [comment]
Ah, yes. It looks like the SDK (full IDE) provides the crash reporter framework which this project needs. Thanks.
