### ISSUE TITLE
how to solve it that required the fuzzed file path must use quotation marks

### ISSUE THREAD

**Issue by riusksk** [google/honggfuzz#91]
I test in Windows, for example:
```
 rundll32.exe shimgvw.dll,ImageView_Fullscreen "C:\Users\Administrator\Desktop\test.jpg"
```
it can't open image if you don't use quotation marks,  I try to fuzz with the following cmd, but no effect:
```
./honggfuzz.exe -f "C:\Users\Administrator\Desktop\test.jpg" -t3 -e jpg -- rundll32.exe shimgvw.dll,ImageView_Fullscreen \"___FILE___\"
```

how to solve it ?

**Comment by robertswiecki** [comment]
So, for Windows we use CygWin, but I have no idea how Cygwin treats inputs - i.e. how the tokenization for execve works.

I can presume that if you're using bash under cygwin, it'll work sort-a like with Unix?

**Comment by robertswiecki** [comment]
Try rundll32.exe shimgvw.dll,ImageView_Fullscreen '"C:\Users\Administrator\Desktop\test.jpg"' (i.e. surround it by single quotes.

The shell substitution will work like for generla bash I guess, your goal is to display

"C:\Users\Administrator\Desktop\test.jpg"

with the echo command.

Try (surrounded by single-quotes)

$ echo '"C:\Users\Administrator\Desktop\test.jpg"'
"C:\Users\Administrator\Desktop\test.jpg"

**Comment by riusksk** [comment]
I run it under cygwin,  it can open image file after use system() and add full path into fileName var, but can't auto close gui windows, which  cause unable to continue to fuzzing the next file.
