### ISSUE TITLE
intel syntax in assembly output

### ISSUE THREAD

**Issue by kokanin** [google/honggfuzz#95]
can we have this in some easy way, as opposed to at&t?

**Comment by robertswiecki** [comment]
You'd probably have to take a look at libbfd, possibly there's some option to force the disassembly flavor.

Then, you can try to modify bfd init somewhere here: https://github.com/google/honggfuzz/blob/master/linux/bfd.c#L173

Possibly you need to change

info.mach = bfd_get_mach(bfdh);

to

info.mach = bfd_mach_x86_64_intel_syntax;

of course, this will work only for Intel x86-64 bins
